## Kayak Project - Eric Nguyen 🎯

### Récupération de coordonées GPS pour une trentaines de villes françaises

In [8]:
# Packages 
import requests
import pandas as pd
import asyncio
from geopy.geocoders import Nominatim
import time
import os
from dotenv import load_dotenv

In [9]:
load_dotenv()
# Accéder à la variable appid
appid = os.getenv('appid')

In [2]:
town_name = ["Mont Saint Michel","Saint Malo","Bayeux","Le Havre","Rouen","Paris","Amiens","Lille","Strasbourg","Chateau du Haut Koenigsbourg","Colmar","Eguisheim","Besancon","Dijon","Annecy","Grenoble","Lyon","Gorges du Verdon","Bormes les Mimosas","Cassis","Marseille",
"Aix en Provence","Avignon","Uzes","Nimes","Aigues Mortes","Saintes Maries de la mer","Collioure","Carcassonne","Ariege","Toulouse","Montauban","Biarritz","Bayonne","La Rochelle"]

geolocator = Nominatim(user_agent="eric_jedha")
location = geolocator.geocode("Lille")
best_towns = []

for geo in town_name:
  geolocator = Nominatim(user_agent="eric_jedha")
  location = geolocator.geocode(geo)
  time.sleep(5)
  best_towns.append({'Towns' : location[0].split(",")[0], 
                            'Latitude' : location[1][0],
                            'Longitude' : location[1][1],
                 })

In [3]:
best_towns

[{'Towns': 'Mont Saint-Michel',
  'Latitude': 48.6359541,
  'Longitude': -1.511459954959514},
 {'Towns': 'Saint-Malo', 'Latitude': 48.649518, 'Longitude': -2.0260409},
 {'Towns': 'Bayeux', 'Latitude': 49.2764624, 'Longitude': -0.7024738},
 {'Towns': 'Le Havre', 'Latitude': 49.4938975, 'Longitude': 0.1079732},
 {'Towns': 'Rouen', 'Latitude': 49.4404591, 'Longitude': 1.0939658},
 {'Towns': 'Paris', 'Latitude': 48.8588897, 'Longitude': 2.3200410217200766},
 {'Towns': 'Amiens', 'Latitude': 49.8941708, 'Longitude': 2.2956951},
 {'Towns': 'Lille', 'Latitude': 50.6365654, 'Longitude': 3.0635282},
 {'Towns': 'Strasbourg', 'Latitude': 48.584614, 'Longitude': 7.7507127},
 {'Towns': 'Château du Haut-Kœnigsbourg',
  'Latitude': 48.249410749999996,
  'Longitude': 7.344320233724503},
 {'Towns': 'Colmar', 'Latitude': 48.0777517, 'Longitude': 7.3579641},
 {'Towns': 'Eguisheim', 'Latitude': 48.0447968, 'Longitude': 7.3079618},
 {'Towns': 'Besançon', 'Latitude': 47.2380222, 'Longitude': 6.0243622},
 {'Towns': 'Dijon', 'Latitude': 47.3215806, 'Longitude': 5.0414701},
 {'Towns': 'Annecy', 'Latitude': 45.8992348, 'Longitude': 6.1288847},
 {'Towns': 'Grenoble', 'Latitude': 45.1875602, 'Longitude': 5.7357819},
 {'Towns': 'Lyon', 'Latitude': 45.7578137, 'Longitude': 4.8320114},
 {'Towns': 'Gorges du Verdon', 'Latitude': 43.7496562, 'Longitude': 6.3285616},
 {'Towns': 'Bormes-les-Mimosas',
  'Latitude': 43.1506968,
  'Longitude': 6.3419285},
 {'Towns': 'Cassis', 'Latitude': 43.2140359, 'Longitude': 5.5396318},
 {'Towns': 'Marseille', 'Latitude': 43.2961743, 'Longitude': 5.3699525},
 {'Towns': 'Aix-en-Provence', 'Latitude': 43.5298424, 'Longitude': 5.4474738},
 {'Towns': 'Avignon', 'Latitude': 43.9492493, 'Longitude': 4.8059012},
 {'Towns': 'Uzès', 'Latitude': 44.0121279, 'Longitude': 4.4196718},
 {'Towns': 'Nîmes', 'Latitude': 43.8374249, 'Longitude': 4.3600687},
 {'Towns': 'Aigues-Mortes', 'Latitude': 43.5661521, 'Longitude': 4.19154},
 {'Towns': 'Saintes-Maries-de-la-Mer',
  'Latitude': 43.4515922,
  'Longitude': 4.4277202},
 {'Towns': 'Collioure', 'Latitude': 42.52505, 'Longitude': 3.0831554},
 {'Towns': 'Carcassonne', 'Latitude': 43.2130358, 'Longitude': 2.3491069},
 {'Towns': 'Ariège', 'Latitude': 42.9455368, 'Longitude': 1.4065544156065486},
 {'Towns': 'Toulouse', 'Latitude': 43.6044622, 'Longitude': 1.4442469},
 {'Towns': 'Montauban', 'Latitude': 44.0175835, 'Longitude': 1.3549991},
 {'Towns': 'Biarritz',
  'Latitude': 43.471143749999996,
  'Longitude': -1.552726590666314},
 {'Towns': 'Bayonne', 'Latitude': 43.4945144, 'Longitude': -1.4736657},
 {'Towns': 'La Rochelle', 'Latitude': 46.159732, 'Longitude': -1.1515951}]

In [17]:
df = pd.DataFrame(best_towns)

                          Towns   Latitude  Longitude
0             Mont Saint-Michel  48.635954  -1.511460
1                    Saint-Malo  48.649518  -2.026041
2                        Bayeux  49.276462  -0.702474
3                      Le Havre  49.493898   0.107973
4                         Rouen  49.440459   1.093966
5                         Paris  48.858890   2.320041
6                        Amiens  49.894171   2.295695
7                         Lille  50.636565   3.063528
8                    Strasbourg  48.584614   7.750713
9   Château du Haut-Kœnigsbourg  48.249411   7.344320
10                       Colmar  48.077752   7.357964
11                    Eguisheim  48.044797   7.307962
12                     Besançon  47.238022   6.024362
13                        Dijon  47.321581   5.041470
14                       Annecy  45.899235   6.128885
15                     Grenoble  45.187560   5.735782
16                         Lyon  45.757814   4.832011
17             Gorges du Verdon  43.749656   6.328562
18           Bormes-les-Mimosas  43.150697   6.341928
19                       Cassis  43.214036   5.539632
20                    Marseille  43.296174   5.369953
21              Aix-en-Provence  43.529842   5.447474
22                      Avignon  43.949249   4.805901
23                         Uzès  44.012128   4.419672
24                        Nîmes  43.837425   4.360069
25                Aigues-Mortes  43.566152   4.191540
26     Saintes-Maries-de-la-Mer  43.451592   4.427720
27                    Collioure  42.525050   3.083155
28                  Carcassonne  43.213036   2.349107
29                       Ariège  42.945537   1.406554
30                     Toulouse  43.604462   1.444247
31                    Montauban  44.017584   1.354999
32                     Biarritz  43.471144  -1.552727
33                      Bayonne  43.494514  -1.473666
34                  La Rochelle  46.159732  -1.151595

In [ ]:
#Créer un index pour le dataframe
df['Id'] = [x for x in range(0, 35)]
df

                          Towns   Latitude  Longitude  Id
0             Mont Saint-Michel  48.635954  -1.511460   0
1                    Saint-Malo  48.649518  -2.026041   1
2                        Bayeux  49.276462  -0.702474   2
3                      Le Havre  49.493898   0.107973   3
4                         Rouen  49.440459   1.093966   4
5                         Paris  48.858890   2.320041   5
6                        Amiens  49.894171   2.295695   6
7                         Lille  50.636565   3.063528   7
8                    Strasbourg  48.584614   7.750713   8
9   Château du Haut-Kœnigsbourg  48.249411   7.344320   9
10                       Colmar  48.077752   7.357964  10
11                    Eguisheim  48.044797   7.307962  11
12                     Besançon  47.238022   6.024362  12
13                        Dijon  47.321581   5.041470  13
14                       Annecy  45.899235   6.128885  14
15                     Grenoble  45.187560   5.735782  15
16                         Lyon  45.757814   4.832011  16
17             Gorges du Verdon  43.749656   6.328562  17
18           Bormes-les-Mimosas  43.150697   6.341928  18
19                       Cassis  43.214036   5.539632  19
20                    Marseille  43.296174   5.369953  20
21              Aix-en-Provence  43.529842   5.447474  21
22                      Avignon  43.949249   4.805901  22
23                         Uzès  44.012128   4.419672  23
24                        Nîmes  43.837425   4.360069  24
25                Aigues-Mortes  43.566152   4.191540  25
26     Saintes-Maries-de-la-Mer  43.451592   4.427720  26
27                    Collioure  42.525050   3.083155  27
28                  Carcassonne  43.213036   2.349107  28
29                       Ariège  42.945537   1.406554  29
30                     Toulouse  43.604462   1.444247  30
31                    Montauban  44.017584   1.354999  31
32                     Biarritz  43.471144  -1.552727  32
33                      Bayonne  43.494514  -1.473666  33
34                  La Rochelle  46.159732  -1.151595  34

In [35]:
# Sauvegarde en CSV pour éviter de refaire les requêtes à l'API à chaque fois 
df.to_csv('kayak_town_geo.csv')

In [34]:
df_gps = df.copy()

In [36]:
# Préparation des listes de coordonnées sans les noms des villes pour l'API Open Weather

towns = df_gps[['Longitude', 'Latitude']]
long_list = towns['Longitude'].values.tolist()
lat_list = towns['Latitude'].values.tolist()
print(long_list[0:35])
print(lat_list[0:35])

[-1.511459954959514, -2.0260409, -0.7024738, 0.1079732, 1.0939658, 2.3200410217200766, 2.2956951, 3.0635282, 7.7507127, 7.344320233724503, 7.3579641, 7.3079618, 6.0243622, 5.0414701, 6.1288847, 5.7357819, 4.8320114, 6.3285616, 6.3419285, 5.5396318, 5.3699525, 5.4474738, 4.8059012, 4.4196718, 4.3600687, 4.19154, 4.4277202, 3.0831554, 2.3491069, 1.4065544156065486, 1.4442469, 1.3549991, -1.552726590666314, -1.4736657, -1.1515951]
[48.6359541, 48.649518, 49.2764624, 49.4938975, 49.4404591, 48.8588897, 49.8941708, 50.6365654, 48.584614, 48.249410749999996, 48.0777517, 48.0447968, 47.2380222, 47.3215806, 45.8992348, 45.1875602, 45.7578137, 43.7496562, 43.1506968, 43.2140359, 43.2961743, 43.5298424, 43.9492493, 44.0121279, 43.8374249, 43.5661521, 43.4515922, 42.52505, 43.2130358, 42.9455368, 43.6044622, 44.0175835, 43.471143749999996, 43.4945144, 46.159732]

In [37]:
towns.shape

(35, 2)

In [ ]:
# API Open Weather 



town_and_weather = []

for i in range(35):

    url = f"https://api.openweathermap.org/data/2.5/forecast?lat={lat_list[i]}&lon={long_list[i]}&cnt=7&appid={appid}"
    response = requests.get(url = url)
    response.json()
    icon= ''
    temps = response.json()
    weather7 = temps["list"][0]['weather'][0]['main']
    icon7 = temps["list"][0]['weather'][0]['icon']
    temperature = temps["list"][0]['main']['temp'] 
    temp7 = round(temperature - 273.15)

    town_and_weather.append({'Id' : i,
                            'temperature_forcast' : temp7,
                            'weather_forcast' : weather7})

print(town_and_weather)

[{'Id': 0, 'temperature_forcast': 8, 'weather_forcast': 'Clouds'}, {'Id': 1, 'temperature_forcast': 12, 'weather_forcast': 'Clouds'}, {'Id': 2, 'temperature_forcast': 9, 'weather_forcast': 'Clouds'}, {'Id': 3, 'temperature_forcast': 10, 'weather_forcast': 'Clouds'}, {'Id': 4, 'temperature_forcast': 5, 'weather_forcast': 'Clouds'}, {'Id': 5, 'temperature_forcast': 2, 'weather_forcast': 'Clouds'}, {'Id': 6, 'temperature_forcast': 3, 'weather_forcast': 'Clear'}, {'Id': 7, 'temperature_forcast': 2, 'weather_forcast': 'Clouds'}, {'Id': 8, 'temperature_forcast': 1, 'weather_forcast': 'Clear'}, {'Id': 9, 'temperature_forcast': 0, 'weather_forcast': 'Clear'}, {'Id': 10, 'temperature_forcast': 3, 'weather_forcast': 'Clear'}, {'Id': 11, 'temperature_forcast': 3, 'weather_forcast': 'Clear'}, {'Id': 12, 'temperature_forcast': 0, 'weather_forcast': 'Clear'}, {'Id': 13, 'temperature_forcast': 1, 'weather_forcast': 'Clouds'}, {'Id': 14, 'temperature_forcast': 5, 'weather_forcast': 'Clear'}, {'Id': 15, 'temperature_forcast': 4, 'weather_forcast': 'Clear'}, {'Id': 16, 'temperature_forcast': 2, 'weather_forcast': 'Clouds'}, {'Id': 17, 'temperature_forcast': 7, 'weather_forcast': 'Clear'}, {'Id': 18, 'temperature_forcast': 12, 'weather_forcast': 'Clear'}, {'Id': 19, 'temperature_forcast': 12, 'weather_forcast': 'Clear'}, {'Id': 20, 'temperature_forcast': 13, 'weather_forcast': 'Clear'}, {'Id': 21, 'temperature_forcast': 11, 'weather_forcast': 'Clear'}, {'Id': 22, 'temperature_forcast': 9, 'weather_forcast': 'Clear'}, {'Id': 23, 'temperature_forcast': 7, 'weather_forcast': 'Clear'}, {'Id': 24, 'temperature_forcast': 10, 'weather_forcast': 'Clear'}, {'Id': 25, 'temperature_forcast': 10, 'weather_forcast': 'Clear'}, {'Id': 26, 'temperature_forcast': 10, 'weather_forcast': 'Clear'}, {'Id': 27, 'temperature_forcast': 11, 'weather_forcast': 'Clear'}, {'Id': 28, 'temperature_forcast': 13, 'weather_forcast': 'Clear'}, {'Id': 29, 'temperature_forcast': 2, 'weather_forcast': 'Clear'}, {'Id': 30, 'temperature_forcast': 13, 'weather_forcast': 'Clear'}, {'Id': 31, 'temperature_forcast': 7, 'weather_forcast': 'Clear'}, {'Id': 32, 'temperature_forcast': 12, 'weather_forcast': 'Clear'}, {'Id': 33, 'temperature_forcast': 12, 'weather_forcast': 'Clear'}, {'Id': 34, 'temperature_forcast': 11, 'weather_forcast': 'Clear'}]

In [ ]:
print(town_and_weather)

{'Id': 34, 'temperature_forcast': 12, 'weather_forcast': 'Clear'}

In [72]:
towns_and_wforcast = pd.DataFrame.from_dict(town_and_weather)
towns_and_wforcast.to_csv('kayak_forecast.csv')

In [41]:
df1 = pd.read_csv('kayak_town_geo.csv')
df2 = pd.read_csv('kayak_forecast.csv')
df3 = pd.merge(df1, df2, on = 'Id')

df3 = df3.drop(['Unnamed: 0_x', 'Unnamed: 0_y'], axis = 1)
id_move = df3.pop('Id')
df3.insert(0, 'Id', id_move)

# 10 Les meileures villes à visiter en termes de douceur du climent (les données sont récoltées le 4 février, les prévisions ont été faites pour le 11 février 2025)

best_towns = df3.sort_values(by='temperature_forcast', ascending=False)

best_towns[0:10]
df3.to_csv('Town_Geo_Forcast.csv')

In [42]:
df3

,Id,Towns,Latitude,Longitude,temperature_forcast,weather_forcast
0,0,Mont Saint-Michel,48.635954,-1.511460,8,Clouds
1,1,Saint-Malo,48.649518,-2.026041,12,Clouds
2,2,Bayeux,49.276462,-0.702474,9,Clouds
3,3,Le Havre,49.493898,0.107973,10,Clouds
4,4,Rouen,49.440459,1.093966,5,Clouds
5,5,Paris,48.858890,2.320041,2,Clouds
6,6,Amiens,49.894171,2.295695,3,Clear
7,7,Lille,50.636565,3.063528,2,Clouds
8,8,Strasbourg,48.584614,7.750713,1,Clear
9,9,Château du Haut-Kœnigsbourg,48.249411,7.344320,0,Clear
10,10,Colmar,48.077752,7.357964,3,Clear
11,11,Eguisheim,48.044797,7.307962,3,Clear
12,12,Besançon,47.238022,6.024362,0,Clear
13,13,Dijon,47.321581,5.041470,1,Clouds
14,14,Annecy,45.899235,6.128885,5,Clear
15,15,Grenoble,45.187560,5.735782,4,Clear
16,16,Lyon,45.757814,4.832011,2,Clouds
17,17,Gorges du Verdon,43.749656,6.328562,7,Clear
18,18,Bormes-les-Mimosas,43.150697,6.341928,12,Clear
19,19,Cassis,43.214036,5.539632,12,Clear
20,20,Marseille,43.296174,5.369953,13,Clear
21,21,Aix-en-Provence,43.529842,5.447474,11,Clear
22,22,Avignon,43.949249,4.805901,9,Clear
23,23,Uzès,44.012128,4.419672,7,Clear
24,24,Nîmes,43.837425,4.360069,10,Clear
25,25,Aigues-Mortes,43.566152,4.191540,10,Clear
26,26,Saintes-Maries-de-la-Mer,43.451592,4.427720,10,Clear
27,27,Collioure,42.525050,3.083155,11,Clear
28,28,Carcassonne,43.213036,2.349107,13,Clear
29,29,Ariège,42.945537,1.406554,2,Clear
30,30,Toulouse,43.604462,1.444247,13,Clear
31,31,Montauban,44.017584,1.354999,7,Clear
32,32,Biarritz,43.471144,-1.552727,12,Clear
33,33,Bayonne,43.494514,-1.473666,12,Clear
34,34,La Rochelle,46.159732,-1.151595,11,Clear

In [43]:
best_towns[0:10]

,Id,Towns,Latitude,Longitude,temperature_forcast,weather_forcast
20,20,Marseille,43.296174,5.369953,13,Clear
30,30,Toulouse,43.604462,1.444247,13,Clear
28,28,Carcassonne,43.213036,2.349107,13,Clear
18,18,Bormes-les-Mimosas,43.150697,6.341928,12,Clear
19,19,Cassis,43.214036,5.539632,12,Clear
33,33,Bayonne,43.494514,-1.473666,12,Clear
32,32,Biarritz,43.471144,-1.552727,12,Clear
1,1,Saint-Malo,48.649518,-2.026041,12,Clouds
21,21,Aix-en-Provence,43.529842,5.447474,11,Clear
34,34,La Rochelle,46.159732,-1.151595,11,Clear

In [69]:
# Les 10 villes sélectionnés pour la douceur du climat
ten_towns = best_towns[['Id', 'Towns']][0:10]
ten_towns['Towns'] = [x.replace(' ', '+') for x in ten_towns['Towns']]
ten_towns

    Id               Towns
20  20           Marseille
30  30            Toulouse
28  28         Carcassonne
18  18  Bormes-les-Mimosas
19  19              Cassis
33  33             Bayonne
32  32            Biarritz
1    1          Saint-Malo
21  21     Aix-en-Provence
34  34         La+Rochelle

In [107]:
list_10 = ten_towns[['Id', 'Towns']].to_dict()['Towns']

In [108]:
list_10

{20: 'Marseille',
 30: 'Toulouse',
 28: 'Carcassonne',
 18: 'Bormes-les-Mimosas',
 19: 'Cassis',
 33: 'Bayonne',
 32: 'Biarritz',
 1: 'Saint-Malo',
 21: 'Aix-en-Provence',
 34: 'La+Rochelle'}

In [110]:
for i, j in list_10.items():
    print(i, j)

20 Marseille
30 Toulouse
28 Carcassonne
18 Bormes-les-Mimosas
19 Cassis
33 Bayonne
32 Biarritz
1 Saint-Malo
21 Aix-en-Provence
34 La+Rochelle

In [116]:
! python kayak_spider_22fev.py

2025-02-22 22:12:52 [scrapy.utils.log] INFO: Scrapy 2.11.1 started (bot: scrapybot)
2025-02-22 22:12:52 [scrapy.utils.log] INFO: Versions: lxml 5.2.1.0, libxml2 2.13.1, cssselect 1.2.0, parsel 1.8.1, w3lib 2.1.2, Twisted 23.10.0, Python 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 21:00:12) [Clang 16.0.6 ], pyOpenSSL 24.2.1 (OpenSSL 3.4.1 11 Feb 2025), cryptography 43.0.0, Platform macOS-11.7.10-x86_64-i386-64bit
2025-02-22 22:12:52 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-22 22:12:52 [py.warnings] WARNING: /opt/anaconda3/lib/python3.12/site-packages/scrapy/utils/request.py:254: ScrapyDeprecationWarning: '2.6' is a deprecated value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting.

It is also the default value. In other words, it is normal to get this warning if you have not defined a value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting. This is so for backward compatibility reasons, but it will change in a future version of Scrapy.

See the documentation of the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting for information on how to handle this deprecation.
  return cls(crawler)

2025-02-22 22:12:52 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.selectreactor.SelectReactor
2025-02-22 22:12:52 [scrapy.extensions.telnet] INFO: Telnet Password: 4e191b2554b76aaf
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-22 22:12:52 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-22 22:12:52 [scrapy.core.engine] INFO: Spider opened
2025-02-22 22:12:52 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-22 22:12:52 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2025-02-22 22:12:52 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-22 22:12:52 [py.warnings] WARNING: /opt/anaconda3/lib/python3.12/site-packages/scrapy/utils/request.py:254: ScrapyDeprecationWarning: '2.6' is a deprecated value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting.

It is also the default value. In other words, it is normal to get this warning if you have not defined a value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting. This is so for backward compatibility reasons, but it will change in a future version of Scrapy.

See the documentation of the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting for information on how to handle this deprecation.
  return cls(crawler)

2025-02-22 22:12:52 [scrapy.extensions.telnet] INFO: Telnet Password: cef7457786d4a95a
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-22 22:12:52 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-22 22:12:52 [scrapy.core.engine] INFO: Spider opened
2025-02-22 22:12:52 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-22 22:12:52 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6024
2025-02-22 22:12:52 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-22 22:12:52 [scrapy.extensions.telnet] INFO: Telnet Password: e57a94b756775d81
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-22 22:12:52 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-22 22:12:52 [scrapy.core.engine] INFO: Spider opened
2025-02-22 22:12:52 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-22 22:12:52 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6025
2025-02-22 22:12:52 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-22 22:12:52 [scrapy.extensions.telnet] INFO: Telnet Password: 9d53ca3bf14526f0
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-22 22:12:52 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-22 22:12:52 [scrapy.core.engine] INFO: Spider opened
2025-02-22 22:12:52 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-22 22:12:52 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6026
2025-02-22 22:12:52 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-22 22:12:52 [scrapy.extensions.telnet] INFO: Telnet Password: 91fc4eea9e254bc8
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-22 22:12:52 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-22 22:12:52 [scrapy.core.engine] INFO: Spider opened
2025-02-22 22:12:52 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-22 22:12:52 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6027
2025-02-22 22:12:52 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-22 22:12:52 [scrapy.extensions.telnet] INFO: Telnet Password: a33be55d8a2fc96d
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-22 22:12:52 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-22 22:12:52 [scrapy.core.engine] INFO: Spider opened
2025-02-22 22:12:52 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-22 22:12:52 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6028
2025-02-22 22:12:52 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-22 22:12:52 [scrapy.extensions.telnet] INFO: Telnet Password: ac00eb39b03ad5a1
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-22 22:12:52 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-22 22:12:52 [scrapy.core.engine] INFO: Spider opened
2025-02-22 22:12:52 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-22 22:12:52 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6029
2025-02-22 22:12:52 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-22 22:12:52 [scrapy.extensions.telnet] INFO: Telnet Password: f90df211aec4a2ef
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-22 22:12:52 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-22 22:12:52 [scrapy.core.engine] INFO: Spider opened
2025-02-22 22:12:52 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-22 22:12:52 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6030
2025-02-22 22:12:52 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-22 22:12:52 [scrapy.extensions.telnet] INFO: Telnet Password: 9c4145a890fb973b
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-22 22:12:52 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-22 22:12:52 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',

In [ ]:
url_hotel_ten = pd.read_json('ten_hotels_town_id.json', lines=True)
url_hotel_ten['hotel_url_parse'] = [x]

0      https://www.booking.com/hotel/fr/paradise-eart...
1      https://www.booking.com/hotel/fr/grand-t1-vieu...
2      https://www.booking.com/hotel/fr/les-jardins-d...
3      https://www.booking.com/hotel/fr/easyhotel-mar...
4      https://www.booking.com/hotel/fr/montgrand.fr....
                             ...
245    https://www.booking.com/hotel/fr/caporizon-pre...
246    https://www.booking.com/hotel/fr/le-petit-cail...
247    https://www.booking.com/hotel/fr/2-pieces-avec...
248    https://www.booking.com/hotel/fr/kyriad-la-roc...
249    https://www.booking.com/hotel/fr/beautiful-fla...
Name: hotel_url, Length: 250, dtype: object

In [137]:
from urllib.parse import urlparse, parse_qs
url_hotel_ten['hotel_url_parse'] = [urlparse(x).path.split('/hotel/fr/') for x in url_hotel_ten['hotel_url']]
url_hotel_ten['hotel_url_parse_final'] = [x[1] for x in url_hotel_ten['hotel_url_parse']]

In [138]:
url_hotel_ten

,Id,town,hotel_name,hotel_rating,hotel_url,hotel_url_parse,hotel_url_parse_final
0,20,Marseille,PARADISE Earth & Sea,"8,7",https://www.booking.com/hotel/fr/paradise-eart...,"[, paradise-eart-amp-sea.fr.html]",paradise-eart-amp-sea.fr.html
1,20,Marseille,The Babel Community Hôtel - Vieux Port,"8,0",https://www.booking.com/hotel/fr/grand-t1-vieu...,"[, grand-t1-vieux-port-salle-de-sport-amp-roof...",grand-t1-vieux-port-salle-de-sport-amp-rooftop...
2,20,Marseille,Les Appartements du Vieux Port,"9,5",https://www.booking.com/hotel/fr/les-jardins-d...,"[, les-jardins-du-ga-c-na-c-ral.fr.html]",les-jardins-du-ga-c-na-c-ral.fr.html
3,20,Marseille,easyHotel Marseille Euromed,"8,5",https://www.booking.com/hotel/fr/easyhotel-mar...,"[, easyhotel-marseille.fr.html]",easyhotel-marseille.fr.html
4,20,Marseille,Hôtel Maison Montgrand - Vieux Port,"8,2",https://www.booking.com/hotel/fr/montgrand.fr....,"[, montgrand.fr.html]",montgrand.fr.html
...,...,...,...,...,...,...,...
245,34,La+Rochelle,Caporizon-Le Perot-T2 au coeur du vieux port 1...,"8,0",https://www.booking.com/hotel/fr/caporizon-pre...,"[, caporizon-presente-coeur-vieux-port-t2-a-10...",caporizon-presente-coeur-vieux-port-t2-a-100m-...
246,34,La+Rochelle,Le Petit Caillebotis,"9,0",https://www.booking.com/hotel/fr/le-petit-cail...,"[, le-petit-caillebotis.fr.html]",le-petit-caillebotis.fr.html
247,34,La+Rochelle,2 pièces avec parking en Coeur de Ville - Appa...,"9,2",https://www.booking.com/hotel/fr/2-pieces-avec...,"[, 2-pieces-avec-parking-en-coeur-de-ville-app...",2-pieces-avec-parking-en-coeur-de-ville-appart...
248,34,La+Rochelle,Hôtel Kyriad La Rochelle Centre Ville,"8,4",https://www.booking.com/hotel/fr/kyriad-la-roc...,"[, kyriad-la-rochelle-centre.fr.html]",kyriad-la-rochelle-centre.fr.html
249,34,La+Rochelle,Appartement du Port - Welkeys,"8,3",https://www.booking.com/hotel/fr/beautiful-fla...,"[, beautiful-flat-2-minutes-from-the-city-cent...",beautiful-flat-2-minutes-from-the-city-centre-...

In [139]:
list_10_h_url = url_hotel_ten[['Id', 'hotel_url_parse_final']].to_dict()['hotel_url_parse_final']

In [141]:
list_10_h_url

{0: 'paradise-eart-amp-sea.fr.html',
 1: 'grand-t1-vieux-port-salle-de-sport-amp-rooftop.fr.html',
 2: 'les-jardins-du-ga-c-na-c-ral.fr.html',
 3: 'easyhotel-marseille.fr.html',
 4: 'montgrand.fr.html',
 5: 'hermes.fr.html',
 6: 'nhow-marseille.fr.html',
 7: 'citea-marseille-prado-perier.fr.html',
 8: 'staycity-aparthotels-centre-vieux-port.fr.html',
 9: 'residence-kley-marseille-republique.fr.html',
 10: 'alize.fr.html',
 11: 'le-mistral-marseille.fr.html',
 12: 'l-39-orangeraie-et-la-palmeraie-d-39-endoume.fr.html',
 13: 'maison-vue-mer-marseille.fr.html',
 14: 'hotelkyrivieuxmarseille.fr.html',
 15: 'mouchki-marseille1.fr.html',
 16: 'marseille-castellane.fr.html',
 17: 'appartement-vieux-port-de-marseille-davso-marseille.fr.html',
 18: 'goldentulipvillamassalia.fr.html',
 19: 'le-cocon-de-louise.fr.html',
 20: 'coup-de-coeur-vieux-port-republique.fr.html',
 21: 'bord-de-mer-charmant-studio-entierement-equipe.fr.html',
 22: 'superbe-t2-4-etoiles-climatise-faviere-refait-a-neuf.fr.html',
 23: 'select-sohome-t2-proche-de-la-station-balneaire-de-la-faviere-azur-17.fr.html',
 24: 'bormes-les-mimosas-appart-25m2-avec-balcon-4p.fr.html',
 25: 'bormes-le-loft.fr.html',
 26: 'studio-alize.fr.html',
 27: 'the-little-house-bormes-les-mimosas.fr.html',
 28: 'select-sohome-t2-entierement-renove-a-quelques-pas-de-la-plage-pos07.fr.html',
 29: 'select-joli-appartement-avec-jardin-privatif-et-parking-capnat-f08.fr.html',
 30: 'appartement-pieds-dans-l-eau-vue-mer-bormes-les-mimosas.fr.html',
 31: 'les-terrasses-de-lo.fr.html',
 32: 'boulevard-du-soleil.fr.html',
 33: 'the-social-hub-toulouse.fr.html',
 34: 'odalys-city-centre-compans-caffarelli.fr.html',
 35: 'crowne-plaza-toulouse-toulouse.fr.html',
 36: 'montempo-apparthotel-toulouse-cite-internationale.fr.html',
 37: 'le-peri-douillet-appartement-en-hypercentre.fr.html',
 38: 'residence-concorde.fr.html',
 39: 'des-beaux-arts.fr.html',
 40: 'ours-blanc-wilson.fr.html',
 41: 'victor-hugo.fr.html',
 42: 'eklo-toulouse.fr.html',
 43: 'la-romance-apartment-the-heart-of-toulouse.fr.html',
 44: 'le-nid-de-la-pomme.fr.html',
 45: 'bara-superbe-t2-avec-balcon-a-patte-d-oie.fr.html',
 46: 'le-toulousain-202-appartement-cosy-en-hypercentre-quartier-jeanne-d-arc.fr.html',
 47: 'la-recampado-bormes-les-mimosas.fr.html',
 48: 'select-sohome-superbe-appartement-pour-4-personnes-a-deux-pas-de-la-plage-et-des.fr.html',
 49: 'studio-3-pers-coeur-de-village-bormes-les-mimosas.fr.html',
 50: 'studio-cosy-climatise-place-de-parking-a-la-faviere.fr.html',
 51: 'lovely-place-for-2.fr.html',
 52: 'studio-ideal-sejour-en-amoureux-rez-de-jardin-proche-plage.fr.html',
 53: 'select-t2-avec-vue-piscine-et-parking-prive-capnat-b08.fr.html',
 54: 'le-studio-tahiti-4-pers-200m-de-la-plage.fr.html',
 55: 'voir-les-photos-presentationemplacementcommentairesl-39-hote-2-pieces-35m2-borme.fr.html',
 56: 'la-lavandiere-bormes-les-mimosas.fr.html',
 57: 'les-embruns-bormes-les-mimosas.fr.html',
 58: 'face-mer-entre-plage-et-marina.fr.html',
 59: 'student-factory-toulouse-zenith.fr.html',
 60: 'le-toulousain-102-appartement-cosy-en-hypercentre-quartier-jeanne-d-arc.fr.html',
 61: 't2-cosy-toulouse-hypercentre-metro-jaures-parking-toulouse.fr.html',
 62: 'groovy-by-yume.fr.html',
 63: 'le-toulousain-001-appartement-calme-en-rez-de-chaussee-avec-terrasse-hypercentre.fr.html',
 64: 'nid-calme-en-hypercentre-proche-metro-amp-gare.fr.html',
 65: 'les-appartements-de-babel-republique-marseille.fr.html',
 66: 'mama-shelter-marseille.fr.html',
 67: 'adira-marseille-panier.fr.html',
 68: 'amarrage-marseille.fr.html',
 69: 't2-de-charme-a-rochebonne.fr.html',
 70: 'de-l-europe-appartements.fr.html',
 71: 'calm-and-cosy-saint-malo.fr.html',
 72: 'appartement-chaleureux-saint-malo-centre.fr.html',
 73: 'centre-saint-malo.fr.html',
 74: 'le-servannais.fr.html',
 75: 'les-embruns-saint-malo.fr.html',
 76: 'cote-basque.fr.html',
 77: 'parc-709-bayonne.fr.html',
 78: 'city-break-miradour.fr.html',
 79: 'l-39-ame-nomade-bayonne-centre.fr.html',
 80: 'okko-hotels-bayonne-centre.fr.html',
 81: 'des-basses-pyrenees.fr.html',
 82: 'iri-etxea-appt-2-chambre-a-bayonne.fr.html',
 83: 'villa-koegui-bayonne.fr.html',
 84: 'appart-39-bellevue.fr.html',
 85: 'comfort-bayonne-biarritz.fr.html',
 86: 'le-bayonne-ha-tel.fr.html',
 87: 'chez-fleur-bayonne.fr.html',
 88: 'un-appart-en-ville-bayonne1.fr.html',
 89: 'ibis-bayonne.fr.html',
 90: 'kyriad-prestige-saint-malo-xml.fr.html',
 91: 'elizabeth.fr.html',
 92: 'ar-iniz.fr.html',
 93: 'charmant-appartement-saint-malo-saint-servan.fr.html',
 94: 'de-france-et-chateaubriand.fr.html',
 95: 'anne-de-bretagne.fr.html',
 96: 'gite-de-la-tra-c-herais.fr.html',
 97: 'malouiniere-guillaume-onffroy.fr.html',
 98: 'san-pedro.fr.html',
 99: 'plage-de-solidor-quartier-saint-servan.fr.html',
 100: 'bleumarinesaintmalo.fr.html',
 101: 'appartement-la-grassinais.fr.html',
 102: 'heol.fr.html',
 103: 'boulevard-hebert.fr.html',
 104: 'le-port-neuf.fr.html',
 105: 'bayonne-en-plein-coeur-centre-historique-2-chambres.fr.html',
 106: 'appartement-t2-bayonne-st-esprit-avec-parking.fr.html',
 107: 'loustau.fr.html',
 108: 'appartement-t2-cosy-et-calme-bayonne.fr.html',
 109: 'le-petit-nid-douillet-chez-jeje.fr.html',
 110: 'appartement-residence-neuve.fr.html',
 111: 'select-sohome-appartement-spacieux-pour-4-personnes-avec-garage-prive-et-piscine.fr.html',
 112: 'le-toulousain-appartement-calme-en-hypercentre-quartier-jeanne-d-arc.fr.html',
 113: 'loft-palais-de-justice.fr.html',
 114: 'logement-entier-hyper-centre.fr.html',
 115: 'tout-beau-tout-neuf.fr.html',
 116: 'pargaminieres-elegant-duplex-proche-du-capitole.fr.html',
 117: 'le-grand-large-biarritz.fr.html',
 118: 'la-maison-du-lierre.fr.html',
 119: 'hotelargieder.fr.html',
 120: 'studio-biarritz-2-min-halles-3-min-plages-plein-centre.fr.html',
 121: 'la-casa-cosy-biarritz.fr.html',
 122: 'studio-grand-plage-de-biarritz.fr.html',
 123: 'vue-exceptionnelle-sur-l-ocean-studio-2-4-pers.fr.html',
 124: 'biarritz-appartement-4-personnes-a-proximite-immediate-des-plages-et-des-commerc.fr.html',
 125: 'de-la-plage-biarritz.fr.html',
 126: 'cote-des-basques.fr.html',
 127: 'studio-du-phare.fr.html',
 128: 'l-39-ocean-a-perte-de-vue-la-grande-plage-a-vos-pieds.fr.html',
 129: 'palym-biarritz.fr.html',
 130: 'charmant-studio-hyper-centre-biarritz.fr.html',
 131: 'surf-hostel-biarritz.fr.html',
 132: 'hotelanjou.fr.html',
 133: 'biarritz-victoria-surf.fr.html',
 134: 'studio-les-pieds-dans-le-sable-vue-mer-amp-balcon.fr.html',
 135: 'residence-pierre-vacances-haguna.fr.html',
 136: 'amazing-cosy-studio-with-ocean-view-amp-pool.fr.html',
 137: 'home-cassis.fr.html',
 138: 'home-cassis-maison-mediterrannee.fr.html',
 139: 'villa-w.fr.html',
 140: 'mistral-gagnant-cassis.fr.html',
 141: '80m2-a-200m-de-la-calanque-de-port-miou-2-chambres-et-parking.fr.html',
 142: 'le-nais-proche-centre-parking-wifi.fr.html',
 143: 'entre-terre-et-mer-a-cassis.fr.html',
 144: 'appartement-saint-malo-saint-malo2.fr.html',
 145: 'les-bois-flottes-saint-malo.fr.html',
 146: 'ajoncsdor.fr.html',
 147: 'appartement-neuf-et-bien-situe-avec-un-classement-saint-malo.fr.html',
 148: 'grand-appartement-cosy.fr.html',
 149: 'temporesidence-cathedrale.fr.html',
 150: 'libertitu.fr.html',
 151: 'villa-la-renaissance-bayonne.fr.html',
 152: 'cassis-4-pers-vue-mer-wifi-piscine-parking-tennis.fr.html',
 153: 'le-biou.fr.html',
 154: 'au-son-des-cigales-cassis.fr.html',
 155: 'villa-bobnell.fr.html',
 156: 'home-cassis-maison-julou.fr.html',
 157: 'le-pagnol-hyper-centre-clim.fr.html',
 158: 'magnifique-t2-residence-la-rade-vue-mer-parking.fr.html',
 159: 'le-sept-charmant-studio-aux-portes-des-calanques.fr.html',
 160: 'cassis-calanques-2-pieces-grande-terrasse-vue-mer.fr.html',
 161: 'vue-de-reve.fr.html',
 162: 'azur-cassis.fr.html',
 163: 'guest-house-olivades.fr.html',
 164: 'seaview-cassis.fr.html',
 165: 'reves-de-vie-studio-20m2-avec-terrasse-et-parking-prive.fr.html',
 166: 'splendid-studio-with-parking-lot-right-in-the-center-of-biarritz-welkeys.fr.html',
 167: 'le-cafe-de-paris-4.fr.html',
 168: 'studio-et-piscine-sur-la-grande-plage.fr.html',
 169: 'vtf-le-domaine-de-francon.fr.html',
 170: 'kemaris-biarritz.fr.html',
 171: 'la-rapia-re.fr.html',
 172: 'rooftop-vue-sur-la-cite-rvc-carcassonne1.fr.html',
 173: 'studio-avec-parking-vue-sur-la-cite-de-carcassonne-carcassonne.fr.html',
 174: 'des-trois-couronnes.fr.html',
 175: 'appartement-petit-saint-gimer.fr.html',
 176: 'chez-micka-carcassonne.fr.html',
 177: 'la-demeure-de-la-cite-by-jean-bacou.fr.html',
 178: 'les-quatre-dauphins.fr.html',
 179: 'les-augustins.fr.html',
 180: 'la-caravelle-aix-en-provence.fr.html',
 181: 'thecamp-amp-lodges.fr.html',
 182: 'paul.fr.html',
 183: 'le-clos-de-la-chartreuse.fr.html',
 184: 'hotel-aquabella.fr.html',
 185: 'good-knight.fr.html',
 186: 'les-florentines-.fr.html',
 187: 'le-rendez-vous-parking-gratuit.fr.html',
 188: 'appartement-carcassone-residence-capucins.fr.html',
 189: 'observatoire-cite-medievale.fr.html',
 190: 'le-pied-a-terre-de-trivalle.fr.html',
 191: 'jules-appartement-au-calme-dans-la-bastide-proche-citee-medieval.fr.html',
 192: 'petit-capucin.fr.html',
 193: 'new-boheme-chic-pied-de-la-cite-2.fr.html',
 194: 'inter-les-oliviers.fr.html',
 195: 'le-patio-de-la-bastide.fr.html',
 196: 'studio-pour-2-avec-terrasse-au-pied-de-la-cite-ma-pierre-a-l-edifice.fr.html',
 197: 'best-western-le-galice.fr.html',
 198: 'grand-negre-coste.fr.html',
 199: 'rotonde.fr.html',
 200: 'grand-mercure-roi-rene.fr.html',
 201: 'cezanne-aix-en-provence.fr.html',
 202: 'hotel-escaletto.fr.html',
 203: 'le-nelio.fr.html',
 204: 'domaine-de-carraire-chez-alphonse.fr.html',
 205: 'golden-tulip-aix-en-provence.fr.html',
 206: 'royal-mirabeau.fr.html',
 207: 'pierre-vacances-city-centre.fr.html',
 208: 'cardinal.fr.html',
 209: 'charmant-appartement-hypercentre-aix-en-provence.fr.html',
 210: 'studio-arene-by-k6-you.fr.html',
 211: 'zina.fr.html',
 212: 'cote-gibaou.fr.html',
 213: 'nesme-par-dodo-a-cassis.fr.html',
 214: 'chambre-independante-a-carcassonne.fr.html',
 215: 'appartement-le-joyau-de-courtejaire.fr.html',
 216: 'la-couleur-des-champs.fr.html',
 217: 'appartement-lumineux-en-centre-ville-carcassonne.fr.html',
 218: 'soleil-vacances-les-chevaliers.fr.html',
 219: 'canal-du-midi-carcassonne.fr.html',
 220: 'the-originals-residence-aix-schuman.fr.html',
 221: 'les-floridianes.fr.html',
 222: 'l-39-escapade-aixoise-nuit-romantique.fr.html',
 223: 'renaissance-aix-en-provence.fr.html',
 224: 'amandier-appart-de-charme-au-coeur-d-aix.fr.html',
 225: 'lycee-hotelier-la-rochelle.fr.html',
 226: 'apartment-la-rochelle-historic-city-centre.fr.html',
 227: 'appartements-les-rochelais.fr.html',
 228: 'ambre-appart-wifi-terrasse-parking-terrasse-2-couchages.fr.html',
 229: 'les-3-tours.fr.html',
 230: 'la-rochelle-b.fr.html',
 231: 'le-lodge-park-a-la-rochelle.fr.html',
 232: 'appart-archipel.fr.html',
 233: 'central-park-amp-spa.fr.html',
 234: 'la-rochelle-en-famille-4-personnes.fr.html',
 235: 'les-studios-du-chemins-vert.fr.html',
 236: 'chez-alma.fr.html',
 237: 'b-amp-b-la-rochelle-centre.fr.html',
 238: '360-degres-sur-la-rochelle.fr.html',
 239: 'hotellesbrises.fr.html',
 240: 'location-la-rebelle-la-rochelle-b.fr.html',
 241: 'ponant-3-407.fr.html',
 242: 'porte-oceane-6.fr.html',
 243: 'amazing-apartment-in-la-rochelle-with-wifi.fr.html',
 244: 'studio-cosy-la-rochelle-quartier-des-minimes.fr.html',
 245: 'caporizon-presente-coeur-vieux-port-t2-a-100m-plage.fr.html',
 246: 'le-petit-caillebotis.fr.html',
 247: '2-pieces-avec-parking-en-coeur-de-ville-appartement-lumineux-et-calme.fr.html',
 248: 'kyriad-la-rochelle-centre.fr.html',
 249: 'beautiful-flat-2-minutes-from-the-city-centre-of-la-rochelle-welkeys.fr.html'}

In [143]:
import csv
csv_file = 'ten_hotels_town_id.csv'

with open(csv_file, 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['Key', 'Value'])
	
    # Write data
    for key, value in list_10_h_url.items():
        writer.writerow([key, value])

print(f"Dictionary saved to {csv_file}")

Dictionary saved to ten_hotels_town_id.csv

In [ ]:
url_hotel_ten.to_csv('ten_hotels_town_id.csv')

In [21]:
import csv
hotel_url = []
with open('ten_hotels_town_id.csv', mode ='r') as file:
    url = csv.reader(file)
    for u in url:
        if u[1] != 'Value':
            hotel_url.append(u)

In [19]:
hotel_url

[['0', 'paradise-eart-amp-sea.fr.html'],
 ['1', 'grand-t1-vieux-port-salle-de-sport-amp-rooftop.fr.html'],
 ['2', 'les-jardins-du-ga-c-na-c-ral.fr.html'],
 ['3', 'easyhotel-marseille.fr.html'],
 ['4', 'montgrand.fr.html'],
 ['5', 'hermes.fr.html'],
 ['6', 'nhow-marseille.fr.html'],
 ['7', 'citea-marseille-prado-perier.fr.html'],
 ['8', 'staycity-aparthotels-centre-vieux-port.fr.html'],
 ['9', 'residence-kley-marseille-republique.fr.html'],
 ['10', 'alize.fr.html'],
 ['11', 'le-mistral-marseille.fr.html'],
 ['12', 'l-39-orangeraie-et-la-palmeraie-d-39-endoume.fr.html'],
 ['13', 'maison-vue-mer-marseille.fr.html'],
 ['14', 'hotelkyrivieuxmarseille.fr.html'],
 ['15', 'mouchki-marseille1.fr.html'],
 ['16', 'marseille-castellane.fr.html'],
 ['17', 'appartement-vieux-port-de-marseille-davso-marseille.fr.html'],
 ['18', 'goldentulipvillamassalia.fr.html'],
 ['19', 'le-cocon-de-louise.fr.html'],
 ['20', 'coup-de-coeur-vieux-port-republique.fr.html'],
 ['21', 'bord-de-mer-charmant-studio-entierement-equipe.fr.html'],
 ['22', 'superbe-t2-4-etoiles-climatise-faviere-refait-a-neuf.fr.html'],
 ['23',
  'select-sohome-t2-proche-de-la-station-balneaire-de-la-faviere-azur-17.fr.html'],
 ['24', 'bormes-les-mimosas-appart-25m2-avec-balcon-4p.fr.html'],
 ['25', 'bormes-le-loft.fr.html'],
 ['26', 'studio-alize.fr.html'],
 ['27', 'the-little-house-bormes-les-mimosas.fr.html'],
 ['28',
  'select-sohome-t2-entierement-renove-a-quelques-pas-de-la-plage-pos07.fr.html'],
 ['29',
  'select-joli-appartement-avec-jardin-privatif-et-parking-capnat-f08.fr.html'],
 ['30', 'appartement-pieds-dans-l-eau-vue-mer-bormes-les-mimosas.fr.html'],
 ['31', 'les-terrasses-de-lo.fr.html'],
 ['32', 'boulevard-du-soleil.fr.html'],
 ['33', 'the-social-hub-toulouse.fr.html'],
 ['34', 'odalys-city-centre-compans-caffarelli.fr.html'],
 ['35', 'crowne-plaza-toulouse-toulouse.fr.html'],
 ['36', 'montempo-apparthotel-toulouse-cite-internationale.fr.html'],
 ['37', 'le-peri-douillet-appartement-en-hypercentre.fr.html'],
 ['38', 'residence-concorde.fr.html'],
 ['39', 'des-beaux-arts.fr.html'],
 ['40', 'ours-blanc-wilson.fr.html'],
 ['41', 'victor-hugo.fr.html'],
 ['42', 'eklo-toulouse.fr.html'],
 ['43', 'la-romance-apartment-the-heart-of-toulouse.fr.html'],
 ['44', 'le-nid-de-la-pomme.fr.html'],
 ['45', 'bara-superbe-t2-avec-balcon-a-patte-d-oie.fr.html'],
 ['46',
  'le-toulousain-202-appartement-cosy-en-hypercentre-quartier-jeanne-d-arc.fr.html'],
 ['47', 'la-recampado-bormes-les-mimosas.fr.html'],
 ['48',
  'select-sohome-superbe-appartement-pour-4-personnes-a-deux-pas-de-la-plage-et-des.fr.html'],
 ['49', 'studio-3-pers-coeur-de-village-bormes-les-mimosas.fr.html'],
 ['50', 'studio-cosy-climatise-place-de-parking-a-la-faviere.fr.html'],
 ['51', 'lovely-place-for-2.fr.html'],
 ['52', 'studio-ideal-sejour-en-amoureux-rez-de-jardin-proche-plage.fr.html'],
 ['53', 'select-t2-avec-vue-piscine-et-parking-prive-capnat-b08.fr.html'],
 ['54', 'le-studio-tahiti-4-pers-200m-de-la-plage.fr.html'],
 ['55',
  'voir-les-photos-presentationemplacementcommentairesl-39-hote-2-pieces-35m2-borme.fr.html'],
 ['56', 'la-lavandiere-bormes-les-mimosas.fr.html'],
 ['57', 'les-embruns-bormes-les-mimosas.fr.html'],
 ['58', 'face-mer-entre-plage-et-marina.fr.html'],
 ['59', 'student-factory-toulouse-zenith.fr.html'],
 ['60',
  'le-toulousain-102-appartement-cosy-en-hypercentre-quartier-jeanne-d-arc.fr.html'],
 ['61', 't2-cosy-toulouse-hypercentre-metro-jaures-parking-toulouse.fr.html'],
 ['62', 'groovy-by-yume.fr.html'],
 ['63',
  'le-toulousain-001-appartement-calme-en-rez-de-chaussee-avec-terrasse-hypercentre.fr.html'],
 ['64', 'nid-calme-en-hypercentre-proche-metro-amp-gare.fr.html'],
 ['65', 'les-appartements-de-babel-republique-marseille.fr.html'],
 ['66', 'mama-shelter-marseille.fr.html'],
 ['67', 'adira-marseille-panier.fr.html'],
 ['68', 'amarrage-marseille.fr.html'],
 ['69', 't2-de-charme-a-rochebonne.fr.html'],
 ['70', 'de-l-europe-appartements.fr.html'],
 ['71', 'calm-and-cosy-saint-malo.fr.html'],
 ['72', 'appartement-chaleureux-saint-malo-centre.fr.html'],
 ['73', 'centre-saint-malo.fr.html'],
 ['74', 'le-servannais.fr.html'],
 ['75', 'les-embruns-saint-malo.fr.html'],
 ['76', 'cote-basque.fr.html'],
 ['77', 'parc-709-bayonne.fr.html'],
 ['78', 'city-break-miradour.fr.html'],
 ['79', 'l-39-ame-nomade-bayonne-centre.fr.html'],
 ['80', 'okko-hotels-bayonne-centre.fr.html'],
 ['81', 'des-basses-pyrenees.fr.html'],
 ['82', 'iri-etxea-appt-2-chambre-a-bayonne.fr.html'],
 ['83', 'villa-koegui-bayonne.fr.html'],
 ['84', 'appart-39-bellevue.fr.html'],
 ['85', 'comfort-bayonne-biarritz.fr.html'],
 ['86', 'le-bayonne-ha-tel.fr.html'],
 ['87', 'chez-fleur-bayonne.fr.html'],
 ['88', 'un-appart-en-ville-bayonne1.fr.html'],
 ['89', 'ibis-bayonne.fr.html'],
 ['90', 'kyriad-prestige-saint-malo-xml.fr.html'],
 ['91', 'elizabeth.fr.html'],
 ['92', 'ar-iniz.fr.html'],
 ['93', 'charmant-appartement-saint-malo-saint-servan.fr.html'],
 ['94', 'de-france-et-chateaubriand.fr.html'],
 ['95', 'anne-de-bretagne.fr.html'],
 ['96', 'gite-de-la-tra-c-herais.fr.html'],
 ['97', 'malouiniere-guillaume-onffroy.fr.html'],
 ['98', 'san-pedro.fr.html'],
 ['99', 'plage-de-solidor-quartier-saint-servan.fr.html'],
 ['100', 'bleumarinesaintmalo.fr.html'],
 ['101', 'appartement-la-grassinais.fr.html'],
 ['102', 'heol.fr.html'],
 ['103', 'boulevard-hebert.fr.html'],
 ['104', 'le-port-neuf.fr.html'],
 ['105', 'bayonne-en-plein-coeur-centre-historique-2-chambres.fr.html'],
 ['106', 'appartement-t2-bayonne-st-esprit-avec-parking.fr.html'],
 ['107', 'loustau.fr.html'],
 ['108', 'appartement-t2-cosy-et-calme-bayonne.fr.html'],
 ['109', 'le-petit-nid-douillet-chez-jeje.fr.html'],
 ['110', 'appartement-residence-neuve.fr.html'],
 ['111',
  'select-sohome-appartement-spacieux-pour-4-personnes-avec-garage-prive-et-piscine.fr.html'],
 ['112',
  'le-toulousain-appartement-calme-en-hypercentre-quartier-jeanne-d-arc.fr.html'],
 ['113', 'loft-palais-de-justice.fr.html'],
 ['114', 'logement-entier-hyper-centre.fr.html'],
 ['115', 'tout-beau-tout-neuf.fr.html'],
 ['116', 'pargaminieres-elegant-duplex-proche-du-capitole.fr.html'],
 ['117', 'le-grand-large-biarritz.fr.html'],
 ['118', 'la-maison-du-lierre.fr.html'],
 ['119', 'hotelargieder.fr.html'],
 ['120', 'studio-biarritz-2-min-halles-3-min-plages-plein-centre.fr.html'],
 ['121', 'la-casa-cosy-biarritz.fr.html'],
 ['122', 'studio-grand-plage-de-biarritz.fr.html'],
 ['123', 'vue-exceptionnelle-sur-l-ocean-studio-2-4-pers.fr.html'],
 ['124',
  'biarritz-appartement-4-personnes-a-proximite-immediate-des-plages-et-des-commerc.fr.html'],
 ['125', 'de-la-plage-biarritz.fr.html'],
 ['126', 'cote-des-basques.fr.html'],
 ['127', 'studio-du-phare.fr.html'],
 ['128', 'l-39-ocean-a-perte-de-vue-la-grande-plage-a-vos-pieds.fr.html'],
 ['129', 'palym-biarritz.fr.html'],
 ['130', 'charmant-studio-hyper-centre-biarritz.fr.html'],
 ['131', 'surf-hostel-biarritz.fr.html'],
 ['132', 'hotelanjou.fr.html'],
 ['133', 'biarritz-victoria-surf.fr.html'],
 ['134', 'studio-les-pieds-dans-le-sable-vue-mer-amp-balcon.fr.html'],
 ['135', 'residence-pierre-vacances-haguna.fr.html'],
 ['136', 'amazing-cosy-studio-with-ocean-view-amp-pool.fr.html'],
 ['137', 'home-cassis.fr.html'],
 ['138', 'home-cassis-maison-mediterrannee.fr.html'],
 ['139', 'villa-w.fr.html'],
 ['140', 'mistral-gagnant-cassis.fr.html'],
 ['141',
  '80m2-a-200m-de-la-calanque-de-port-miou-2-chambres-et-parking.fr.html'],
 ['142', 'le-nais-proche-centre-parking-wifi.fr.html'],
 ['143', 'entre-terre-et-mer-a-cassis.fr.html'],
 ['144', 'appartement-saint-malo-saint-malo2.fr.html'],
 ['145', 'les-bois-flottes-saint-malo.fr.html'],
 ['146', 'ajoncsdor.fr.html'],
 ['147',
  'appartement-neuf-et-bien-situe-avec-un-classement-saint-malo.fr.html'],
 ['148', 'grand-appartement-cosy.fr.html'],
 ['149', 'temporesidence-cathedrale.fr.html'],
 ['150', 'libertitu.fr.html'],
 ['151', 'villa-la-renaissance-bayonne.fr.html'],
 ['152', 'cassis-4-pers-vue-mer-wifi-piscine-parking-tennis.fr.html'],
 ['153', 'le-biou.fr.html'],
 ['154', 'au-son-des-cigales-cassis.fr.html'],
 ['155', 'villa-bobnell.fr.html'],
 ['156', 'home-cassis-maison-julou.fr.html'],
 ['157', 'le-pagnol-hyper-centre-clim.fr.html'],
 ['158', 'magnifique-t2-residence-la-rade-vue-mer-parking.fr.html'],
 ['159', 'le-sept-charmant-studio-aux-portes-des-calanques.fr.html'],
 ['160', 'cassis-calanques-2-pieces-grande-terrasse-vue-mer.fr.html'],
 ['161', 'vue-de-reve.fr.html'],
 ['162', 'azur-cassis.fr.html'],
 ['163', 'guest-house-olivades.fr.html'],
 ['164', 'seaview-cassis.fr.html'],
 ['165', 'reves-de-vie-studio-20m2-avec-terrasse-et-parking-prive.fr.html'],
 ['166',
  'splendid-studio-with-parking-lot-right-in-the-center-of-biarritz-welkeys.fr.html'],
 ['167', 'le-cafe-de-paris-4.fr.html'],
 ['168', 'studio-et-piscine-sur-la-grande-plage.fr.html'],
 ['169', 'vtf-le-domaine-de-francon.fr.html'],
 ['170', 'kemaris-biarritz.fr.html'],
 ['171', 'la-rapia-re.fr.html'],
 ['172', 'rooftop-vue-sur-la-cite-rvc-carcassonne1.fr.html'],
 ['173',
  'studio-avec-parking-vue-sur-la-cite-de-carcassonne-carcassonne.fr.html'],
 ['174', 'des-trois-couronnes.fr.html'],
 ['175', 'appartement-petit-saint-gimer.fr.html'],
 ['176', 'chez-micka-carcassonne.fr.html'],
 ['177', 'la-demeure-de-la-cite-by-jean-bacou.fr.html'],
 ['178', 'les-quatre-dauphins.fr.html'],
 ['179', 'les-augustins.fr.html'],
 ['180', 'la-caravelle-aix-en-provence.fr.html'],
 ['181', 'thecamp-amp-lodges.fr.html'],
 ['182', 'paul.fr.html'],
 ['183', 'le-clos-de-la-chartreuse.fr.html'],
 ['184', 'hotel-aquabella.fr.html'],
 ['185', 'good-knight.fr.html'],
 ['186', 'les-florentines-.fr.html'],
 ['187', 'le-rendez-vous-parking-gratuit.fr.html'],
 ['188', 'appartement-carcassone-residence-capucins.fr.html'],
 ['189', 'observatoire-cite-medievale.fr.html'],
 ['190', 'le-pied-a-terre-de-trivalle.fr.html'],
 ['191',
  'jules-appartement-au-calme-dans-la-bastide-proche-citee-medieval.fr.html'],
 ['192', 'petit-capucin.fr.html'],
 ['193', 'new-boheme-chic-pied-de-la-cite-2.fr.html'],
 ['194', 'inter-les-oliviers.fr.html'],
 ['195', 'le-patio-de-la-bastide.fr.html'],
 ['196',
  'studio-pour-2-avec-terrasse-au-pied-de-la-cite-ma-pierre-a-l-edifice.fr.html'],
 ['197', 'best-western-le-galice.fr.html'],
 ['198', 'grand-negre-coste.fr.html'],
 ['199', 'rotonde.fr.html'],
 ['200', 'grand-mercure-roi-rene.fr.html'],
 ['201', 'cezanne-aix-en-provence.fr.html'],
 ['202', 'hotel-escaletto.fr.html'],
 ['203', 'le-nelio.fr.html'],
 ['204', 'domaine-de-carraire-chez-alphonse.fr.html'],
 ['205', 'golden-tulip-aix-en-provence.fr.html'],
 ['206', 'royal-mirabeau.fr.html'],
 ['207', 'pierre-vacances-city-centre.fr.html'],
 ['208', 'cardinal.fr.html'],
 ['209', 'charmant-appartement-hypercentre-aix-en-provence.fr.html'],
 ['210', 'studio-arene-by-k6-you.fr.html'],
 ['211', 'zina.fr.html'],
 ['212', 'cote-gibaou.fr.html'],
 ['213', 'nesme-par-dodo-a-cassis.fr.html'],
 ['214', 'chambre-independante-a-carcassonne.fr.html'],
 ['215', 'appartement-le-joyau-de-courtejaire.fr.html'],
 ['216', 'la-couleur-des-champs.fr.html'],
 ['217', 'appartement-lumineux-en-centre-ville-carcassonne.fr.html'],
 ['218', 'soleil-vacances-les-chevaliers.fr.html'],
 ['219', 'canal-du-midi-carcassonne.fr.html'],
 ['220', 'the-originals-residence-aix-schuman.fr.html'],
 ['221', 'les-floridianes.fr.html'],
 ['222', 'l-39-escapade-aixoise-nuit-romantique.fr.html'],
 ['223', 'renaissance-aix-en-provence.fr.html'],
 ['224', 'amandier-appart-de-charme-au-coeur-d-aix.fr.html'],
 ['225', 'lycee-hotelier-la-rochelle.fr.html'],
 ['226', 'apartment-la-rochelle-historic-city-centre.fr.html'],
 ['227', 'appartements-les-rochelais.fr.html'],
 ['228', 'ambre-appart-wifi-terrasse-parking-terrasse-2-couchages.fr.html'],
 ['229', 'les-3-tours.fr.html'],
 ['230', 'la-rochelle-b.fr.html'],
 ['231', 'le-lodge-park-a-la-rochelle.fr.html'],
 ['232', 'appart-archipel.fr.html'],
 ['233', 'central-park-amp-spa.fr.html'],
 ['234', 'la-rochelle-en-famille-4-personnes.fr.html'],
 ['235', 'les-studios-du-chemins-vert.fr.html'],
 ['236', 'chez-alma.fr.html'],
 ['237', 'b-amp-b-la-rochelle-centre.fr.html'],
 ['238', '360-degres-sur-la-rochelle.fr.html'],
 ['239', 'hotellesbrises.fr.html'],
 ['240', 'location-la-rebelle-la-rochelle-b.fr.html'],
 ['241', 'ponant-3-407.fr.html'],
 ['242', 'porte-oceane-6.fr.html'],
 ['243', 'amazing-apartment-in-la-rochelle-with-wifi.fr.html'],
 ['244', 'studio-cosy-la-rochelle-quartier-des-minimes.fr.html'],
 ['245', 'caporizon-presente-coeur-vieux-port-t2-a-100m-plage.fr.html'],
 ['246', 'le-petit-caillebotis.fr.html'],
 ['247',
  '2-pieces-avec-parking-en-coeur-de-ville-appartement-lumineux-et-calme.fr.html'],
 ['248', 'kyriad-la-rochelle-centre.fr.html'],
 ['249',
  'beautiful-flat-2-minutes-from-the-city-centre-of-la-rochelle-welkeys.fr.html']]

In [28]:
hotel_url

h = []

for id, u in enumerate(hotel_url):
    print(id, u[1])
    h.append(u[1])
print(h)

0 paradise-eart-amp-sea.fr.html
1 grand-t1-vieux-port-salle-de-sport-amp-rooftop.fr.html
2 les-jardins-du-ga-c-na-c-ral.fr.html
3 easyhotel-marseille.fr.html
4 montgrand.fr.html
5 hermes.fr.html
6 nhow-marseille.fr.html
7 citea-marseille-prado-perier.fr.html
8 staycity-aparthotels-centre-vieux-port.fr.html
9 residence-kley-marseille-republique.fr.html
10 alize.fr.html
11 le-mistral-marseille.fr.html
12 l-39-orangeraie-et-la-palmeraie-d-39-endoume.fr.html
13 maison-vue-mer-marseille.fr.html
14 hotelkyrivieuxmarseille.fr.html
15 mouchki-marseille1.fr.html
16 marseille-castellane.fr.html
17 appartement-vieux-port-de-marseille-davso-marseille.fr.html
18 goldentulipvillamassalia.fr.html
19 le-cocon-de-louise.fr.html
20 coup-de-coeur-vieux-port-republique.fr.html
21 bord-de-mer-charmant-studio-entierement-equipe.fr.html
22 superbe-t2-4-etoiles-climatise-faviere-refait-a-neuf.fr.html
23 select-sohome-t2-proche-de-la-station-balneaire-de-la-faviere-azur-17.fr.html
24 bormes-les-mimosas-appart-25m2-avec-balcon-4p.fr.html
25 bormes-le-loft.fr.html
26 studio-alize.fr.html
27 the-little-house-bormes-les-mimosas.fr.html
28 select-sohome-t2-entierement-renove-a-quelques-pas-de-la-plage-pos07.fr.html
29 select-joli-appartement-avec-jardin-privatif-et-parking-capnat-f08.fr.html
30 appartement-pieds-dans-l-eau-vue-mer-bormes-les-mimosas.fr.html
31 les-terrasses-de-lo.fr.html
32 boulevard-du-soleil.fr.html
33 the-social-hub-toulouse.fr.html
34 odalys-city-centre-compans-caffarelli.fr.html
35 crowne-plaza-toulouse-toulouse.fr.html
36 montempo-apparthotel-toulouse-cite-internationale.fr.html
37 le-peri-douillet-appartement-en-hypercentre.fr.html
38 residence-concorde.fr.html
39 des-beaux-arts.fr.html
40 ours-blanc-wilson.fr.html
41 victor-hugo.fr.html
42 eklo-toulouse.fr.html
43 la-romance-apartment-the-heart-of-toulouse.fr.html
44 le-nid-de-la-pomme.fr.html
45 bara-superbe-t2-avec-balcon-a-patte-d-oie.fr.html
46 le-toulousain-202-appartement-cosy-en-hypercentre-quartier-jeanne-d-arc.fr.html
47 la-recampado-bormes-les-mimosas.fr.html
48 select-sohome-superbe-appartement-pour-4-personnes-a-deux-pas-de-la-plage-et-des.fr.html
49 studio-3-pers-coeur-de-village-bormes-les-mimosas.fr.html
50 studio-cosy-climatise-place-de-parking-a-la-faviere.fr.html
51 lovely-place-for-2.fr.html
52 studio-ideal-sejour-en-amoureux-rez-de-jardin-proche-plage.fr.html
53 select-t2-avec-vue-piscine-et-parking-prive-capnat-b08.fr.html
54 le-studio-tahiti-4-pers-200m-de-la-plage.fr.html
55 voir-les-photos-presentationemplacementcommentairesl-39-hote-2-pieces-35m2-borme.fr.html
56 la-lavandiere-bormes-les-mimosas.fr.html
57 les-embruns-bormes-les-mimosas.fr.html
58 face-mer-entre-plage-et-marina.fr.html
59 student-factory-toulouse-zenith.fr.html
60 le-toulousain-102-appartement-cosy-en-hypercentre-quartier-jeanne-d-arc.fr.html
61 t2-cosy-toulouse-hypercentre-metro-jaures-parking-toulouse.fr.html
62 groovy-by-yume.fr.html
63 le-toulousain-001-appartement-calme-en-rez-de-chaussee-avec-terrasse-hypercentre.fr.html
64 nid-calme-en-hypercentre-proche-metro-amp-gare.fr.html
65 les-appartements-de-babel-republique-marseille.fr.html
66 mama-shelter-marseille.fr.html
67 adira-marseille-panier.fr.html
68 amarrage-marseille.fr.html
69 t2-de-charme-a-rochebonne.fr.html
70 de-l-europe-appartements.fr.html
71 calm-and-cosy-saint-malo.fr.html
72 appartement-chaleureux-saint-malo-centre.fr.html
73 centre-saint-malo.fr.html
74 le-servannais.fr.html
75 les-embruns-saint-malo.fr.html
76 cote-basque.fr.html
77 parc-709-bayonne.fr.html
78 city-break-miradour.fr.html
79 l-39-ame-nomade-bayonne-centre.fr.html
80 okko-hotels-bayonne-centre.fr.html
81 des-basses-pyrenees.fr.html
82 iri-etxea-appt-2-chambre-a-bayonne.fr.html
83 villa-koegui-bayonne.fr.html
84 appart-39-bellevue.fr.html
85 comfort-bayonne-biarritz.fr.html
86 le-bayonne-ha-tel.fr.html
87 chez-fleur-bayonne.fr.html
88 un-appart-en-ville-bayonne1.fr.html
89 ibis-bayonne.fr.html
90 kyriad-prestige-saint-malo-xml.fr.html
91 elizabeth.fr.html
92 ar-iniz.fr.html
93 charmant-appartement-saint-malo-saint-servan.fr.html
94 de-france-et-chateaubriand.fr.html
95 anne-de-bretagne.fr.html
96 gite-de-la-tra-c-herais.fr.html
97 malouiniere-guillaume-onffroy.fr.html
98 san-pedro.fr.html
99 plage-de-solidor-quartier-saint-servan.fr.html
100 bleumarinesaintmalo.fr.html
101 appartement-la-grassinais.fr.html
102 heol.fr.html
103 boulevard-hebert.fr.html
104 le-port-neuf.fr.html
105 bayonne-en-plein-coeur-centre-historique-2-chambres.fr.html
106 appartement-t2-bayonne-st-esprit-avec-parking.fr.html
107 loustau.fr.html
108 appartement-t2-cosy-et-calme-bayonne.fr.html
109 le-petit-nid-douillet-chez-jeje.fr.html
110 appartement-residence-neuve.fr.html
111 select-sohome-appartement-spacieux-pour-4-personnes-avec-garage-prive-et-piscine.fr.html
112 le-toulousain-appartement-calme-en-hypercentre-quartier-jeanne-d-arc.fr.html
113 loft-palais-de-justice.fr.html
114 logement-entier-hyper-centre.fr.html
115 tout-beau-tout-neuf.fr.html
116 pargaminieres-elegant-duplex-proche-du-capitole.fr.html
117 le-grand-large-biarritz.fr.html
118 la-maison-du-lierre.fr.html
119 hotelargieder.fr.html
120 studio-biarritz-2-min-halles-3-min-plages-plein-centre.fr.html
121 la-casa-cosy-biarritz.fr.html
122 studio-grand-plage-de-biarritz.fr.html
123 vue-exceptionnelle-sur-l-ocean-studio-2-4-pers.fr.html
124 biarritz-appartement-4-personnes-a-proximite-immediate-des-plages-et-des-commerc.fr.html
125 de-la-plage-biarritz.fr.html
126 cote-des-basques.fr.html
127 studio-du-phare.fr.html
128 l-39-ocean-a-perte-de-vue-la-grande-plage-a-vos-pieds.fr.html
129 palym-biarritz.fr.html
130 charmant-studio-hyper-centre-biarritz.fr.html
131 surf-hostel-biarritz.fr.html
132 hotelanjou.fr.html
133 biarritz-victoria-surf.fr.html
134 studio-les-pieds-dans-le-sable-vue-mer-amp-balcon.fr.html
135 residence-pierre-vacances-haguna.fr.html
136 amazing-cosy-studio-with-ocean-view-amp-pool.fr.html
137 home-cassis.fr.html
138 home-cassis-maison-mediterrannee.fr.html
139 villa-w.fr.html
140 mistral-gagnant-cassis.fr.html
141 80m2-a-200m-de-la-calanque-de-port-miou-2-chambres-et-parking.fr.html
142 le-nais-proche-centre-parking-wifi.fr.html
143 entre-terre-et-mer-a-cassis.fr.html
144 appartement-saint-malo-saint-malo2.fr.html
145 les-bois-flottes-saint-malo.fr.html
146 ajoncsdor.fr.html
147 appartement-neuf-et-bien-situe-avec-un-classement-saint-malo.fr.html
148 grand-appartement-cosy.fr.html
149 temporesidence-cathedrale.fr.html
150 libertitu.fr.html
151 villa-la-renaissance-bayonne.fr.html
152 cassis-4-pers-vue-mer-wifi-piscine-parking-tennis.fr.html
153 le-biou.fr.html
154 au-son-des-cigales-cassis.fr.html
155 villa-bobnell.fr.html
156 home-cassis-maison-julou.fr.html
157 le-pagnol-hyper-centre-clim.fr.html
158 magnifique-t2-residence-la-rade-vue-mer-parking.fr.html
159 le-sept-charmant-studio-aux-portes-des-calanques.fr.html
160 cassis-calanques-2-pieces-grande-terrasse-vue-mer.fr.html
161 vue-de-reve.fr.html
162 azur-cassis.fr.html
163 guest-house-olivades.fr.html
164 seaview-cassis.fr.html
165 reves-de-vie-studio-20m2-avec-terrasse-et-parking-prive.fr.html
166 splendid-studio-with-parking-lot-right-in-the-center-of-biarritz-welkeys.fr.html
167 le-cafe-de-paris-4.fr.html
168 studio-et-piscine-sur-la-grande-plage.fr.html
169 vtf-le-domaine-de-francon.fr.html
170 kemaris-biarritz.fr.html
171 la-rapia-re.fr.html
172 rooftop-vue-sur-la-cite-rvc-carcassonne1.fr.html
173 studio-avec-parking-vue-sur-la-cite-de-carcassonne-carcassonne.fr.html
174 des-trois-couronnes.fr.html
175 appartement-petit-saint-gimer.fr.html
176 chez-micka-carcassonne.fr.html
177 la-demeure-de-la-cite-by-jean-bacou.fr.html
178 les-quatre-dauphins.fr.html
179 les-augustins.fr.html
180 la-caravelle-aix-en-provence.fr.html
181 thecamp-amp-lodges.fr.html
182 paul.fr.html
183 le-clos-de-la-chartreuse.fr.html
184 hotel-aquabella.fr.html
185 good-knight.fr.html
186 les-florentines-.fr.html
187 le-rendez-vous-parking-gratuit.fr.html
188 appartement-carcassone-residence-capucins.fr.html
189 observatoire-cite-medievale.fr.html
190 le-pied-a-terre-de-trivalle.fr.html
191 jules-appartement-au-calme-dans-la-bastide-proche-citee-medieval.fr.html
192 petit-capucin.fr.html
193 new-boheme-chic-pied-de-la-cite-2.fr.html
194 inter-les-oliviers.fr.html
195 le-patio-de-la-bastide.fr.html
196 studio-pour-2-avec-terrasse-au-pied-de-la-cite-ma-pierre-a-l-edifice.fr.html
197 best-western-le-galice.fr.html
198 grand-negre-coste.fr.html
199 rotonde.fr.html
200 grand-mercure-roi-rene.fr.html
201 cezanne-aix-en-provence.fr.html
202 hotel-escaletto.fr.html
203 le-nelio.fr.html
204 domaine-de-carraire-chez-alphonse.fr.html
205 golden-tulip-aix-en-provence.fr.html
206 royal-mirabeau.fr.html
207 pierre-vacances-city-centre.fr.html
208 cardinal.fr.html
209 charmant-appartement-hypercentre-aix-en-provence.fr.html
210 studio-arene-by-k6-you.fr.html
211 zina.fr.html
212 cote-gibaou.fr.html
213 nesme-par-dodo-a-cassis.fr.html
214 chambre-independante-a-carcassonne.fr.html
215 appartement-le-joyau-de-courtejaire.fr.html
216 la-couleur-des-champs.fr.html
217 appartement-lumineux-en-centre-ville-carcassonne.fr.html
218 soleil-vacances-les-chevaliers.fr.html
219 canal-du-midi-carcassonne.fr.html
220 the-originals-residence-aix-schuman.fr.html
221 les-floridianes.fr.html
222 l-39-escapade-aixoise-nuit-romantique.fr.html
223 renaissance-aix-en-provence.fr.html
224 amandier-appart-de-charme-au-coeur-d-aix.fr.html
225 lycee-hotelier-la-rochelle.fr.html
226 apartment-la-rochelle-historic-city-centre.fr.html
227 appartements-les-rochelais.fr.html
228 ambre-appart-wifi-terrasse-parking-terrasse-2-couchages.fr.html
229 les-3-tours.fr.html
230 la-rochelle-b.fr.html
231 le-lodge-park-a-la-rochelle.fr.html
232 appart-archipel.fr.html
233 central-park-amp-spa.fr.html
234 la-rochelle-en-famille-4-personnes.fr.html
235 les-studios-du-chemins-vert.fr.html
236 chez-alma.fr.html
237 b-amp-b-la-rochelle-centre.fr.html
238 360-degres-sur-la-rochelle.fr.html
239 hotellesbrises.fr.html
240 location-la-rebelle-la-rochelle-b.fr.html
241 ponant-3-407.fr.html
242 porte-oceane-6.fr.html
243 amazing-apartment-in-la-rochelle-with-wifi.fr.html
244 studio-cosy-la-rochelle-quartier-des-minimes.fr.html
245 caporizon-presente-coeur-vieux-port-t2-a-100m-plage.fr.html
246 le-petit-caillebotis.fr.html
247 2-pieces-avec-parking-en-coeur-de-ville-appartement-lumineux-et-calme.fr.html
248 kyriad-la-rochelle-centre.fr.html
249 beautiful-flat-2-minutes-from-the-city-centre-of-la-rochelle-welkeys.fr.html

In [29]:
print(h)

['paradise-eart-amp-sea.fr.html', 'grand-t1-vieux-port-salle-de-sport-amp-rooftop.fr.html', 'les-jardins-du-ga-c-na-c-ral.fr.html', 'easyhotel-marseille.fr.html', 'montgrand.fr.html', 'hermes.fr.html', 'nhow-marseille.fr.html', 'citea-marseille-prado-perier.fr.html', 'staycity-aparthotels-centre-vieux-port.fr.html', 'residence-kley-marseille-republique.fr.html', 'alize.fr.html', 'le-mistral-marseille.fr.html', 'l-39-orangeraie-et-la-palmeraie-d-39-endoume.fr.html', 'maison-vue-mer-marseille.fr.html', 'hotelkyrivieuxmarseille.fr.html', 'mouchki-marseille1.fr.html', 'marseille-castellane.fr.html', 'appartement-vieux-port-de-marseille-davso-marseille.fr.html', 'goldentulipvillamassalia.fr.html', 'le-cocon-de-louise.fr.html', 'coup-de-coeur-vieux-port-republique.fr.html', 'bord-de-mer-charmant-studio-entierement-equipe.fr.html', 'superbe-t2-4-etoiles-climatise-faviere-refait-a-neuf.fr.html', 'select-sohome-t2-proche-de-la-station-balneaire-de-la-faviere-azur-17.fr.html', 'bormes-les-mimosas-appart-25m2-avec-balcon-4p.fr.html', 'bormes-le-loft.fr.html', 'studio-alize.fr.html', 'the-little-house-bormes-les-mimosas.fr.html', 'select-sohome-t2-entierement-renove-a-quelques-pas-de-la-plage-pos07.fr.html', 'select-joli-appartement-avec-jardin-privatif-et-parking-capnat-f08.fr.html', 'appartement-pieds-dans-l-eau-vue-mer-bormes-les-mimosas.fr.html', 'les-terrasses-de-lo.fr.html', 'boulevard-du-soleil.fr.html', 'the-social-hub-toulouse.fr.html', 'odalys-city-centre-compans-caffarelli.fr.html', 'crowne-plaza-toulouse-toulouse.fr.html', 'montempo-apparthotel-toulouse-cite-internationale.fr.html', 'le-peri-douillet-appartement-en-hypercentre.fr.html', 'residence-concorde.fr.html', 'des-beaux-arts.fr.html', 'ours-blanc-wilson.fr.html', 'victor-hugo.fr.html', 'eklo-toulouse.fr.html', 'la-romance-apartment-the-heart-of-toulouse.fr.html', 'le-nid-de-la-pomme.fr.html', 'bara-superbe-t2-avec-balcon-a-patte-d-oie.fr.html', 'le-toulousain-202-appartement-cosy-en-hypercentre-quartier-jeanne-d-arc.fr.html', 'la-recampado-bormes-les-mimosas.fr.html', 'select-sohome-superbe-appartement-pour-4-personnes-a-deux-pas-de-la-plage-et-des.fr.html', 'studio-3-pers-coeur-de-village-bormes-les-mimosas.fr.html', 'studio-cosy-climatise-place-de-parking-a-la-faviere.fr.html', 'lovely-place-for-2.fr.html', 'studio-ideal-sejour-en-amoureux-rez-de-jardin-proche-plage.fr.html', 'select-t2-avec-vue-piscine-et-parking-prive-capnat-b08.fr.html', 'le-studio-tahiti-4-pers-200m-de-la-plage.fr.html', 'voir-les-photos-presentationemplacementcommentairesl-39-hote-2-pieces-35m2-borme.fr.html', 'la-lavandiere-bormes-les-mimosas.fr.html', 'les-embruns-bormes-les-mimosas.fr.html', 'face-mer-entre-plage-et-marina.fr.html', 'student-factory-toulouse-zenith.fr.html', 'le-toulousain-102-appartement-cosy-en-hypercentre-quartier-jeanne-d-arc.fr.html', 't2-cosy-toulouse-hypercentre-metro-jaures-parking-toulouse.fr.html', 'groovy-by-yume.fr.html', 'le-toulousain-001-appartement-calme-en-rez-de-chaussee-avec-terrasse-hypercentre.fr.html', 'nid-calme-en-hypercentre-proche-metro-amp-gare.fr.html', 'les-appartements-de-babel-republique-marseille.fr.html', 'mama-shelter-marseille.fr.html', 'adira-marseille-panier.fr.html', 'amarrage-marseille.fr.html', 't2-de-charme-a-rochebonne.fr.html', 'de-l-europe-appartements.fr.html', 'calm-and-cosy-saint-malo.fr.html', 'appartement-chaleureux-saint-malo-centre.fr.html', 'centre-saint-malo.fr.html', 'le-servannais.fr.html', 'les-embruns-saint-malo.fr.html', 'cote-basque.fr.html', 'parc-709-bayonne.fr.html', 'city-break-miradour.fr.html', 'l-39-ame-nomade-bayonne-centre.fr.html', 'okko-hotels-bayonne-centre.fr.html', 'des-basses-pyrenees.fr.html', 'iri-etxea-appt-2-chambre-a-bayonne.fr.html', 'villa-koegui-bayonne.fr.html', 'appart-39-bellevue.fr.html', 'comfort-bayonne-biarritz.fr.html', 'le-bayonne-ha-tel.fr.html', 'chez-fleur-bayonne.fr.html', 'un-appart-en-ville-bayonne1.fr.html', 'ibis-bayonne.fr.html', 'kyriad-prestige-saint-malo-xml.fr.html', 'elizabeth.fr.html', 'ar-iniz.fr.html', 'charmant-appartement-saint-malo-saint-servan.fr.html', 'de-france-et-chateaubriand.fr.html', 'anne-de-bretagne.fr.html', 'gite-de-la-tra-c-herais.fr.html', 'malouiniere-guillaume-onffroy.fr.html', 'san-pedro.fr.html', 'plage-de-solidor-quartier-saint-servan.fr.html', 'bleumarinesaintmalo.fr.html', 'appartement-la-grassinais.fr.html', 'heol.fr.html', 'boulevard-hebert.fr.html', 'le-port-neuf.fr.html', 'bayonne-en-plein-coeur-centre-historique-2-chambres.fr.html', 'appartement-t2-bayonne-st-esprit-avec-parking.fr.html', 'loustau.fr.html', 'appartement-t2-cosy-et-calme-bayonne.fr.html', 'le-petit-nid-douillet-chez-jeje.fr.html', 'appartement-residence-neuve.fr.html', 'select-sohome-appartement-spacieux-pour-4-personnes-avec-garage-prive-et-piscine.fr.html', 'le-toulousain-appartement-calme-en-hypercentre-quartier-jeanne-d-arc.fr.html', 'loft-palais-de-justice.fr.html', 'logement-entier-hyper-centre.fr.html', 'tout-beau-tout-neuf.fr.html', 'pargaminieres-elegant-duplex-proche-du-capitole.fr.html', 'le-grand-large-biarritz.fr.html', 'la-maison-du-lierre.fr.html', 'hotelargieder.fr.html', 'studio-biarritz-2-min-halles-3-min-plages-plein-centre.fr.html', 'la-casa-cosy-biarritz.fr.html', 'studio-grand-plage-de-biarritz.fr.html', 'vue-exceptionnelle-sur-l-ocean-studio-2-4-pers.fr.html', 'biarritz-appartement-4-personnes-a-proximite-immediate-des-plages-et-des-commerc.fr.html', 'de-la-plage-biarritz.fr.html', 'cote-des-basques.fr.html', 'studio-du-phare.fr.html', 'l-39-ocean-a-perte-de-vue-la-grande-plage-a-vos-pieds.fr.html', 'palym-biarritz.fr.html', 'charmant-studio-hyper-centre-biarritz.fr.html', 'surf-hostel-biarritz.fr.html', 'hotelanjou.fr.html', 'biarritz-victoria-surf.fr.html', 'studio-les-pieds-dans-le-sable-vue-mer-amp-balcon.fr.html', 'residence-pierre-vacances-haguna.fr.html', 'amazing-cosy-studio-with-ocean-view-amp-pool.fr.html', 'home-cassis.fr.html', 'home-cassis-maison-mediterrannee.fr.html', 'villa-w.fr.html', 'mistral-gagnant-cassis.fr.html', '80m2-a-200m-de-la-calanque-de-port-miou-2-chambres-et-parking.fr.html', 'le-nais-proche-centre-parking-wifi.fr.html', 'entre-terre-et-mer-a-cassis.fr.html', 'appartement-saint-malo-saint-malo2.fr.html', 'les-bois-flottes-saint-malo.fr.html', 'ajoncsdor.fr.html', 'appartement-neuf-et-bien-situe-avec-un-classement-saint-malo.fr.html', 'grand-appartement-cosy.fr.html', 'temporesidence-cathedrale.fr.html', 'libertitu.fr.html', 'villa-la-renaissance-bayonne.fr.html', 'cassis-4-pers-vue-mer-wifi-piscine-parking-tennis.fr.html', 'le-biou.fr.html', 'au-son-des-cigales-cassis.fr.html', 'villa-bobnell.fr.html', 'home-cassis-maison-julou.fr.html', 'le-pagnol-hyper-centre-clim.fr.html', 'magnifique-t2-residence-la-rade-vue-mer-parking.fr.html', 'le-sept-charmant-studio-aux-portes-des-calanques.fr.html', 'cassis-calanques-2-pieces-grande-terrasse-vue-mer.fr.html', 'vue-de-reve.fr.html', 'azur-cassis.fr.html', 'guest-house-olivades.fr.html', 'seaview-cassis.fr.html', 'reves-de-vie-studio-20m2-avec-terrasse-et-parking-prive.fr.html', 'splendid-studio-with-parking-lot-right-in-the-center-of-biarritz-welkeys.fr.html', 'le-cafe-de-paris-4.fr.html', 'studio-et-piscine-sur-la-grande-plage.fr.html', 'vtf-le-domaine-de-francon.fr.html', 'kemaris-biarritz.fr.html', 'la-rapia-re.fr.html', 'rooftop-vue-sur-la-cite-rvc-carcassonne1.fr.html', 'studio-avec-parking-vue-sur-la-cite-de-carcassonne-carcassonne.fr.html', 'des-trois-couronnes.fr.html', 'appartement-petit-saint-gimer.fr.html', 'chez-micka-carcassonne.fr.html', 'la-demeure-de-la-cite-by-jean-bacou.fr.html', 'les-quatre-dauphins.fr.html', 'les-augustins.fr.html', 'la-caravelle-aix-en-provence.fr.html', 'thecamp-amp-lodges.fr.html', 'paul.fr.html', 'le-clos-de-la-chartreuse.fr.html', 'hotel-aquabella.fr.html', 'good-knight.fr.html', 'les-florentines-.fr.html', 'le-rendez-vous-parking-gratuit.fr.html', 'appartement-carcassone-residence-capucins.fr.html', 'observatoire-cite-medievale.fr.html', 'le-pied-a-terre-de-trivalle.fr.html', 'jules-appartement-au-calme-dans-la-bastide-proche-citee-medieval.fr.html', 'petit-capucin.fr.html', 'new-boheme-chic-pied-de-la-cite-2.fr.html', 'inter-les-oliviers.fr.html', 'le-patio-de-la-bastide.fr.html', 'studio-pour-2-avec-terrasse-au-pied-de-la-cite-ma-pierre-a-l-edifice.fr.html', 'best-western-le-galice.fr.html', 'grand-negre-coste.fr.html', 'rotonde.fr.html', 'grand-mercure-roi-rene.fr.html', 'cezanne-aix-en-provence.fr.html', 'hotel-escaletto.fr.html', 'le-nelio.fr.html', 'domaine-de-carraire-chez-alphonse.fr.html', 'golden-tulip-aix-en-provence.fr.html', 'royal-mirabeau.fr.html', 'pierre-vacances-city-centre.fr.html', 'cardinal.fr.html', 'charmant-appartement-hypercentre-aix-en-provence.fr.html', 'studio-arene-by-k6-you.fr.html', 'zina.fr.html', 'cote-gibaou.fr.html', 'nesme-par-dodo-a-cassis.fr.html', 'chambre-independante-a-carcassonne.fr.html', 'appartement-le-joyau-de-courtejaire.fr.html', 'la-couleur-des-champs.fr.html', 'appartement-lumineux-en-centre-ville-carcassonne.fr.html', 'soleil-vacances-les-chevaliers.fr.html', 'canal-du-midi-carcassonne.fr.html', 'the-originals-residence-aix-schuman.fr.html', 'les-floridianes.fr.html', 'l-39-escapade-aixoise-nuit-romantique.fr.html', 'renaissance-aix-en-provence.fr.html', 'amandier-appart-de-charme-au-coeur-d-aix.fr.html', 'lycee-hotelier-la-rochelle.fr.html', 'apartment-la-rochelle-historic-city-centre.fr.html', 'appartements-les-rochelais.fr.html', 'ambre-appart-wifi-terrasse-parking-terrasse-2-couchages.fr.html', 'les-3-tours.fr.html', 'la-rochelle-b.fr.html', 'le-lodge-park-a-la-rochelle.fr.html', 'appart-archipel.fr.html', 'central-park-amp-spa.fr.html', 'la-rochelle-en-famille-4-personnes.fr.html', 'les-studios-du-chemins-vert.fr.html', 'chez-alma.fr.html', 'b-amp-b-la-rochelle-centre.fr.html', '360-degres-sur-la-rochelle.fr.html', 'hotellesbrises.fr.html', 'location-la-rebelle-la-rochelle-b.fr.html', 'ponant-3-407.fr.html', 'porte-oceane-6.fr.html', 'amazing-apartment-in-la-rochelle-with-wifi.fr.html', 'studio-cosy-la-rochelle-quartier-des-minimes.fr.html', 'caporizon-presente-coeur-vieux-port-t2-a-100m-plage.fr.html', 'le-petit-caillebotis.fr.html', '2-pieces-avec-parking-en-coeur-de-ville-appartement-lumineux-et-calme.fr.html', 'kyriad-la-rochelle-centre.fr.html', 'beautiful-flat-2-minutes-from-the-city-centre-of-la-rochelle-welkeys.fr.html']

In [23]:
! python kayak_spider_hotel_GPS_22fev.py

2025-02-23 00:17:44 [scrapy.utils.log] INFO: Scrapy 2.11.1 started (bot: scrapybot)
2025-02-23 00:17:44 [scrapy.utils.log] INFO: Versions: lxml 5.2.1.0, libxml2 2.13.1, cssselect 1.2.0, parsel 1.8.1, w3lib 2.1.2, Twisted 23.10.0, Python 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 21:00:12) [Clang 16.0.6 ], pyOpenSSL 24.2.1 (OpenSSL 3.4.1 11 Feb 2025), cryptography 43.0.0, Platform macOS-11.7.10-x86_64-i386-64bit
2025-02-23 00:17:44 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-23 00:17:44 [py.warnings] WARNING: /opt/anaconda3/lib/python3.12/site-packages/scrapy/utils/request.py:254: ScrapyDeprecationWarning: '2.6' is a deprecated value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting.

It is also the default value. In other words, it is normal to get this warning if you have not defined a value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting. This is so for backward compatibility reasons, but it will change in a future version of Scrapy.

See the documentation of the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting for information on how to handle this deprecation.
  return cls(crawler)

2025-02-23 00:17:44 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.selectreactor.SelectReactor
2025-02-23 00:17:44 [scrapy.extensions.telnet] INFO: Telnet Password: a947196f58e30bbc
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-23 00:17:44 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-23 00:17:44 [scrapy.core.engine] INFO: Spider opened
2025-02-23 00:17:44 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-23 00:17:44 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2025-02-23 00:17:44 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-23 00:17:44 [py.warnings] WARNING: /opt/anaconda3/lib/python3.12/site-packages/scrapy/utils/request.py:254: ScrapyDeprecationWarning: '2.6' is a deprecated value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting.

It is also the default value. In other words, it is normal to get this warning if you have not defined a value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting. This is so for backward compatibility reasons, but it will change in a future version of Scrapy.

See the documentation of the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting for information on how to handle this deprecation.
  return cls(crawler)

2025-02-23 00:17:44 [scrapy.extensions.telnet] INFO: Telnet Password: 0a00e1a6f1163fe5
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-23 00:17:44 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-23 00:17:44 [scrapy.core.engine] INFO: Spider opened
2025-02-23 00:17:44 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-23 00:17:44 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6024
2025-02-23 00:17:44 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-23 00:17:44 [scrapy.extensions.telnet] INFO: Telnet Password: 854581304cfbb5af
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-23 00:17:44 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-23 00:17:44 [scrapy.core.engine] INFO: Spider opened
2025-02-23 00:17:44 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-23 00:17:44 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6025
2025-02-23 00:17:44 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-23 00:17:44 [scrapy.extensions.telnet] INFO: Telnet Password: a96fe030b2a0d0a9
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-23 00:17:44 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-23 00:17:44 [scrapy.core.engine] INFO: Spider opened
2025-02-23 00:17:44 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-23 00:17:44 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6026
2025-02-23 00:17:44 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-23 00:17:44 [scrapy.extensions.telnet] INFO: Telnet Password: 5c9f3115ef0eb7f5
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-23 00:17:44 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-23 00:17:44 [scrapy.core.engine] INFO: Spider opened
2025-02-23 00:17:44 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-23 00:17:44 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6027
2025-02-23 00:17:44 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-23 00:17:44 [scrapy.extensions.telnet] INFO: Telnet Password: 4cca493670603939
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-23 00:17:44 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-23 00:17:44 [scrapy.core.engine] INFO: Spider opened
2025-02-23 00:17:44 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-23 00:17:44 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6028
2025-02-23 00:17:44 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-23 00:17:44 [scrapy.extensions.telnet] INFO: Telnet Password: 849ca12e33c3e70f
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-23 00:17:44 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-23 00:17:44 [scrapy.core.engine] INFO: Spider opened
2025-02-23 00:17:44 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-23 00:17:44 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6029
2025-02-23 00:17:44 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-23 00:17:44 [scrapy.extensions.telnet] INFO: Telnet Password: bed12a0992e2d17e
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-23 00:17:44 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-23 00:17:44 [scrapy.core.engine] INFO: Spider opened
2025-02-23 00:17:44 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-23 00:17:44 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6030
2025-02-23 00:17:44 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-23 00:17:44 [scrapy.extensions.telnet] INFO: Telnet Password: 3665d3ca97430afe
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-23 00:17:44 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-23 00:17:44 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',

In [33]:
! python kayak_spider_hotel_GPS_22fev.py

2025-02-23 00:30:13 [scrapy.utils.log] INFO: Scrapy 2.11.1 started (bot: scrapybot)
2025-02-23 00:30:13 [scrapy.utils.log] INFO: Versions: lxml 5.2.1.0, libxml2 2.13.1, cssselect 1.2.0, parsel 1.8.1, w3lib 2.1.2, Twisted 23.10.0, Python 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 21:00:12) [Clang 16.0.6 ], pyOpenSSL 24.2.1 (OpenSSL 3.4.1 11 Feb 2025), cryptography 43.0.0, Platform macOS-11.7.10-x86_64-i386-64bit
2025-02-23 00:30:13 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-23 00:30:13 [py.warnings] WARNING: /opt/anaconda3/lib/python3.12/site-packages/scrapy/utils/request.py:254: ScrapyDeprecationWarning: '2.6' is a deprecated value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting.

It is also the default value. In other words, it is normal to get this warning if you have not defined a value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting. This is so for backward compatibility reasons, but it will change in a future version of Scrapy.

See the documentation of the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting for information on how to handle this deprecation.
  return cls(crawler)

2025-02-23 00:30:13 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.selectreactor.SelectReactor
2025-02-23 00:30:13 [scrapy.extensions.telnet] INFO: Telnet Password: ba2542e142760944
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-23 00:30:13 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-23 00:30:13 [scrapy.core.engine] INFO: Spider opened
2025-02-23 00:30:13 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-23 00:30:13 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2025-02-23 00:30:13 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-23 00:30:13 [py.warnings] WARNING: /opt/anaconda3/lib/python3.12/site-packages/scrapy/utils/request.py:254: ScrapyDeprecationWarning: '2.6' is a deprecated value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting.

It is also the default value. In other words, it is normal to get this warning if you have not defined a value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting. This is so for backward compatibility reasons, but it will change in a future version of Scrapy.

See the documentation of the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting for information on how to handle this deprecation.
  return cls(crawler)

2025-02-23 00:30:13 [scrapy.extensions.telnet] INFO: Telnet Password: 007ffc650f26402e
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-23 00:30:13 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-23 00:30:13 [scrapy.core.engine] INFO: Spider opened
2025-02-23 00:30:13 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-23 00:30:13 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6024
2025-02-23 00:30:13 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-23 00:30:13 [scrapy.extensions.telnet] INFO: Telnet Password: 92510bf638e8a7d5
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-23 00:30:13 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-23 00:30:13 [scrapy.core.engine] INFO: Spider opened
2025-02-23 00:30:13 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-23 00:30:13 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6025
2025-02-23 00:30:13 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-23 00:30:13 [scrapy.extensions.telnet] INFO: Telnet Password: 3644c48b251a689d
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-23 00:30:13 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-23 00:30:13 [scrapy.core.engine] INFO: Spider opened
2025-02-23 00:30:13 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-23 00:30:13 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6026
2025-02-23 00:30:13 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-23 00:30:13 [scrapy.extensions.telnet] INFO: Telnet Password: 9e59f3e4f6de7422
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-23 00:30:13 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-23 00:30:13 [scrapy.core.engine] INFO: Spider opened
2025-02-23 00:30:13 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-23 00:30:13 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6027
2025-02-23 00:30:13 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-23 00:30:13 [scrapy.extensions.telnet] INFO: Telnet Password: 9c31e9090c5c0928
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-23 00:30:13 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-23 00:30:13 [scrapy.core.engine] INFO: Spider opened
2025-02-23 00:30:13 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-23 00:30:13 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6028
2025-02-23 00:30:13 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-23 00:30:13 [scrapy.extensions.telnet] INFO: Telnet Password: 7ddaf07e6c2e9ec6
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-23 00:30:13 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-23 00:30:13 [scrapy.core.engine] INFO: Spider opened
2025-02-23 00:30:13 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-23 00:30:13 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6029
2025-02-23 00:30:13 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-23 00:30:13 [scrapy.extensions.telnet] INFO: Telnet Password: 90c02fca40f7d6cf
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-23 00:30:13 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-23 00:30:13 [scrapy.core.engine] INFO: Spider opened
2025-02-23 00:30:13 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-23 00:30:13 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6030
2025-02-23 00:30:13 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-23 00:30:13 [scrapy.extensions.telnet] INFO: Telnet Password: 31785203d764d854
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-23 00:30:13 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 10,
 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
               '(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
2025-02-23 00:30:13 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',