In [22]:
# To Launch
import pandas as pd
import json
import plotly.io as pio
import plotly.express as px

In [23]:
#To launch
df = pd.read_json('ten_hotels_town_id_facilitie_f.json', lines=True)
df

,Id,hotel_name,hotel_lat,hotel_long,hotel_rating,hotel_description,hotel_facilities,hotel_facilities_1,hotel_facilities_2,hotel_facilities_3,hotel_facilities_4
0,20,easyHotel Marseille Euromed,43.310115,5.370340,"8,5",L’établissement easyHotel Marseille Euromed bé...,Connexion Wi-Fi gratuite,Équipements pour les personnes handicapées,Réception ouverte 24h/24,Ascenseur,Chauffage
1,20,Staycity Aparthotels Marseille Centre Vieux Port,43.300466,5.374442,"8,4","Doté d'une connexion Wi-Fi gratuite, le Stayci...",Parking,Connexion Wi-Fi gratuite,Chambres familiales,Chambres non-fumeurs,Équipements pour les personnes handicapées
2,20,Coup de Cœur VIEUX PORT-République,43.298031,5.372932,"9,6",L’hébergement Coup de Cœur VIEUX PORT-Républiq...,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Réception ouverte 24h/24,Terrasse,Chauffage
3,18,"Bord de mer, charmant studio entièrement équipé",43.126023,6.358852,"9,4","L’hébergement Bord de mer, charmant studio ent...",Parking gratuit,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Parking gratuit,Connexion Wi-Fi gratuite
4,20,"Maison vue Mer, Marseille.",43.354912,5.333493,"9,5","Offrant une vue sur la ville, l’hébergement Ma...",Connexion Wi-Fi gratuite,Terrasse,Connexion Wi-Fi gratuite,Terrasse,Machine à café
...,...,...,...,...,...,...,...,...,...,...,...
245,34,** Studio cosy La Rochelle quartier des Minime...,46.140106,-1.161035,"9,1",L’hébergement en bord de mer ** Studio cosy La...,Parking gratuit,Connexion Wi-Fi gratuite,En bord de plage,Chambres non-fumeurs,Parking gratuit
246,34,Le Petit Caillebotis,46.142908,-1.156299,"9,0",L’hébergement Le Petit Caillebotis se situe à ...,Parking gratuit,Chambres familiales,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Terrasse
247,34,Hôtel Kyriad La Rochelle Centre Ville,46.157796,-1.138319,"8,4",L’Hôtel Kyriad La Rochelle Centre Ville vous a...,Parking privé,Chambres familiales,Connexion Wi-Fi gratuite,Restaurant,Chambres non-fumeurs
248,19,Le Nadadou par Dodo à Cassis,43.213317,5.549367,"8,4",L’hébergement Le Nadadou par Dodo à Cassis pro...,Parking gratuit,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Terrasse,Jardin
249,21,Odalys City Aix en Provence Les Floridianes,43.521333,5.444777,"8,0",L'Odalys City Aix en Provence Les Floridianes ...,Piscine extérieure,Parking privé,Connexion Wi-Fi gratuite,Chambres familiales,Chambres non-fumeurs

In [24]:
df.loc[df['hotel_facilities_1'] == df['hotel_facilities'], 'hotel_facilities_1'] = '***'
df.loc[df['hotel_facilities_2'] == df['hotel_facilities'], 'hotel_facilities_2'] = '***'
df.loc[df['hotel_facilities_3'] == df['hotel_facilities'], 'hotel_facilities_3'] = '***'
df.loc[df['hotel_facilities_4'] == df['hotel_facilities'], 'hotel_facilities_4'] = '***'
df.loc[df['hotel_facilities_2'] == df['hotel_facilities_1'], 'hotel_facilities_2'] = '***'
df.loc[df['hotel_facilities_3'] == df['hotel_facilities_1'], 'hotel_facilities_3'] = '***'
df.loc[df['hotel_facilities_4'] == df['hotel_facilities_1'], 'hotel_facilities_4'] = '***'
df.loc[df['hotel_facilities_3'] == df['hotel_facilities_2'], 'hotel_facilities_3'] = '***'
df.loc[df['hotel_facilities_4'] == df['hotel_facilities_2'], 'hotel_facilities_4'] = '***'
df.loc[df['hotel_facilities_4'] == df['hotel_facilities_3'], 'hotel_facilities_4'] = '***'

In [25]:
df

,Id,hotel_name,hotel_lat,hotel_long,hotel_rating,hotel_description,hotel_facilities,hotel_facilities_1,hotel_facilities_2,hotel_facilities_3,hotel_facilities_4
0,20,easyHotel Marseille Euromed,43.310115,5.370340,"8,5",L’établissement easyHotel Marseille Euromed bé...,Connexion Wi-Fi gratuite,Équipements pour les personnes handicapées,Réception ouverte 24h/24,Ascenseur,Chauffage
1,20,Staycity Aparthotels Marseille Centre Vieux Port,43.300466,5.374442,"8,4","Doté d'une connexion Wi-Fi gratuite, le Stayci...",Parking,Connexion Wi-Fi gratuite,Chambres familiales,Chambres non-fumeurs,Équipements pour les personnes handicapées
2,20,Coup de Cœur VIEUX PORT-République,43.298031,5.372932,"9,6",L’hébergement Coup de Cœur VIEUX PORT-Républiq...,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Réception ouverte 24h/24,Terrasse,Chauffage
3,18,"Bord de mer, charmant studio entièrement équipé",43.126023,6.358852,"9,4","L’hébergement Bord de mer, charmant studio ent...",Parking gratuit,Connexion Wi-Fi gratuite,Chambres non-fumeurs,***,***
4,20,"Maison vue Mer, Marseille.",43.354912,5.333493,"9,5","Offrant une vue sur la ville, l’hébergement Ma...",Connexion Wi-Fi gratuite,Terrasse,***,***,Machine à café
...,...,...,...,...,...,...,...,...,...,...,...
245,34,** Studio cosy La Rochelle quartier des Minime...,46.140106,-1.161035,"9,1",L’hébergement en bord de mer ** Studio cosy La...,Parking gratuit,Connexion Wi-Fi gratuite,En bord de plage,Chambres non-fumeurs,***
246,34,Le Petit Caillebotis,46.142908,-1.156299,"9,0",L’hébergement Le Petit Caillebotis se situe à ...,Parking gratuit,Chambres familiales,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Terrasse
247,34,Hôtel Kyriad La Rochelle Centre Ville,46.157796,-1.138319,"8,4",L’Hôtel Kyriad La Rochelle Centre Ville vous a...,Parking privé,Chambres familiales,Connexion Wi-Fi gratuite,Restaurant,Chambres non-fumeurs
248,19,Le Nadadou par Dodo à Cassis,43.213317,5.549367,"8,4",L’hébergement Le Nadadou par Dodo à Cassis pro...,Parking gratuit,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Terrasse,Jardin
249,21,Odalys City Aix en Provence Les Floridianes,43.521333,5.444777,"8,0",L'Odalys City Aix en Provence Les Floridianes ...,Piscine extérieure,Parking privé,Connexion Wi-Fi gratuite,Chambres familiales,Chambres non-fumeurs

In [26]:
hotel_gps_forecast = pd.read_csv('Town_Geo_Forcast.csv')
hotel_gps_forecast['Id'] = hotel_gps_forecast['Id'].apply(lambda x: x + 249)
hotel_gps_forecast = hotel_gps_forecast.drop('Unnamed: 0', axis = 1)

In [27]:
# To Launch

hotel_gps_forecast = hotel_gps_forecast.rename(columns={'Towns' : 'towns',
                                'Latitude' : 'town_lat',
                                'Longitude' : 'town_long',
                                'temperature_forcast' : 'temperature_forecast',
                                'weather_forcast' : 'weather_forecast'})
hotel_gps_forecast.sample(5)

,Id,towns,town_lat,town_long,temperature_forecast,weather_forecast
31,280,Montauban,44.017584,1.354999,7,Clear
0,249,Mont Saint-Michel,48.635954,-1.511460,8,Clouds
30,279,Toulouse,43.604462,1.444247,13,Clear
24,273,Nîmes,43.837425,4.360069,10,Clear
9,258,Château du Haut-Kœnigsbourg,48.249411,7.344320,0,Clear

In [28]:
# To Launch

result = pd.concat([df, hotel_gps_forecast])

In [29]:
result

,Id,hotel_name,hotel_lat,hotel_long,hotel_rating,hotel_description,hotel_facilities,hotel_facilities_1,hotel_facilities_2,hotel_facilities_3,hotel_facilities_4,towns,town_lat,town_long,temperature_forecast,weather_forecast
0,20,easyHotel Marseille Euromed,43.310115,5.370340,"8,5",L’établissement easyHotel Marseille Euromed bé...,Connexion Wi-Fi gratuite,Équipements pour les personnes handicapées,Réception ouverte 24h/24,Ascenseur,Chauffage,NaN,NaN,NaN,NaN,NaN
1,20,Staycity Aparthotels Marseille Centre Vieux Port,43.300466,5.374442,"8,4","Doté d'une connexion Wi-Fi gratuite, le Stayci...",Parking,Connexion Wi-Fi gratuite,Chambres familiales,Chambres non-fumeurs,Équipements pour les personnes handicapées,NaN,NaN,NaN,NaN,NaN
2,20,Coup de Cœur VIEUX PORT-République,43.298031,5.372932,"9,6",L’hébergement Coup de Cœur VIEUX PORT-Républiq...,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Réception ouverte 24h/24,Terrasse,Chauffage,NaN,NaN,NaN,NaN,NaN
3,18,"Bord de mer, charmant studio entièrement équipé",43.126023,6.358852,"9,4","L’hébergement Bord de mer, charmant studio ent...",Parking gratuit,Connexion Wi-Fi gratuite,Chambres non-fumeurs,***,***,NaN,NaN,NaN,NaN,NaN
4,20,"Maison vue Mer, Marseille.",43.354912,5.333493,"9,5","Offrant une vue sur la ville, l’hébergement Ma...",Connexion Wi-Fi gratuite,Terrasse,***,***,Machine à café,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30,279,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Toulouse,43.604462,1.444247,13.0,Clear
31,280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Montauban,44.017584,1.354999,7.0,Clear
32,281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Biarritz,43.471144,-1.552727,12.0,Clear
33,282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bayonne,43.494514,-1.473666,12.0,Clear
34,283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,La Rochelle,46.159732,-1.151595,11.0,Clear

In [30]:
# To Launch
result= result[result["hotel_rating"].notnull()]

In [31]:
result['hotel_rating'] = result['hotel_rating'].apply(lambda x: x.replace(',', '.')).apply(pd.to_numeric)

/var/folders/mk/k32g1gsn4c1_yd1vbqdbpvw00000gn/T/ipykernel_6608/3321586000.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [32]:
result

,Id,hotel_name,hotel_lat,hotel_long,hotel_rating,hotel_description,hotel_facilities,hotel_facilities_1,hotel_facilities_2,hotel_facilities_3,hotel_facilities_4,towns,town_lat,town_long,temperature_forecast,weather_forecast
0,20,easyHotel Marseille Euromed,43.310115,5.370340,8.5,L’établissement easyHotel Marseille Euromed bé...,Connexion Wi-Fi gratuite,Équipements pour les personnes handicapées,Réception ouverte 24h/24,Ascenseur,Chauffage,NaN,NaN,NaN,NaN,NaN
1,20,Staycity Aparthotels Marseille Centre Vieux Port,43.300466,5.374442,8.4,"Doté d'une connexion Wi-Fi gratuite, le Stayci...",Parking,Connexion Wi-Fi gratuite,Chambres familiales,Chambres non-fumeurs,Équipements pour les personnes handicapées,NaN,NaN,NaN,NaN,NaN
2,20,Coup de Cœur VIEUX PORT-République,43.298031,5.372932,9.6,L’hébergement Coup de Cœur VIEUX PORT-Républiq...,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Réception ouverte 24h/24,Terrasse,Chauffage,NaN,NaN,NaN,NaN,NaN
3,18,"Bord de mer, charmant studio entièrement équipé",43.126023,6.358852,9.4,"L’hébergement Bord de mer, charmant studio ent...",Parking gratuit,Connexion Wi-Fi gratuite,Chambres non-fumeurs,***,***,NaN,NaN,NaN,NaN,NaN
4,20,"Maison vue Mer, Marseille.",43.354912,5.333493,9.5,"Offrant une vue sur la ville, l’hébergement Ma...",Connexion Wi-Fi gratuite,Terrasse,***,***,Machine à café,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,34,** Studio cosy La Rochelle quartier des Minime...,46.140106,-1.161035,9.1,L’hébergement en bord de mer ** Studio cosy La...,Parking gratuit,Connexion Wi-Fi gratuite,En bord de plage,Chambres non-fumeurs,***,NaN,NaN,NaN,NaN,NaN
246,34,Le Petit Caillebotis,46.142908,-1.156299,9.0,L’hébergement Le Petit Caillebotis se situe à ...,Parking gratuit,Chambres familiales,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Terrasse,NaN,NaN,NaN,NaN,NaN
247,34,Hôtel Kyriad La Rochelle Centre Ville,46.157796,-1.138319,8.4,L’Hôtel Kyriad La Rochelle Centre Ville vous a...,Parking privé,Chambres familiales,Connexion Wi-Fi gratuite,Restaurant,Chambres non-fumeurs,NaN,NaN,NaN,NaN,NaN
248,19,Le Nadadou par Dodo à Cassis,43.213317,5.549367,8.4,L’hébergement Le Nadadou par Dodo à Cassis pro...,Parking gratuit,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Terrasse,Jardin,NaN,NaN,NaN,NaN,NaN
249,21,Odalys City Aix en Provence Les Floridianes,43.521333,5.444777,8.0,L'Odalys City Aix en Provence Les Floridianes ...,Piscine extérieure,Parking privé,Connexion Wi-Fi gratuite,Chambres familiales,Chambres non-fumeurs,NaN,NaN,NaN,NaN,NaN

In [33]:
#To Launch
#result = pd.read_csv('best_town_rating_final.csv')
result['hotel_description_hover'] = result.apply(lambda row: f"{row['hotel_description'][:100]}...", axis=1)

/var/folders/mk/k32g1gsn4c1_yd1vbqdbpvw00000gn/T/ipykernel_6608/3062512733.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [34]:
import textwrap

# Fonction pour insérer des <br> toutes les 40 lettres
def wrap_text(text, width=40):
    if pd.isna(text):  # Vérifie si le texte est vide
        return ""
    wrapped = textwrap.wrap(text, width=width)
    return "".join(wrapped)  # Utilise <br> pour les sauts de ligne HTML

# Applique cette fonction à la colonne 'hotel_description'
result['hotel_description_hover_1'] = result['hotel_description'].apply(wrap_text, width=40)

/var/folders/mk/k32g1gsn4c1_yd1vbqdbpvw00000gn/T/ipykernel_6608/3848135676.py:11: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [35]:
result['hotel_description_hover'] = result['hotel_description'].apply(
    lambda x: '<br>'.join(textwrap.wrap(str(x), width=50))
)

/var/folders/mk/k32g1gsn4c1_yd1vbqdbpvw00000gn/T/ipykernel_6608/1111653325.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [36]:
result

,Id,hotel_name,hotel_lat,hotel_long,hotel_rating,hotel_description,hotel_facilities,hotel_facilities_1,hotel_facilities_2,hotel_facilities_3,hotel_facilities_4,towns,town_lat,town_long,temperature_forecast,weather_forecast,hotel_description_hover,hotel_description_hover_1
0,20,easyHotel Marseille Euromed,43.310115,5.370340,8.5,L’établissement easyHotel Marseille Euromed bé...,Connexion Wi-Fi gratuite,Équipements pour les personnes handicapées,Réception ouverte 24h/24,Ascenseur,Chauffage,NaN,NaN,NaN,NaN,NaN,L’établissement easyHotel Marseille Euromed<br...,L’établissement easyHotel MarseilleEuromed bén...
1,20,Staycity Aparthotels Marseille Centre Vieux Port,43.300466,5.374442,8.4,"Doté d'une connexion Wi-Fi gratuite, le Stayci...",Parking,Connexion Wi-Fi gratuite,Chambres familiales,Chambres non-fumeurs,Équipements pour les personnes handicapées,NaN,NaN,NaN,NaN,NaN,"Doté d'une connexion Wi-Fi gratuite, le Stayci...","Doté d'une connexion Wi-Fi gratuite, leStaycit..."
2,20,Coup de Cœur VIEUX PORT-République,43.298031,5.372932,9.6,L’hébergement Coup de Cœur VIEUX PORT-Républiq...,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Réception ouverte 24h/24,Terrasse,Chauffage,NaN,NaN,NaN,NaN,NaN,L’hébergement Coup de Cœur VIEUX PORT-Républiq...,L’hébergement Coup de Cœur VIEUX PORT-Républiq...
3,18,"Bord de mer, charmant studio entièrement équipé",43.126023,6.358852,9.4,"L’hébergement Bord de mer, charmant studio ent...",Parking gratuit,Connexion Wi-Fi gratuite,Chambres non-fumeurs,***,***,NaN,NaN,NaN,NaN,NaN,"L’hébergement Bord de mer, charmant studio<br>...","L’hébergement Bord de mer, charmantstudio enti..."
4,20,"Maison vue Mer, Marseille.",43.354912,5.333493,9.5,"Offrant une vue sur la ville, l’hébergement Ma...",Connexion Wi-Fi gratuite,Terrasse,***,***,Machine à café,NaN,NaN,NaN,NaN,NaN,"Offrant une vue sur la ville, l’hébergement Ma...","Offrant une vue sur la ville,l’hébergement Mai..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,34,** Studio cosy La Rochelle quartier des Minime...,46.140106,-1.161035,9.1,L’hébergement en bord de mer ** Studio cosy La...,Parking gratuit,Connexion Wi-Fi gratuite,En bord de plage,Chambres non-fumeurs,***,NaN,NaN,NaN,NaN,NaN,L’hébergement en bord de mer ** Studio cosy La...,L’hébergement en bord de mer ** Studiocosy La ...
246,34,Le Petit Caillebotis,46.142908,-1.156299,9.0,L’hébergement Le Petit Caillebotis se situe à ...,Parking gratuit,Chambres familiales,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Terrasse,NaN,NaN,NaN,NaN,NaN,L’hébergement Le Petit Caillebotis se situe à ...,L’hébergement Le Petit Caillebotis sesitue à L...
247,34,Hôtel Kyriad La Rochelle Centre Ville,46.157796,-1.138319,8.4,L’Hôtel Kyriad La Rochelle Centre Ville vous a...,Parking privé,Chambres familiales,Connexion Wi-Fi gratuite,Restaurant,Chambres non-fumeurs,NaN,NaN,NaN,NaN,NaN,L’Hôtel Kyriad La Rochelle Centre Ville vous<b...,L’Hôtel Kyriad La Rochelle Centre Villevous ac...
248,19,Le Nadadou par Dodo à Cassis,43.213317,5.549367,8.4,L’hébergement Le Nadadou par Dodo à Cassis pro...,Parking gratuit,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Terrasse,Jardin,NaN,NaN,NaN,NaN,NaN,L’hébergement Le Nadadou par Dodo à Cassis pro...,L’hébergement Le Nadadou par Dodo àCassis prop...
249,21,Odalys City Aix en Provence Les Floridianes,43.521333,5.444777,8.0,L'Odalys City Aix en Provence Les Floridianes ...,Piscine extérieure,Parking privé,Connexion Wi-Fi gratuite,Chambres familiales,Chambres non-fumeurs,NaN,NaN,NaN,NaN,NaN,L'Odalys City Aix en Provence Les Floridianes ...,L'Odalys City Aix en Provence LesFloridianes v...

In [37]:
# Dictionnaire d'emojis
facilities_emoji_map = {
    "Ascenceur" : "🛗",
    "Connexion Wi-Fi gratuite": "📶",
    "Restaurant": "🍽",
    "Parking gratuit" : "🚗",
    "Parking": "🚗",
    "Parking privé": "🚗",
    "Réception ouverte 24h/24" : "🕚",
    "En bord de plage": "🏖",
    "Chambres non-fumeurs":"🚭",
    "Terrasse": "🩴",
    "Jardin" : "🌱",
    "Chambres familiales": "👨‍👩‍👧‍👦",
    "Table à manger": "🍽️",
    "Piscine extérieure" : "🏊",
    "Machine à café": "☕"
}

# --- ÉTAPE 1 : Définir la liste des colonnes d'équipements ---
facility_cols = ['hotel_facilities', 'hotel_facilities_1', 'hotel_facilities_2', 'hotel_facilities_3', 'hotel_facilities_4']

# --- ÉTAPE 2 : Créer la fonction qui traite une SEULE LIGNE ---
def format_facilities_from_row(row, columns_to_check, emoji_map):
    """
    Prend une ligne de DataFrame, vérifie les colonnes d'équipements,
    et retourne une chaîne HTML formatée.
    """
    formatted_list = []
    for col in columns_to_check:
        facility_name = row[col]
        # On vérifie que la valeur n'est pas nulle/NaN avant de continuer
        if pd.notna(facility_name):
            emoji = emoji_map.get(facility_name, '✅') # Emoji par défaut si non trouvé
            formatted_list.append(f"{emoji} {facility_name}")
            
    return "<br>".join(formatted_list)

# --- ÉTAPE 3 : Appliquer la fonction à chaque ligne pour créer la nouvelle colonne ---
result['facilities_html'] = result.apply(
    lambda row: format_facilities_from_row(row, facility_cols, facilities_emoji_map),
    axis=1
)

/var/folders/mk/k32g1gsn4c1_yd1vbqdbpvw00000gn/T/ipykernel_6608/1083407668.py:40: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [38]:
result

,Id,hotel_name,hotel_lat,hotel_long,hotel_rating,hotel_description,hotel_facilities,hotel_facilities_1,hotel_facilities_2,hotel_facilities_3,hotel_facilities_4,towns,town_lat,town_long,temperature_forecast,weather_forecast,hotel_description_hover,hotel_description_hover_1,facilities_html
0,20,easyHotel Marseille Euromed,43.310115,5.370340,8.5,L’établissement easyHotel Marseille Euromed bé...,Connexion Wi-Fi gratuite,Équipements pour les personnes handicapées,Réception ouverte 24h/24,Ascenseur,Chauffage,NaN,NaN,NaN,NaN,NaN,L’établissement easyHotel Marseille Euromed<br...,L’établissement easyHotel MarseilleEuromed bén...,📶 Connexion Wi-Fi gratuite<br>✅ Équipements po...
1,20,Staycity Aparthotels Marseille Centre Vieux Port,43.300466,5.374442,8.4,"Doté d'une connexion Wi-Fi gratuite, le Stayci...",Parking,Connexion Wi-Fi gratuite,Chambres familiales,Chambres non-fumeurs,Équipements pour les personnes handicapées,NaN,NaN,NaN,NaN,NaN,"Doté d'une connexion Wi-Fi gratuite, le Stayci...","Doté d'une connexion Wi-Fi gratuite, leStaycit...",🚗 Parking<br>📶 Connexion Wi-Fi gratuite<br>👨‍👩...
2,20,Coup de Cœur VIEUX PORT-République,43.298031,5.372932,9.6,L’hébergement Coup de Cœur VIEUX PORT-Républiq...,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Réception ouverte 24h/24,Terrasse,Chauffage,NaN,NaN,NaN,NaN,NaN,L’hébergement Coup de Cœur VIEUX PORT-Républiq...,L’hébergement Coup de Cœur VIEUX PORT-Républiq...,📶 Connexion Wi-Fi gratuite<br>🚭 Chambres non-f...
3,18,"Bord de mer, charmant studio entièrement équipé",43.126023,6.358852,9.4,"L’hébergement Bord de mer, charmant studio ent...",Parking gratuit,Connexion Wi-Fi gratuite,Chambres non-fumeurs,***,***,NaN,NaN,NaN,NaN,NaN,"L’hébergement Bord de mer, charmant studio<br>...","L’hébergement Bord de mer, charmantstudio enti...",🚗 Parking gratuit<br>📶 Connexion Wi-Fi gratuit...
4,20,"Maison vue Mer, Marseille.",43.354912,5.333493,9.5,"Offrant une vue sur la ville, l’hébergement Ma...",Connexion Wi-Fi gratuite,Terrasse,***,***,Machine à café,NaN,NaN,NaN,NaN,NaN,"Offrant une vue sur la ville, l’hébergement Ma...","Offrant une vue sur la ville,l’hébergement Mai...",📶 Connexion Wi-Fi gratuite<br>🩴 Terrasse<br>✅ ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,34,** Studio cosy La Rochelle quartier des Minime...,46.140106,-1.161035,9.1,L’hébergement en bord de mer ** Studio cosy La...,Parking gratuit,Connexion Wi-Fi gratuite,En bord de plage,Chambres non-fumeurs,***,NaN,NaN,NaN,NaN,NaN,L’hébergement en bord de mer ** Studio cosy La...,L’hébergement en bord de mer ** Studiocosy La ...,🚗 Parking gratuit<br>📶 Connexion Wi-Fi gratuit...
246,34,Le Petit Caillebotis,46.142908,-1.156299,9.0,L’hébergement Le Petit Caillebotis se situe à ...,Parking gratuit,Chambres familiales,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Terrasse,NaN,NaN,NaN,NaN,NaN,L’hébergement Le Petit Caillebotis se situe à ...,L’hébergement Le Petit Caillebotis sesitue à L...,🚗 Parking gratuit<br>👨‍👩‍👧‍👦 Chambres familial...
247,34,Hôtel Kyriad La Rochelle Centre Ville,46.157796,-1.138319,8.4,L’Hôtel Kyriad La Rochelle Centre Ville vous a...,Parking privé,Chambres familiales,Connexion Wi-Fi gratuite,Restaurant,Chambres non-fumeurs,NaN,NaN,NaN,NaN,NaN,L’Hôtel Kyriad La Rochelle Centre Ville vous<b...,L’Hôtel Kyriad La Rochelle Centre Villevous ac...,🚗 Parking privé<br>👨‍👩‍👧‍👦 Chambres familiales...
248,19,Le Nadadou par Dodo à Cassis,43.213317,5.549367,8.4,L’hébergement Le Nadadou par Dodo à Cassis pro...,Parking gratuit,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Terrasse,Jardin,NaN,NaN,NaN,NaN,NaN,L’hébergement Le Nadadou par Dodo à Cassis pro...,L’hébergement Le Nadadou par Dodo àCassis prop...,🚗 Parking gratuit<br>📶 Connexion Wi-Fi gratuit...
249,21,Odalys City Aix en Provence Les Floridianes,43.521333,5.444777,8.0,L'Odalys City Aix en Provence Les Floridianes ...,Piscine extérieure,Parking privé,Connexion Wi-Fi gratuite,Chambres familiales,Chambres non-fumeurs,NaN,NaN,NaN,NaN,NaN,L'Odalys City Aix en Provence Les Floridianes ...,L'Odalys City Aix en Provence LesFloridianes v...,🏊 Piscine extérieure<br>🚗 Parking privé<br>📶 C...

In [39]:
# Scatter plot des températures
fig = px.scatter_mapbox(
    hotel_gps_forecast,
    lat='town_lat',
    lon='town_long',
    color='temperature_forecast',
    hover_name="towns",
    zoom=5,
    labels={'temperature_forecast': 'Temperature Forecast'},
    size="temperature_forecast",
    size_max=20,
    width=1000,
    height=800,
    opacity=0.8
)

# Nommer correctement la trace des températures
fig.data[0].name = "Temperature Forecast"

# Mise à jour du hovertemplate pour les villes
fig.update_traces(
    selector=dict(name="Temperature Forecast"),
    customdata=hotel_gps_forecast[['weather_forecast', 'temperature_forecast']],
    hovertemplate="<b>%{hovertext}</b><br>" +
                  "<span style='font-size:10px;'>&#127759;</span> <i>Weather : <b>%{customdata[0]}</b></i><br>" + 
                  "<span style='font-size:10px;'> 🌡️</span> <i>Temperature : <b>%{customdata[1]}</b></i><br>"
)

# Modifier l'apparence de la carte
fig.update_layout(
    coloraxis_colorbar=dict(title="Temperature Forecast"),
    mapbox_style="carto-positron",
    title="Les coins où la température est la plus douce au 8 février (prévision d'une semaine)",
    margin={"r":40, "t":70, "l":40, "b":20},
    height=800,
    width=1400,
    # Déplacer la légende
    legend=dict(
        yanchor="top",
        y=0.99,
        xanchor="left",
        x=0.01,
        bgcolor="rgba(255, 255, 255, 0.01)",
        bordercolor="black",
        borderwidth=1
    )
)


# Affichage final
fig.show()

In [40]:
import plotly.graph_objects as go
# Création de la figure
fig = go.Figure()

# --- TRACE N°1 : LES POINTS VISUELS (SANS HOVER) ---
# Cette trace dessine les points colorés, mais ne réagit pas au survol.
fig.add_trace(go.Scattermapbox(
    lat=result["hotel_lat"],
    lon=result["hotel_long"],
    mode='markers',
    hoverinfo='none', # Très important : désactive le hover pour cette trace
    marker=dict(
        size=result["hotel_rating"].apply(lambda x: (x - 8) * 8 + 8),
        sizemode='diameter',
        sizeref=1.2,
        color=result["hotel_rating"],
        colorscale="YlOrRd",
        cmin=8, cmax=10,
        showscale=True,
        colorbar=dict(title="Note Hôtel"),
        opacity=0.8
    )
))

# --- TRACE N°2 : LES POINTS INTERACTIFS (INVISIBLES) ---
# Cette trace est invisible mais gère l'affichage de l'infobulle.
fig.add_trace(go.Scattermapbox(
    lat=result["hotel_lat"],
    lon=result["hotel_long"],
    mode='markers',
    text=result["hotel_name"],
    customdata=result[['hotel_description_hover', 'hotel_rating', 'facilities_html']],
    
    # Le marqueur est invisible et n'a pas de couleur variable
    marker=dict(
        size=result["hotel_rating"].apply(lambda x: (x - 8) * 8 + 8), # Même taille que la trace visuelle
        sizemode='diameter',
        sizeref=1.2,
        color='rgba(0,0,0,0)', # Couleur transparente
        opacity=0 # Complètement invisible
    ),
    
    # Votre hovertemplate est ici, dans la trace qui n'a pas de couleur.
    hovertemplate=(
        "<span style='font-size:16px; font-weight:bold; color:#1f1f1f;'>%{text}</span><br>" +
        "<span style='font-size:14px; color:#666;'>⭐ <i>Rating</i>: <b>%{customdata[1]}</b></span><br>" +
        "<span style='font-size:12px; color:#333;'>🏨 %{customdata[0]}</span><br>" +
        # Le contenu de <extra> n'héritera plus de la couleur du point.
        "<extra>" +
        "<b>Popular facilities</b><br>" + # Titre simplifié pour meilleure lisibilité
        "<span style='"
            "background-color:#f8f8f8; "
            "border-radius:6px; "
            "padding:8px; "
            "font-size:12px; "
            "color:#111; " # Cette couleur sera maintenant respectée !
            "display:block; "
            "margin-top:4px;"
            "'>%{customdata[2]}</span>" +
        "</extra>"
    ),
    
    hoverlabel=dict(
        bgcolor="rgba(240, 240, 240, 0.98)",
        font_size=13,
        font_family="Arial, sans-serif",
        bordercolor="#ddd",
    )
))

# Modifier l'apparence générale de la carte
fig.update_layout(
    mapbox_style="carto-positron",
    title="Carte des Meilleurs Hôtels en France dans les régions les plus chaudes",
    margin={"r":20, "t":60, "l":20, "b":20},
    height=800,
    width=1400,
    mapbox=dict(
        center=dict(lat=46.603354, lon=1.888334),
        zoom=4.5
    ),
    showlegend=False # Cache la légende pour les deux traces
)

# Affichage final
fig.show()

In [41]:
import plotly.express as px
import plotly.graph_objects as go


# Scatter plot des températures
fig = px.scatter_mapbox(
    hotel_gps_forecast,
    lat='town_lat',
    lon='town_long',
    color='temperature_forecast',
    hover_name="towns",
    zoom=5,
    labels={'temperature_forecast': 'Temperature Forecast'},
    size="temperature_forecast",
    size_max=20,
    width=1000,
    height=800,
    opacity=0.8
)

# Nommer correctement la trace des températures
fig.data[0].name = "Temperature Forecast"

# Mise à jour du hovertemplate pour les villes
fig.update_traces(
    selector=dict(name="Temperature Forecast"),
    customdata=hotel_gps_forecast[['weather_forecast', 'temperature_forecast']],
    hovertemplate="<b>%{hovertext}</b><br>" +
                  "<span style='font-size:10px;'>&#127759;</span> <i>Weather : <b>%{customdata[0]}</b></i><br>" + 
                  "<span style='font-size:10px;'> 🌡️</span> <i>Temperature : <b>%{customdata[1]}</b></i><br>"
)

# Scatter plot des hôtels
hotel_trace = go.Scattermapbox(
    lat=result["hotel_lat"],
    lon=result["hotel_long"],
    text=result["hotel_name"],
    customdata=result[['hotel_description_hover', 'hotel_rating', 'facilities_html']],
    marker=dict(
        size=5,
        color='red',
        showscale=False,
        sizemode='area',
        sizeref=10
    ),
    hovertemplate=(
        "<span style='font-size:16px; font-weight:bold; color:#1f1f1f;'>%{text}</span><br>" +  # Titre en gras, noir
        "<span style='font-size:14px; color:#666;'>⭐ <i>Rating</i>: <b>%{customdata[1]}</b></span><br>" +  # Sous-titre en gris moyen
        "<span style='font-size:12px; color:#333;'>🏨 %{customdata[0]}</span><br>" +  # Description en gris foncé
        "<extra>" +
        "<span style='font-size:14px; color:#007bff;'>✅</span> <b>Popular facilities</b><br>" +  # Icône verte, titre Facilities en bleu
        "<span style='"
            "background-color:#f8f8f8; "
            "border-radius:6px; "
            "padding:8px; "
            "font-size:12px; "
            "color:#111; "
            "display:block; "
            "margin-top:4px;"
            "'>%{customdata[2]}</span>" +
        "</extra>"
    ),
    name="<b>Hotels</b> with rating > <b>8/10</b>",
    
    # === Fond général du hover ===
    hoverlabel=dict(
        bgcolor="rgba(240, 240, 240, 0.98)",   # Fond global très clair
        font_size=13,
        font_family="Arial, sans-serif",
        bordercolor="#ddd",
       # borderwidth=1
    )
)

# Mise à jour du hovertemplate pour les hôtels
fig.update_traces(
    selector=dict(name="<b>Hotels</b> with rating > <b>8/10</b>"),
)

# Ajouter les hôtels à la carte
fig.add_trace(hotel_trace)

# Modifier l'apparence de la carte
fig.update_layout(
    coloraxis_colorbar=dict(title="Temperature Forecast"),
    mapbox_style="carto-positron",
    title="Meilleurs ⭐ Hotels au soleil 🌞 & Prévision de température pour la semaine prochaine au 8 février",
    margin={"r":40, "t":70, "l":40, "b":20},
    height=800,
    width=1400,
    # Déplacer la légende
    legend=dict(
        yanchor="top",
        y=0.99,
        xanchor="left",
        x=0.01,
        bgcolor="rgba(255, 255, 255, 0.01)",
        bordercolor="black",
        borderwidth=1
    )
)

# Affichage final
fig.show()

In [42]:
df1 = pd.read_json('ten_hotels_town_id_facilitie_f.json', lines=True)

In [43]:
hotel_gps_forecast1 = pd.read_csv('Town_Geo_Forcast.csv')
hotel_gps_forecast1 = hotel_gps_forecast1.drop('Unnamed: 0', axis = 1)
hotel_gps_forecast1

,Id,Towns,Latitude,Longitude,temperature_forcast,weather_forcast
0,0,Mont Saint-Michel,48.635954,-1.511460,8,Clouds
1,1,Saint-Malo,48.649518,-2.026041,12,Clouds
2,2,Bayeux,49.276462,-0.702474,9,Clouds
3,3,Le Havre,49.493898,0.107973,10,Clouds
4,4,Rouen,49.440459,1.093966,5,Clouds
5,5,Paris,48.858890,2.320041,2,Clouds
6,6,Amiens,49.894171,2.295695,3,Clear
7,7,Lille,50.636565,3.063528,2,Clouds
8,8,Strasbourg,48.584614,7.750713,1,Clear
9,9,Château du Haut-Kœnigsbourg,48.249411,7.344320,0,Clear
10,10,Colmar,48.077752,7.357964,3,Clear
11,11,Eguisheim,48.044797,7.307962,3,Clear
12,12,Besançon,47.238022,6.024362,0,Clear
13,13,Dijon,47.321581,5.041470,1,Clouds
14,14,Annecy,45.899235,6.128885,5,Clear
15,15,Grenoble,45.187560,5.735782,4,Clear
16,16,Lyon,45.757814,4.832011,2,Clouds
17,17,Gorges du Verdon,43.749656,6.328562,7,Clear
18,18,Bormes-les-Mimosas,43.150697,6.341928,12,Clear
19,19,Cassis,43.214036,5.539632,12,Clear
20,20,Marseille,43.296174,5.369953,13,Clear
21,21,Aix-en-Provence,43.529842,5.447474,11,Clear
22,22,Avignon,43.949249,4.805901,9,Clear
23,23,Uzès,44.012128,4.419672,7,Clear
24,24,Nîmes,43.837425,4.360069,10,Clear
25,25,Aigues-Mortes,43.566152,4.191540,10,Clear
26,26,Saintes-Maries-de-la-Mer,43.451592,4.427720,10,Clear
27,27,Collioure,42.525050,3.083155,11,Clear
28,28,Carcassonne,43.213036,2.349107,13,Clear
29,29,Ariège,42.945537,1.406554,2,Clear
30,30,Toulouse,43.604462,1.444247,13,Clear
31,31,Montauban,44.017584,1.354999,7,Clear
32,32,Biarritz,43.471144,-1.552727,12,Clear
33,33,Bayonne,43.494514,-1.473666,12,Clear
34,34,La Rochelle,46.159732,-1.151595,11,Clear

In [44]:
hotel_gps_forecast1 = hotel_gps_forecast1.rename(columns={'Towns' : 'towns',
                                'Latitude' : 'town_lat',
                                'Longitude' : 'town_long',
                                'temperature_forcast' : 'temperature_forecast',
                                'weather_forcast' : 'weather_forecast'})

In [45]:
result1 = pd.merge(df1, hotel_gps_forecast1, on="Id")

In [46]:
result1

,Id,hotel_name,hotel_lat,hotel_long,hotel_rating,hotel_description,hotel_facilities,hotel_facilities_1,hotel_facilities_2,hotel_facilities_3,hotel_facilities_4,towns,town_lat,town_long,temperature_forecast,weather_forecast
0,20,easyHotel Marseille Euromed,43.310115,5.370340,"8,5",L’établissement easyHotel Marseille Euromed bé...,Connexion Wi-Fi gratuite,Équipements pour les personnes handicapées,Réception ouverte 24h/24,Ascenseur,Chauffage,Marseille,43.296174,5.369953,13,Clear
1,20,Staycity Aparthotels Marseille Centre Vieux Port,43.300466,5.374442,"8,4","Doté d'une connexion Wi-Fi gratuite, le Stayci...",Parking,Connexion Wi-Fi gratuite,Chambres familiales,Chambres non-fumeurs,Équipements pour les personnes handicapées,Marseille,43.296174,5.369953,13,Clear
2,20,Coup de Cœur VIEUX PORT-République,43.298031,5.372932,"9,6",L’hébergement Coup de Cœur VIEUX PORT-Républiq...,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Réception ouverte 24h/24,Terrasse,Chauffage,Marseille,43.296174,5.369953,13,Clear
3,18,"Bord de mer, charmant studio entièrement équipé",43.126023,6.358852,"9,4","L’hébergement Bord de mer, charmant studio ent...",Parking gratuit,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Parking gratuit,Connexion Wi-Fi gratuite,Bormes-les-Mimosas,43.150697,6.341928,12,Clear
4,20,"Maison vue Mer, Marseille.",43.354912,5.333493,"9,5","Offrant une vue sur la ville, l’hébergement Ma...",Connexion Wi-Fi gratuite,Terrasse,Connexion Wi-Fi gratuite,Terrasse,Machine à café,Marseille,43.296174,5.369953,13,Clear
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,34,** Studio cosy La Rochelle quartier des Minime...,46.140106,-1.161035,"9,1",L’hébergement en bord de mer ** Studio cosy La...,Parking gratuit,Connexion Wi-Fi gratuite,En bord de plage,Chambres non-fumeurs,Parking gratuit,La Rochelle,46.159732,-1.151595,11,Clear
246,34,Le Petit Caillebotis,46.142908,-1.156299,"9,0",L’hébergement Le Petit Caillebotis se situe à ...,Parking gratuit,Chambres familiales,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Terrasse,La Rochelle,46.159732,-1.151595,11,Clear
247,34,Hôtel Kyriad La Rochelle Centre Ville,46.157796,-1.138319,"8,4",L’Hôtel Kyriad La Rochelle Centre Ville vous a...,Parking privé,Chambres familiales,Connexion Wi-Fi gratuite,Restaurant,Chambres non-fumeurs,La Rochelle,46.159732,-1.151595,11,Clear
248,19,Le Nadadou par Dodo à Cassis,43.213317,5.549367,"8,4",L’hébergement Le Nadadou par Dodo à Cassis pro...,Parking gratuit,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Terrasse,Jardin,Cassis,43.214036,5.539632,12,Clear
249,21,Odalys City Aix en Provence Les Floridianes,43.521333,5.444777,"8,0",L'Odalys City Aix en Provence Les Floridianes ...,Piscine extérieure,Parking privé,Connexion Wi-Fi gratuite,Chambres familiales,Chambres non-fumeurs,Aix-en-Provence,43.529842,5.447474,11,Clear

In [47]:
result1= result1[result1["hotel_rating"].notnull()]

In [48]:
result1

,Id,hotel_name,hotel_lat,hotel_long,hotel_rating,hotel_description,hotel_facilities,hotel_facilities_1,hotel_facilities_2,hotel_facilities_3,hotel_facilities_4,towns,town_lat,town_long,temperature_forecast,weather_forecast
0,20,easyHotel Marseille Euromed,43.310115,5.370340,"8,5",L’établissement easyHotel Marseille Euromed bé...,Connexion Wi-Fi gratuite,Équipements pour les personnes handicapées,Réception ouverte 24h/24,Ascenseur,Chauffage,Marseille,43.296174,5.369953,13,Clear
1,20,Staycity Aparthotels Marseille Centre Vieux Port,43.300466,5.374442,"8,4","Doté d'une connexion Wi-Fi gratuite, le Stayci...",Parking,Connexion Wi-Fi gratuite,Chambres familiales,Chambres non-fumeurs,Équipements pour les personnes handicapées,Marseille,43.296174,5.369953,13,Clear
2,20,Coup de Cœur VIEUX PORT-République,43.298031,5.372932,"9,6",L’hébergement Coup de Cœur VIEUX PORT-Républiq...,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Réception ouverte 24h/24,Terrasse,Chauffage,Marseille,43.296174,5.369953,13,Clear
3,18,"Bord de mer, charmant studio entièrement équipé",43.126023,6.358852,"9,4","L’hébergement Bord de mer, charmant studio ent...",Parking gratuit,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Parking gratuit,Connexion Wi-Fi gratuite,Bormes-les-Mimosas,43.150697,6.341928,12,Clear
4,20,"Maison vue Mer, Marseille.",43.354912,5.333493,"9,5","Offrant une vue sur la ville, l’hébergement Ma...",Connexion Wi-Fi gratuite,Terrasse,Connexion Wi-Fi gratuite,Terrasse,Machine à café,Marseille,43.296174,5.369953,13,Clear
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,34,** Studio cosy La Rochelle quartier des Minime...,46.140106,-1.161035,"9,1",L’hébergement en bord de mer ** Studio cosy La...,Parking gratuit,Connexion Wi-Fi gratuite,En bord de plage,Chambres non-fumeurs,Parking gratuit,La Rochelle,46.159732,-1.151595,11,Clear
246,34,Le Petit Caillebotis,46.142908,-1.156299,"9,0",L’hébergement Le Petit Caillebotis se situe à ...,Parking gratuit,Chambres familiales,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Terrasse,La Rochelle,46.159732,-1.151595,11,Clear
247,34,Hôtel Kyriad La Rochelle Centre Ville,46.157796,-1.138319,"8,4",L’Hôtel Kyriad La Rochelle Centre Ville vous a...,Parking privé,Chambres familiales,Connexion Wi-Fi gratuite,Restaurant,Chambres non-fumeurs,La Rochelle,46.159732,-1.151595,11,Clear
248,19,Le Nadadou par Dodo à Cassis,43.213317,5.549367,"8,4",L’hébergement Le Nadadou par Dodo à Cassis pro...,Parking gratuit,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Terrasse,Jardin,Cassis,43.214036,5.539632,12,Clear
249,21,Odalys City Aix en Provence Les Floridianes,43.521333,5.444777,"8,0",L'Odalys City Aix en Provence Les Floridianes ...,Piscine extérieure,Parking privé,Connexion Wi-Fi gratuite,Chambres familiales,Chambres non-fumeurs,Aix-en-Provence,43.529842,5.447474,11,Clear

In [49]:
result1['hotel_rating'] = result1['hotel_rating'].apply(lambda x: x.replace(',', '.')).apply(pd.to_numeric)

/var/folders/mk/k32g1gsn4c1_yd1vbqdbpvw00000gn/T/ipykernel_6608/1029904260.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [50]:
result1

,Id,hotel_name,hotel_lat,hotel_long,hotel_rating,hotel_description,hotel_facilities,hotel_facilities_1,hotel_facilities_2,hotel_facilities_3,hotel_facilities_4,towns,town_lat,town_long,temperature_forecast,weather_forecast
0,20,easyHotel Marseille Euromed,43.310115,5.370340,8.5,L’établissement easyHotel Marseille Euromed bé...,Connexion Wi-Fi gratuite,Équipements pour les personnes handicapées,Réception ouverte 24h/24,Ascenseur,Chauffage,Marseille,43.296174,5.369953,13,Clear
1,20,Staycity Aparthotels Marseille Centre Vieux Port,43.300466,5.374442,8.4,"Doté d'une connexion Wi-Fi gratuite, le Stayci...",Parking,Connexion Wi-Fi gratuite,Chambres familiales,Chambres non-fumeurs,Équipements pour les personnes handicapées,Marseille,43.296174,5.369953,13,Clear
2,20,Coup de Cœur VIEUX PORT-République,43.298031,5.372932,9.6,L’hébergement Coup de Cœur VIEUX PORT-Républiq...,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Réception ouverte 24h/24,Terrasse,Chauffage,Marseille,43.296174,5.369953,13,Clear
3,18,"Bord de mer, charmant studio entièrement équipé",43.126023,6.358852,9.4,"L’hébergement Bord de mer, charmant studio ent...",Parking gratuit,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Parking gratuit,Connexion Wi-Fi gratuite,Bormes-les-Mimosas,43.150697,6.341928,12,Clear
4,20,"Maison vue Mer, Marseille.",43.354912,5.333493,9.5,"Offrant une vue sur la ville, l’hébergement Ma...",Connexion Wi-Fi gratuite,Terrasse,Connexion Wi-Fi gratuite,Terrasse,Machine à café,Marseille,43.296174,5.369953,13,Clear
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,34,** Studio cosy La Rochelle quartier des Minime...,46.140106,-1.161035,9.1,L’hébergement en bord de mer ** Studio cosy La...,Parking gratuit,Connexion Wi-Fi gratuite,En bord de plage,Chambres non-fumeurs,Parking gratuit,La Rochelle,46.159732,-1.151595,11,Clear
246,34,Le Petit Caillebotis,46.142908,-1.156299,9.0,L’hébergement Le Petit Caillebotis se situe à ...,Parking gratuit,Chambres familiales,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Terrasse,La Rochelle,46.159732,-1.151595,11,Clear
247,34,Hôtel Kyriad La Rochelle Centre Ville,46.157796,-1.138319,8.4,L’Hôtel Kyriad La Rochelle Centre Ville vous a...,Parking privé,Chambres familiales,Connexion Wi-Fi gratuite,Restaurant,Chambres non-fumeurs,La Rochelle,46.159732,-1.151595,11,Clear
248,19,Le Nadadou par Dodo à Cassis,43.213317,5.549367,8.4,L’hébergement Le Nadadou par Dodo à Cassis pro...,Parking gratuit,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Terrasse,Jardin,Cassis,43.214036,5.539632,12,Clear
249,21,Odalys City Aix en Provence Les Floridianes,43.521333,5.444777,8.0,L'Odalys City Aix en Provence Les Floridianes ...,Piscine extérieure,Parking privé,Connexion Wi-Fi gratuite,Chambres familiales,Chambres non-fumeurs,Aix-en-Provence,43.529842,5.447474,11,Clear

In [51]:
result1.loc[result1['hotel_facilities_2'] == result1['hotel_facilities'], 'hotel_facilities_2'] = 'not available'
result1.loc[result1['hotel_facilities_3'] == result1['hotel_facilities'], 'hotel_facilities_3'] = 'not available'
result1.loc[result1['hotel_facilities_4'] == result1['hotel_facilities'], 'hotel_facilities_4'] = 'not available'
result1.loc[result1['hotel_facilities_4'] == result1['hotel_facilities_3'], 'hotel_facilities_4'] = 'not available'

In [52]:
result1

,Id,hotel_name,hotel_lat,hotel_long,hotel_rating,hotel_description,hotel_facilities,hotel_facilities_1,hotel_facilities_2,hotel_facilities_3,hotel_facilities_4,towns,town_lat,town_long,temperature_forecast,weather_forecast
0,20,easyHotel Marseille Euromed,43.310115,5.370340,8.5,L’établissement easyHotel Marseille Euromed bé...,Connexion Wi-Fi gratuite,Équipements pour les personnes handicapées,Réception ouverte 24h/24,Ascenseur,Chauffage,Marseille,43.296174,5.369953,13,Clear
1,20,Staycity Aparthotels Marseille Centre Vieux Port,43.300466,5.374442,8.4,"Doté d'une connexion Wi-Fi gratuite, le Stayci...",Parking,Connexion Wi-Fi gratuite,Chambres familiales,Chambres non-fumeurs,Équipements pour les personnes handicapées,Marseille,43.296174,5.369953,13,Clear
2,20,Coup de Cœur VIEUX PORT-République,43.298031,5.372932,9.6,L’hébergement Coup de Cœur VIEUX PORT-Républiq...,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Réception ouverte 24h/24,Terrasse,Chauffage,Marseille,43.296174,5.369953,13,Clear
3,18,"Bord de mer, charmant studio entièrement équipé",43.126023,6.358852,9.4,"L’hébergement Bord de mer, charmant studio ent...",Parking gratuit,Connexion Wi-Fi gratuite,Chambres non-fumeurs,not available,Connexion Wi-Fi gratuite,Bormes-les-Mimosas,43.150697,6.341928,12,Clear
4,20,"Maison vue Mer, Marseille.",43.354912,5.333493,9.5,"Offrant une vue sur la ville, l’hébergement Ma...",Connexion Wi-Fi gratuite,Terrasse,not available,Terrasse,Machine à café,Marseille,43.296174,5.369953,13,Clear
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,34,** Studio cosy La Rochelle quartier des Minime...,46.140106,-1.161035,9.1,L’hébergement en bord de mer ** Studio cosy La...,Parking gratuit,Connexion Wi-Fi gratuite,En bord de plage,Chambres non-fumeurs,not available,La Rochelle,46.159732,-1.151595,11,Clear
246,34,Le Petit Caillebotis,46.142908,-1.156299,9.0,L’hébergement Le Petit Caillebotis se situe à ...,Parking gratuit,Chambres familiales,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Terrasse,La Rochelle,46.159732,-1.151595,11,Clear
247,34,Hôtel Kyriad La Rochelle Centre Ville,46.157796,-1.138319,8.4,L’Hôtel Kyriad La Rochelle Centre Ville vous a...,Parking privé,Chambres familiales,Connexion Wi-Fi gratuite,Restaurant,Chambres non-fumeurs,La Rochelle,46.159732,-1.151595,11,Clear
248,19,Le Nadadou par Dodo à Cassis,43.213317,5.549367,8.4,L’hébergement Le Nadadou par Dodo à Cassis pro...,Parking gratuit,Connexion Wi-Fi gratuite,Chambres non-fumeurs,Terrasse,Jardin,Cassis,43.214036,5.539632,12,Clear
249,21,Odalys City Aix en Provence Les Floridianes,43.521333,5.444777,8.0,L'Odalys City Aix en Provence Les Floridianes ...,Piscine extérieure,Parking privé,Connexion Wi-Fi gratuite,Chambres familiales,Chambres non-fumeurs,Aix-en-Provence,43.529842,5.447474,11,Clear

In [53]:
#Exporter la base de données finale 
result1.to_csv('towns_temp_forecast_best_hotels.csv', encoding='utf-8-sig')

#### Notez bien, toutes ces manipulations de transfert de data base vers S3/Pg Admin/Redshift peuvent se faire manuellement car les interfaces graphiques pour les manipulations du quotidien (cela évite les erreurs de code) \
#### Mais pour les usages de synchronisation ou de fichiers lourds, il est recommandé de passer par du code Python.

### Exemple de code pour envoyer vers S3

In [ ]:
import os
os.environ['AWS_ACCESS_KEY_ID'] = 'VOTREAWSACCESSKEY'
os.environ['AWS_SECRET_ACCESS_KEY'] = 'VotrePASSAWSSECRETKEY'
os.environ['AWS_DEFAULT_REGION'] = 'votre_région'  # Exemple : 'eu-west-1'

import boto3
from botocore.exceptions import NoCredentialsError

# Nom du fichier à envoyer
file_name = "towns_temp_forecast_best_hotels.csv"

# Nom du bucket S3 et clé (chemin) de destination
bucket_name = "votre-nom-de-bucket"  # Remplacez par votre bucket
s3_key = f"data/{file_name}"  # Chemin dans le bucket (exemple : 'data/nom_du_fichier.csv')

# Initialiser le client S3
s3 = boto3.client('s3')

try:
    # Envoyer le fichier
    s3.upload_file(file_name, bucket_name, s3_key)
    print(f"Le fichier {file_name} a été envoyé avec succès vers s3://{bucket_name}/{s3_key}")
except FileNotFoundError:
    print(f"Le fichier {file_name} n'existe pas localement.")
except NoCredentialsError:
    print("Les identifiants AWS ne sont pas disponibles.")
except Exception as e:
    print(f"Une erreur est survenue : {e}")

### Exemple de code pour envoyer vers PG ADmin - L'"upload" manuel peut se faire aussi

### Pour envoyer le fichier sur RedShift, utiliser l'interface de connexion peut éviter d'utiliser du code


pgAdmin installé : Version de pgAdmin > 4 installée sur votre ordinateur. \
**PostGresq** local est installé sur un minikube sous Docker\
Vous pouvez le télécharger depuis www.pgadmin.org.\
Cluster Redshift accessible : \
Endpoint du cluster (ex. : mycluster.abcdef123456.us-east-1.redshift.amazonaws.com).\
Port (par défaut : 5439 pour Redshift).\
Nom de la base de données : [nom de votre base de donnée]\
Nom d’utilisateur.\
Mot de passe associé.

### Code pour envoyer de PG Admin puis à Redshift ensuite

In [ ]:
import pandas as pd
import psycopg2
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT

# 1. Configuration de la connexion PostgreSQL (à adapter)
db_config = {
    "host": "localhost",
    "port": "5433",  # Port redirigé depuis Minikube
    "user": "postgres",  # Utilisateur par défaut pour Bitnami
    "password": "",  # Remplace par le mot de passe récupéré
}

# 2. Nom de la base de données et du fichier CSV
db_name = "hotels_db"  # Nom de la base à créer
local_file = "towns_temp_forecast_best_hotels.csv"  # Chemin vers ton fichier CSV

# 3. Lire le fichier CSV
try:
    df = pd.read_csv(local_file)
    print("Fichier CSV chargé avec succès.")
except Exception as e:
    print(f"Erreur lors de la lecture du CSV : {e}")
    raise

# 4. Connexion à PostgreSQL pour créer la base de données
try:
    # Connexion initiale pour créer la base de données
    conn = psycopg2.connect(
        host=db_config["host"],
        port=db_config["port"],
        user=db_config["user"],
        password=db_config["password"]
    )
    conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
    cursor = conn.cursor()

    # Créer la base de données si elle n'existe pas
    cursor.execute(f"SELECT 1 FROM pg_database WHERE datname = '{db_name}';")
    exists = cursor.fetchone()
    if not exists:
        cursor.execute(f"CREATE DATABASE {db_name};")
        print(f"Base de données '{db_name}' créée.")
    else:
        print(f"Base de données '{db_name}' existe déjà.")

    cursor.close()
    conn.close()
except Exception as e:
    print(f"Erreur lors de la création de la base de données : {e}")
    raise

# 5. Connexion à la base de données pour créer la table et insérer les données
try:
    # Connexion à la base de données spécifique
    conn = psycopg2.connect(
        host=db_config["host"],
        port=db_config["port"],
        user=db_config["user"],
        password=db_config["password"],
        database=db_name
    )
    cursor = conn.cursor()

    # Créer la table
    create_table_query = """
    CREATE TABLE IF NOT EXISTS hotels_forecast (
        id SERIAL PRIMARY KEY,
        hotel_name VARCHAR(255),
        hotel_lat FLOAT,
        hotel_long FLOAT,
        hotel_rating FLOAT,
        hotel_description TEXT,
        hotel_facilities TEXT,
        hotel_facilities_1 TEXT,
        hotel_facilities_2 TEXT,
        hotel_facilities_3 TEXT,
        hotel_facilities_4 TEXT,
        towns VARCHAR(100),
        town_lat FLOAT,
        town_long FLOAT,
        temperature_forecast FLOAT,
        weather_forecast VARCHAR(100)
    );
    """
    cursor.execute(create_table_query)
    conn.commit()
    print("Table 'hotels_forecast' créée ou déjà existante.")

    # Insérer les données
    for _, row in df.iterrows():
        insert_query = """
        INSERT INTO hotels_forecast (
            hotel_name, hotel_lat, hotel_long, hotel_rating, hotel_description,
            hotel_facilities, hotel_facilities_1, hotel_facilities_2, hotel_facilities_3, hotel_facilities_4,
            towns, town_lat, town_long, temperature_forecast, weather_forecast
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);
        """
        cursor.execute(insert_query, (
            row['hotel_name'], row['hotel_lat'], row['hotel_long'], row['hotel_rating'], row['hotel_description'],
            row['hotel_facilities'], row['hotel_facilities_1'], row['hotel_facilities_2'],
            row['hotel_facilities_3'], row['hotel_facilities_4'], row['towns'], row['town_lat'],
            row['town_long'], row['temperature_forecast'], row['weather_forecast']
        ))
    conn.commit()
    print("Données insérées avec succès dans PostgreSQL.")

except Exception as e:
    print(f"Erreur lors de l'insertion dans PostgreSQL : {e}")
    if 'conn' in locals():
        conn.rollback()
finally:
    if 'conn' in locals():
        cursor.close()
        conn.close()
    print("Connexion fermée.")

Fichier CSV chargé avec succès.
Base de données 'hotels_db' créée.
Table 'hotels_forecast' créée ou déjà existante.
Données insérées avec succès dans PostgreSQL.
Connexion fermée.

In [ ]:
import psycopg2

# Configuration de la connexion (à adapter)
db_config = {
    "host": "localhost",
    "port": "5433",  # Port redirigé depuis Minikube
    "user": "postgres",  # Utilisateur par défaut pour Bitnami
    "password": "",  # Remplace par ton mot de passe
    "database": "hotels_db"  # Nom de la base de données
}

def tester_connexion_postgresql():
    try:
        # 1. Connexion à la base de données
        conn = psycopg2.connect(**db_config)
        cursor = conn.cursor()
        print("✅ Connexion à PostgreSQL réussie !")

        # 2. Vérifier que la table `hotels_forecast` existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_name = 'hotels_forecast'
            );
        """)
        table_exists = cursor.fetchone()[0]
        if table_exists:
            print("✅ La table 'hotels_forecast' existe.")

            # 3. Compter le nombre de lignes dans la table
            cursor.execute("SELECT COUNT(*) FROM hotels_forecast;")
            row_count = cursor.fetchone()[0]
            print(f"📊 Nombre de lignes dans la table : {row_count}")

            # 4. Afficher les 5 premières lignes (optionnel)
            if row_count > 0:
                cursor.execute("SELECT * FROM hotels_forecast LIMIT 5;")
                colonnes = [desc[0] for desc in cursor.description]
                print("\n🔍 Aperçu des données :")
                print(", ".join(colonnes))
                for row in cursor.fetchall():
                    print(row)
        else:
            print("❌ La table 'hotels_forecast' n'existe pas.")

    except psycopg2.Error as e:
        print(f"❌ Erreur de connexion ou de requête : {e}")
    finally:
        if 'conn' in locals():
            cursor.close()
            conn.close()
            print("🔌 Connexion fermée.")

# Exécuter le test
tester_connexion_postgresql()

✅ Connexion à PostgreSQL réussie !
✅ La table 'hotels_forecast' existe.
📊 Nombre de lignes dans la table : 248

🔍 Aperçu des données :
id, hotel_name, hotel_lat, hotel_long, hotel_rating, hotel_description, hotel_facilities, hotel_facilities_1, hotel_facilities_2, hotel_facilities_3, hotel_facilities_4, towns, town_lat, town_long, temperature_forecast, weather_forecast
(1, 'easyHotel Marseille Euromed', 43.3101149, 5.3703396, 8.5, "L’établissement easyHotel Marseille Euromed bénéficie d’une situation géographique idéale dans le quartier Euromed - La Joliette de Marseille, à respectivement 700 mètres, 800 mètres et 1,5 km de ces lieux d’intérêt : Métro Joliette, Centre commercial Les Terrasses du Port et Gare de Marseille-Saint-Charles. Cet hôtel 2 étoiles propose des hébergements dotés de la climatisation, d’une salle de bains privative et d’une connexion Wi-Fi gratuite. Cet hôtel vous accueille à respectivement 1,9 km et 1,9 km de : Musée des Civilisations de l'Europe et de la Méditerranée (MuCEM) et Métro Vieux-Port.\n\nTous les hébergements sont pourvus d’une télévision à écran plat. Des serviettes et du linge de lit sont fournis.\n\nL’établissement easyHotel Marseille Euromed sert un petit-déjeuner buffet ou continental.\n\nParlant anglais, espagnol et français, le personnel de la réception se tient 24h/24 à votre disposition pour toute question.\n\nVous séjournerez à respectivement 3,4 km et 3,4 km de ces lieux d’intérêt\xa0: Métro Castellane et Rue Saint-Ferréol. L'aéroport le plus proche (Aéroport de Marseille Provence) est à 20 km.", 'Connexion Wi-Fi gratuite', 'Équipements pour les personnes handicapées', 'Réception ouverte 24h/24', 'Ascenseur', 'Chauffage', 'Marseille', 43.2961743, 5.3699525, 13.0, 'Clear')
(2, 'Staycity Aparthotels Marseille Centre Vieux Port', 43.30046625144968, 5.374441573016384, 8.4, "Doté d'une connexion Wi-Fi gratuite, le Staycity Aparthotels Marseille Centre Vieux Port propose un hébergement climatisé à Marseille, à seulement 550\xa0mètres du port. L’établissement est situé à 12\xa0minutes de marche de la gare de Marseille-Saint-Charles.\n\nTous les appartements et studios sont accessibles par un ascenseur et disposent d'une télévision à écran plat. Leur kitchenette est équipée d'un lave-vaisselle, d'un micro-ondes, d'un grille-pain, d'un réfrigérateur, de plaques de cuisson, d'une machine à café et d'une bouilloire. Les logements sont tous munis d’une salle de bains privative avec des articles de toilette gratuits. Les serviettes et le linge de lit sont fournis.\n\nVous trouverez des bars, des boutiques et des restaurants à moins de 2\xa0minutes de marche.\n\nLa station de métro la plus proche se trouve à seulement 44\xa0mètres. La Canebière est à 1\xa0km et le stade Vélodrome vous attend à 6,4\xa0km. L’aéroport Marseille-Provence, le plus proche de l’établissement, se trouve à 24\xa0km.\n\nCertains logements possèdent un balcon.", 'Parking', 'Connexion Wi-Fi gratuite', 'Chambres familiales', 'Chambres non-fumeurs', 'Équipements pour les personnes handicapées', 'Marseille', 43.2961743, 5.3699525, 13.0, 'Clear')
(3, 'Coup de Cœur VIEUX PORT-République', 43.2980309, 5.3729321, 9.6, "L’hébergement Coup de Cœur VIEUX PORT-République bénéficie d’une situation géographique idéale en plein cœur de Marseille. Offrant une vue sur la ville, il propose un salon commun et une terrasse. Cet hébergement est installé à 2,3 km de : Plage des Catalans. Il comprend une connexion Wi-Fi gratuite et une cuisine commune.\n\nCet appartement avec climatisation se compose de 2 chambres, d'un salon, d'une cuisine entièrement équipée avec un réfrigérateur et une machine à café, ainsi que de 1 salle de bains avec une douche et des articles de toilette gratuits. Des serviettes et du linge de lit sont à votre disposition.\n\nParlant anglais, espagnol et français, le personnel de la réception se fera un plaisir de vous renseigner sur la région.\n\nVous pourrez pratiquer la randonnée dans les environs.\n\nVous séjournerez à proximité de ces lieux d’intérêt\xa0: Métro Vieux-Port, Rue Saint-Ferréol et Métro Joliette. L'aéroport le plus proche (Aéroport de Marseille Provence) est à 22 km.", 'Connexion Wi-Fi gratuite', 'Chambres non-fumeurs', 'Réception ouverte 24h/24', 'Terrasse', 'Chauffage', 'Marseille', 43.2961743, 5.3699525, 13.0, 'Clear')
(4, 'Bord de mer, charmant studio entièrement équipé', 43.1260231, 6.358852, 9.4, "L’hébergement Bord de mer, charmant studio entièrement équipé vous accueille à Bormes-les-Mimosas, à respectivement 900 mètres, 900 mètres et 34 km de ces lieux d’intérêt : Plage de la Pointe de Gouron, Plage de l'Anglade et Chateau de Grimaud. Cet hébergement avec climatisation est installé à 600 mètres de\xa0: Plage de la Favière. Vous pourrez profiter d'un parking privé disponible sur place et d'une connexion Wi-Fi gratuite.\n\nCet appartement comporte 1 chambre, une cuisine avec un réfrigérateur et un micro-ondes, ainsi que 1 salle de bains avec une douche, un sèche-cheveux et un lave-linge. Une télévision à écran plat est à votre disposition.\n\nVous séjournerez à respectivement 34 km et 41 km de ces lieux d’intérêt\xa0: Le Pont des Fées et Gare de Toulon. L'aéroport le plus proche (Aéroport de Toulon - Hyères) est à 23 km.", 'Parking gratuit', 'Connexion Wi-Fi gratuite', 'Chambres non-fumeurs', 'not available', 'Connexion Wi-Fi gratuite', 'Bormes-les-Mimosas', 43.1506968, 6.3419285, 12.0, 'Clear')
(5, 'Maison vue Mer, Marseille.', 43.3549118, 5.3334931, 9.5, "Offrant une vue sur la ville, l’hébergement Maison vue Mer, Marseille. Propose une terrasse et un patio, à environ 7,3 km de ce lieu d’intérêt : Centre commercial Les Terrasses du Port. Cet hébergement offre une vue sur la mer et met à votre disposition une connexion Wi-Fi gratuite dans l’ensemble de ses locaux.\n\nCette maison de vacances avec climatisation comporte 2 chambres, une télévision à écran plat, ainsi qu’une cuisine avec un réfrigérateur et un lave-vaisselle.\n\nVous séjournerez à respectivement 7,5 km et 7,7 km de ces lieux d’intérêt\xa0: Métro Joliette et Musée des Civilisations de l'Europe et de la Méditerranée (MuCEM). L'aéroport le plus proche (Aéroport de Marseille Provence) est à 15 km.", 'Connexion Wi-Fi gratuite', 'Terrasse', 'not available', 'Terrasse', 'Machine à café', 'Marseille', 43.2961743, 5.3699525, 13.0, 'Clear')
🔌 Connexion fermée.

### Pour des raisons de coût, j'ai désactivé AWS Redshift