## Kayak Project - Récupération des données météo pour le ForeCast 🌤️

As the project has just started, your team doesn't have any data that can be used to create this application. Therefore, your job will be to: 

1 Retrieve GPS Coordinates

In [1]:
#Packages 
import requests
import pandas as pd
import asyncio
from geopy.geocoders import Nominatim
import time

In [ ]:
town_name = ["Mont Saint Michel","Saint Malo","Bayeux","Le Havre","Rouen","Paris","Amiens","Lille","Strasbourg","Chateau du Haut Koenigsbourg","Colmar","Eguisheim","Besancon","Dijon","Annecy","Grenoble","Lyon","Gorges du Verdon","Bormes les Mimosas","Cassis","Marseille",
"Aix en Provence","Avignon","Uzes","Nimes","Aigues Mortes","Saintes Maries de la mer","Collioure","Carcassonne","Ariege","Toulouse","Montauban","Biarritz","Bayonne","La Rochelle"]

geolocator = Nominatim(user_agent="eric_jedha")
location = geolocator.geocode("Lille")
best_towns = {}

In [51]:
df_gps = pd.read_csv('kayak.csv')

df_gps

                      Unnamed: 0          0         1
0              Mont Saint Michel  48.635954 -1.511460
1                     Saint Malo  48.649518 -2.026041
2                         Bayeux  49.276462 -0.702474
3                       Le Havre  49.493898  0.107973
4                          Rouen  49.440459  1.093966
5                          Paris  48.858890  2.320041
6                         Amiens  49.894171  2.295695
7                          Lille  50.636565  3.063528
8                     Strasbourg  48.584614  7.750713
9   Chateau du Haut Koenigsbourg  48.249411  7.344320
10                        Colmar  48.077752  7.357964
11                     Eguisheim  48.044797  7.307962
12                      Besancon  47.238022  6.024362
13                         Dijon  47.321581  5.041470
14                        Annecy  45.899235  6.128885
15                      Grenoble  45.187560  5.735782
16                          Lyon  45.757814  4.832011
17              Gorges du Verdon  43.749656  6.328562
18            Bormes les Mimosas  43.150697  6.341928
19                        Cassis  43.214036  5.539632
20                     Marseille  43.296174  5.369953
21               Aix en Provence  43.529842  5.447474
22                       Avignon  43.949249  4.805901
23                          Uzes  44.012128  4.419672
24                         Nimes  43.837425  4.360069
25                 Aigues Mortes  43.566152  4.191540
26      Saintes Maries de la mer  43.451592  4.427720
27                     Collioure  42.525050  3.083155
28                   Carcassonne  43.213036  2.349107
29                        Ariege  42.945537  1.406554
30                      Toulouse  43.604462  1.444247
31                     Montauban  44.017584  1.354999
32                      Biarritz  43.483252 -1.559278
33                       Bayonne  43.494514 -1.473666
34                   La Rochelle  46.159732 -1.151595

In [53]:
df_gps.rename(columns={'Unnamed: 0' : 'Town', '0' : 'Latitude', '1' : "Longitude"}, inplace=True)
df_gps['Id'] = df_gps.index
df_gps.to_csv('kayak_id.csv')

In [54]:
df_gps

                            Town   Latitude  Longitude  Id
0              Mont Saint Michel  48.635954  -1.511460   0
1                     Saint Malo  48.649518  -2.026041   1
2                         Bayeux  49.276462  -0.702474   2
3                       Le Havre  49.493898   0.107973   3
4                          Rouen  49.440459   1.093966   4
5                          Paris  48.858890   2.320041   5
6                         Amiens  49.894171   2.295695   6
7                          Lille  50.636565   3.063528   7
8                     Strasbourg  48.584614   7.750713   8
9   Chateau du Haut Koenigsbourg  48.249411   7.344320   9
10                        Colmar  48.077752   7.357964  10
11                     Eguisheim  48.044797   7.307962  11
12                      Besancon  47.238022   6.024362  12
13                         Dijon  47.321581   5.041470  13
14                        Annecy  45.899235   6.128885  14
15                      Grenoble  45.187560   5.735782  15
16                          Lyon  45.757814   4.832011  16
17              Gorges du Verdon  43.749656   6.328562  17
18            Bormes les Mimosas  43.150697   6.341928  18
19                        Cassis  43.214036   5.539632  19
20                     Marseille  43.296174   5.369953  20
21               Aix en Provence  43.529842   5.447474  21
22                       Avignon  43.949249   4.805901  22
23                          Uzes  44.012128   4.419672  23
24                         Nimes  43.837425   4.360069  24
25                 Aigues Mortes  43.566152   4.191540  25
26      Saintes Maries de la mer  43.451592   4.427720  26
27                     Collioure  42.525050   3.083155  27
28                   Carcassonne  43.213036   2.349107  28
29                        Ariege  42.945537   1.406554  29
30                      Toulouse  43.604462   1.444247  30
31                     Montauban  44.017584   1.354999  31
32                      Biarritz  43.483252  -1.559278  32
33                       Bayonne  43.494514  -1.473666  33
34                   La Rochelle  46.159732  -1.151595  34

In [61]:
df_gps
towns = df_gps[['Longitude', 'Latitude']]
long_list = towns['Longitude'].values.tolist()
lat_list = towns['Latitude'].values.tolist()
print(long_list[0:35])
print(lat_list[0:35])

[-1.511459954959514, -2.0260409, -0.7024738, 0.1079732, 1.0939658, 2.3200410217200766, 2.2956951, 3.0635282, 7.7507127, 7.344320233724503, 7.3579641, 7.3079618, 6.0243622, 5.0414701, 6.1288847, 5.7357819, 4.8320114, 6.3285616, 6.3419285, 5.5396318, 5.3699525, 5.4474738, 4.8059012, 4.4196718, 4.3600687, 4.19154, 4.4277202, 3.0831554, 2.3491069, 1.4065544156065486, 1.4442469, 1.3549991, -1.5592776, -1.4736657, -1.1515951]
[48.6359541, 48.649518, 49.2764624, 49.4938975, 49.4404591, 48.8588897, 49.8941708, 50.6365654, 48.584614, 48.24941075, 48.0777517, 48.0447968, 47.2380222, 47.3215806, 45.8992348, 45.1875602, 45.7578137, 43.7496562, 43.1506968, 43.2140359, 43.2961743, 43.5298424, 43.9492493, 44.0121279, 43.8374249, 43.5661521, 43.4515922, 42.52505, 43.2130358, 42.9455368, 43.6044622, 44.0175835, 43.4832523, 43.4945144, 46.159732]

In [36]:
towns.shape

(35, 2)

In [69]:
# URL Open Weather 

town_and_weather = []

for i in range(35):

    url = f"https://api.openweathermap.org/data/2.5/forecast?lat={lat_list[i]}&lon={long_list[i]}&cnt=7&appid=31960318197e2dc44a273c0f75853c1d"
    response = requests.get(url = url)
    response.json()
    icon= ''
    temps = response.json()
    weather7 = temps["list"][0]['weather'][0]['main']
    icon7 = temps["list"][0]['weather'][0]['icon']
    temperature = temps["list"][0]['main']['temp'] 
    temp7 = round(temperature - 273.15)

    town_and_weather.append({'Id' : i,
                            'temperature_forcast' : temp7,
                            'weather_forcast' : weather7})

print(town_and_weather)

[{'Id': 0, 'temperature_forcast': 8, 'weather_forcast': 'Clouds'}, {'Id': 1, 'temperature_forcast': 12, 'weather_forcast': 'Clouds'}, {'Id': 2, 'temperature_forcast': 9, 'weather_forcast': 'Clouds'}, {'Id': 3, 'temperature_forcast': 10, 'weather_forcast': 'Clouds'}, {'Id': 4, 'temperature_forcast': 5, 'weather_forcast': 'Clouds'}, {'Id': 5, 'temperature_forcast': 2, 'weather_forcast': 'Clouds'}, {'Id': 6, 'temperature_forcast': 3, 'weather_forcast': 'Clear'}, {'Id': 7, 'temperature_forcast': 2, 'weather_forcast': 'Clouds'}, {'Id': 8, 'temperature_forcast': 1, 'weather_forcast': 'Clear'}, {'Id': 9, 'temperature_forcast': 0, 'weather_forcast': 'Clear'}, {'Id': 10, 'temperature_forcast': 3, 'weather_forcast': 'Clear'}, {'Id': 11, 'temperature_forcast': 3, 'weather_forcast': 'Clear'}, {'Id': 12, 'temperature_forcast': 0, 'weather_forcast': 'Clear'}, {'Id': 13, 'temperature_forcast': 1, 'weather_forcast': 'Clouds'}, {'Id': 14, 'temperature_forcast': 5, 'weather_forcast': 'Clear'}, {'Id': 15, 'temperature_forcast': 4, 'weather_forcast': 'Clear'}, {'Id': 16, 'temperature_forcast': 2, 'weather_forcast': 'Clouds'}, {'Id': 17, 'temperature_forcast': 7, 'weather_forcast': 'Clear'}, {'Id': 18, 'temperature_forcast': 12, 'weather_forcast': 'Clear'}, {'Id': 19, 'temperature_forcast': 12, 'weather_forcast': 'Clear'}, {'Id': 20, 'temperature_forcast': 13, 'weather_forcast': 'Clear'}, {'Id': 21, 'temperature_forcast': 11, 'weather_forcast': 'Clear'}, {'Id': 22, 'temperature_forcast': 9, 'weather_forcast': 'Clear'}, {'Id': 23, 'temperature_forcast': 7, 'weather_forcast': 'Clear'}, {'Id': 24, 'temperature_forcast': 10, 'weather_forcast': 'Clear'}, {'Id': 25, 'temperature_forcast': 10, 'weather_forcast': 'Clear'}, {'Id': 26, 'temperature_forcast': 10, 'weather_forcast': 'Clear'}, {'Id': 27, 'temperature_forcast': 11, 'weather_forcast': 'Clear'}, {'Id': 28, 'temperature_forcast': 13, 'weather_forcast': 'Clear'}, {'Id': 29, 'temperature_forcast': 2, 'weather_forcast': 'Clear'}, {'Id': 30, 'temperature_forcast': 13, 'weather_forcast': 'Clear'}, {'Id': 31, 'temperature_forcast': 7, 'weather_forcast': 'Clear'}, {'Id': 32, 'temperature_forcast': 12, 'weather_forcast': 'Clear'}, {'Id': 33, 'temperature_forcast': 12, 'weather_forcast': 'Clear'}, {'Id': 34, 'temperature_forcast': 11, 'weather_forcast': 'Clear'}]

In [ ]:
print(town_and_weather)

{'Id': 34, 'temperature_forcast': 12, 'weather_forcast': 'Clear'}

In [72]:
towns_and_wforcast = pd.DataFrame.from_dict(town_and_weather)
towns_and_wforcast.to_csv('kayak_forecast.csv')

In [ ]:
df1 = pd.read_csv('kayak_id.csv')
df2 = pd.read_csv('kayak_forecast.csv')
df3 = pd.merge(df1, df2, on = 'Id')

df3 = df3.drop(['Unnamed: 0_x', 'Unnamed: 0_y'], axis = 1)
id_move = df3.pop('Id')
df3.insert(0, 'Id', id_move)

best_towns = df3.sort_values(by='temperature_forcast', ascending=False)
# 10 Best towns temperature in seven days (February 4 then it will be February 11)
best_towns[0:10]

,Id,Town,Latitude,Longitude,temperature_forcast,weather_forcast
20,20,Marseille,43.296174,5.369953,13,Clear
30,30,Toulouse,43.604462,1.444247,13,Clear
28,28,Carcassonne,43.213036,2.349107,13,Clear
18,18,Bormes les Mimosas,43.150697,6.341928,12,Clear
19,19,Cassis,43.214036,5.539632,12,Clear
33,33,Bayonne,43.494514,-1.473666,12,Clear
32,32,Biarritz,43.483252,-1.559278,12,Clear
1,1,Saint Malo,48.649518,-2.026041,12,Clouds
21,21,Aix en Provence,43.529842,5.447474,11,Clear
34,34,La Rochelle,46.159732,-1.151595,11,Clear

In [43]:
parsing_town = best_towns['Town'][0:10].str.replace(' ', '+')
parsing_town.to_list()

['Marseille',
 'Toulouse',
 'Carcassonne',
 'Bormes+les+Mimosas',
 'Cassis',
 'Bayonne',
 'Biarritz',
 'Saint+Malo',
 'Aix+en+Provence',
 'La+Rochelle']