# 🚗 GetAround EDA et Thereshold

In [112]:
import pandas as pd
import plotly.express as px
WIDTH = 800
HEIGHT = 600

In [113]:
df = pd.read_excel("get_around_delay_analysis.xlsx")
df

,rental_id,car_id,checkin_type,state,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes
0,505000,363965,mobile,canceled,NaN,NaN,NaN
1,507750,269550,mobile,ended,-81.0,NaN,NaN
2,508131,359049,connect,ended,70.0,NaN,NaN
3,508865,299063,connect,canceled,NaN,NaN,NaN
4,511440,313932,mobile,ended,NaN,NaN,NaN
...,...,...,...,...,...,...,...
21305,573446,380069,mobile,ended,NaN,573429.0,300.0
21306,573790,341965,mobile,ended,-337.0,NaN,NaN
21307,573791,364890,mobile,ended,144.0,NaN,NaN
21308,574852,362531,connect,ended,-76.0,NaN,NaN
21309,575056,351549,connect,ended,35.0,NaN,NaN

In [114]:
df.sample(500).to_csv("sample_getaroud.csv")

In [115]:
from skimpy import skim
skim(df)

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 21310  │ │ float64     │ 3     │                                                          │
│ │ Number of columns │ 7      │ │ int64       │ 2     │                                                          │
│ └───────────────────┴────────┘ │ string      │ 2     │                                                          │
│                                └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━┓  │
│ ┃ column       ┃ NA    ┃ NA %         ┃ mean   ┃ sd    ┃ p0     ┃ p25    ┃ p50    ┃ p75    ┃ p100   ┃ hist   ┃  │
│ ┡━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━┩  │
│ │ rental_id    │     0 │            0 │ 549700 │ 13860 │ 504800 │ 540600 │ 550400 │ 560500 │ 576400 │ ▁▁▅█▇▄ │  │
│ │ car_id       │     0 │            0 │ 350000 │ 58210 │ 159200 │ 317600 │ 368700 │ 394900 │ 417700 │ ▁▁▁▃▅█ │  │
│ │ delay_at_che │  4964 │ 23.294228061 │   59.7 │  1003 │ -22430 │    -36 │      9 │     67 │  71080 │    █   │  │
│ │ ckout_in_min │       │        94275 │        │       │        │        │        │        │        │        │  │
│ │ utes         │       │              │        │       │        │        │        │        │        │        │  │
│ │ previous_end │ 19469 │ 91.360863444 │ 550100 │ 13180 │ 505600 │ 540900 │ 550600 │ 560800 │ 575100 │ ▁▁▅██▅ │  │
│ │ ed_rental_id │       │        39231 │        │       │        │        │        │        │        │        │  │
│ │ time_delta_w │ 19469 │ 91.360863444 │  279.3 │ 254.6 │      0 │     60 │    180 │    540 │    720 │ █▄▂▁▂▅ │  │
│ │ ith_previous │       │        39231 │        │       │        │        │        │        │        │        │  │
│ │ _rental_in_m │       │              │        │       │        │        │        │        │        │        │  │
│ │ inutes       │       │              │        │       │        │        │        │        │        │        │  │
│ └──────────────┴───────┴──────────────┴────────┴───────┴────────┴────────┴────────┴────────┴────────┴────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━━━┳━━━━┳━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━┓  │
│ ┃             ┃    ┃      ┃          ┃          ┃          ┃        ┃ chars per   ┃ words per   ┃ total      ┃  │
│ ┃ column      ┃ NA ┃ NA % ┃ shortest ┃ longest  ┃ min      ┃ max    ┃ row         ┃ row         ┃ words      ┃  │
│ ┡━━━━━━━━━━━━━╇━━━━╇━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━┩  │
│ │ checkin_typ │  0 │    0 │ mobile   │ connect  │ connect  │ mobile │         6.2 │           1 │      21310 │  │
│ │ e           │    │      │          │          │          │        │             │             │            │  │
│ │ state       │  0 │    0 │ ended    │ canceled │ canceled │ ended  │        5.46 │           1 │      21310 │  │
│ └─────────────┴────┴──────┴──────────┴──────────┴──────────┴────────┴─────────────┴─────────────┴────────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

In [116]:
import pandas as pd
# Calculer le nombre de valeurs manquantes par colonne
missing_values_count = df.isnull().sum()

# Calculer le pourcentage de valeurs manquantes par colonne
missing_values_percent = (missing_values_count / len(df)) * 100

# Créer un nouveau DataFrame pour afficher les résultats
missing_data = pd.DataFrame({
    'missing_values_count': missing_values_count,
    'missing_values_percent': missing_values_percent
})

# Afficher les colonnes avec des valeurs manquantes et leur pourcentage
print(missing_data[missing_data['missing_values_count'] > 0])

                                            missing_values_count  \
delay_at_checkout_in_minutes                                4964
previous_ended_rental_id                                   19469
time_delta_with_previous_rental_in_minutes                 19469

                                            missing_values_percent
delay_at_checkout_in_minutes                             23.294228
previous_ended_rental_id                                 91.360863
time_delta_with_previous_rental_in_minutes               91.360863

In [117]:
missing_df = missing_data[missing_data['missing_values_count'] > 0]
missing_df_percent = missing_df['missing_values_percent'].reset_index()

In [118]:
fig = px.bar(
    missing_df_percent,
    x="index",
    y="missing_values_percent",
    hover_data=['index'],
    title="Données manquantes en pourcentage",
    color='index',
    text_auto='.2f',  # Affiche 2 décimales
    text="missing_values_percent"  # Affiche la valeur sur la barre
)

# Personnalisation pour ajouter le % et mettre en gras
fig.update_traces(
    texttemplate='<b>%{text:.2f}%</b>',  # Met en gras et ajoute le %
    textposition='inside'  # Place le texte à l'extérieur de la barre
)

fig.show()

In [119]:
#State of the car

state_car = df['state'].value_counts()
state_car = pd.DataFrame(state_car).reset_index()
state_car.columns = ['state', 'count']
#px.pie(state_car, values='count', names='state', title='State of the Car', color = 'state', width=WIDTH)

In [120]:
state_car

      state  count
0     ended  18045
1  canceled   3265

## Répartition des clients par état

In [121]:
import plotly.express as px

state_car = df['state'].value_counts()
state_car = pd.DataFrame(state_car).reset_index()
state_car.columns = ['state', 'count']

# Trouver les segments le plus petit et le plus gros
min_count = state_car['count'].min()
min_state = state_car[state_car['count'] == min_count]['state'].values[0]
max_count = state_car['count'].max()
max_state = state_car[state_car['count'] == max_count]['state'].values[0]

# Ajouter les emojis selon la taille du segment
state_car['state_with_emoji'] = state_car['state'].apply(
    lambda x: f'🚗 {x}' if x == min_state else (f'🚙 {x}' if x == max_state else x)
)

fig = px.pie(
    state_car,
    values='count',
    names='state_with_emoji',
    title='% de Clients qui concluent vs % de clients qui abandonnent',
    color='state',
    width=WIDTH,
    hole=0.3  # Optionnel : pour un donut chart
)

# Mettre en évidence le segment le plus faible (en jaune)
fig.update_traces(
    textposition='inside',
    insidetextorientation='radial',
    marker=dict(
        colors=['yellow' if state == min_state else color
                for state, color in zip(state_car['state'], fig.data[0].marker.colors)],
        line=dict(
            color='white',
            width=[3 if state == min_state else 1
                   for state in state_car['state']]
        )
    ),
    textinfo='percent+label',
    textfont=dict(
        size=14,
        color=['black' if state == min_state else 'black'
               for state in state_car['state']]  # Texte noir pour lisibilité sur jaune
    )
)

fig.show()

## Plus de 15% de clients annulent leur course.

In [122]:
# Mask sur les types de checkin vs ended canceled

checkin_df = df.groupby('checkin_type')['state'].value_counts()
checkin_df = pd.DataFrame(checkin_df).reset_index()

checkin_df

  checkin_type     state  count
0      connect     ended   3509
1      connect  canceled    798
2       mobile     ended  14536
3       mobile  canceled   2467

In [123]:
checkin_df_connect = checkin_df[checkin_df['checkin_type'] == 'connect']['count'].sum()
checkin_df_mobile = checkin_df[checkin_df['checkin_type'] == 'mobile']['count'].sum()
total_checkin = checkin_df['count'].sum()

In [124]:
checkin_df = checkin_df.assign(percent=lambda x: (x['count']/total_checkin)*100)
checkin_df

  checkin_type     state  count    percent
0      connect     ended   3509  16.466448
1      connect  canceled    798   3.744721
2       mobile     ended  14536  68.212107
3       mobile  canceled   2467  11.576725

In [125]:

import plotly.graph_objects as go
# Supposons que checkin_df soit votre DataFrame
# Exemple de données
# Création du graphique avec go.Bar
fig = go.Figure()
# Ajout des barres pour chaque état
for state in checkin_df['state'].unique():
    df_state = checkin_df[checkin_df['state'] == state]
    fig.add_trace(go.Bar(
    x=df_state['checkin_type'],
    y=df_state['percent'],
    name=state,
    text=df_state['percent'].apply(lambda x: f'{round(x,2)}% 🚗'),
    textfont=dict(size=12, weight='bold'),
    textposition="outside",
))
# Mise en page
fig.update_layout(
title='Type of Checkin vs State',
xaxis_title='Checkin Type',
yaxis_title='Percent',
barmode='group',
width=WIDTH,
height=HEIGHT # Assurez-vous que WIDTH est défini
)
# Affichage du graphique
fig.show()

In [126]:
fig = go.Figure()

# Dictionnaires mis à jour pour correspondre aux données réelles ('ended', 'canceled')
emoji_map = {
    'ended': '🚙',    # Un émoji pour "terminé"
    'canceled': '🚗' # Un émoji pour "annulé"
}

color_map = {
    'ended': '#647CF6',   
    'canceled': '#F06050' 
}


for state in checkin_df['state'].unique():
    df_state = checkin_df[checkin_df['state'] == state]
    
    
    emoji = emoji_map[state]
    color = color_map[state]

    fig.add_trace(go.Bar(
        x=df_state['checkin_type'],
        y=df_state['percent'],
        name=state,
        text=df_state['percent'].apply(lambda x: f'{round(x, 1)}% {emoji}'),
        textfont=dict(size=16, weight='bold', color='black'),
        textposition="outside",
        marker_color=color,
        marker_line_width=0
    ))

# Mise en page
fig.update_layout(
    yaxis_title='Percent',
    xaxis_title=None,
    barmode='group',
    plot_bgcolor='rgb(240, 242, 246)',
    paper_bgcolor='white',
    yaxis=dict(
        gridcolor='white',
        range=[0, max(checkin_df['percent']) * 1.15] # Ajuste automatiquement la hauteur de l'axe Y
    ),
    xaxis=dict(
        tickfont=dict(size=14)
    ),
    legend_title_text='État du Check-in', # Ajout d'un titre à la légende
    font=dict(family="Arial, sans-serif"),
    # showlegend=False, # On peut l'activer pour voir la différence entre 'ended' et 'canceled'
    width=800,
    height=600
)

fig.show()

In [127]:
# Mask sur les Canceled

import plotly.express as px

# Préparation des données
mask_canceled = df['state'] == 'canceled'
car_canceled_detail = df[mask_canceled]
car_canceled_detail = car_canceled_detail['checkin_type'].value_counts().reset_index()
car_canceled_detail.columns = ['checkin_type', 'count']

# Trouver les segments le plus petit et le plus gros
min_count = car_canceled_detail['count'].min()
min_type = car_canceled_detail[car_canceled_detail['count'] == min_count]['checkin_type'].values[0]
max_count = car_canceled_detail['count'].max()
max_type = car_canceled_detail[car_canceled_detail['count'] == max_count]['checkin_type'].values[0]

# Ajouter les emojis selon la taille du segment
car_canceled_detail['checkin_type_with_emoji'] = car_canceled_detail['checkin_type'].apply(
    lambda x: f'🚗 {x}' if x == min_type else (f'🚙 {x}' if x == max_type else x)
)

# Créer le camembert avec les couleurs personnalisées
fig = px.pie(
    car_canceled_detail,
    values='count',
    names='checkin_type_with_emoji',
    title='Groupe Cancel : Checkin Type',
    color='checkin_type',
    width=WIDTH,
    hole=0.3,
    color_discrete_map={min_type: 'yellow', max_type: '#6275F7'}  # Couleurs personnalisées
)

# Détacher le petit segment et ajuster la mise en forme
fig.update_traces(
    pull=[0.1 if checkin_type == min_type else 0 for checkin_type in car_canceled_detail['checkin_type']],
    textposition='inside',
    insidetextorientation='radial',
    marker=dict(
        line=dict(color='white', width=2)
    ),
    textinfo='percent+label',
    textfont=dict(size=14, color='black')
)

fig.show()

In [128]:
# Mask Delay Checkout supérieur à zéro (donc retard)
mask_delay = df['delay_at_checkout_in_minutes'] > 0
df_delay = df[mask_delay]

In [129]:
df_delay

,rental_id,car_id,checkin_type,state,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes
2,508131,359049,connect,ended,70.0,NaN,NaN
9,513434,256528,connect,ended,23.0,NaN,NaN
12,514257,402596,mobile,ended,214.0,NaN,NaN
13,515147,257466,mobile,ended,15.0,NaN,NaN
17,518895,398816,mobile,ended,66.0,NaN,NaN
...,...,...,...,...,...,...,...
21299,571738,406927,mobile,ended,68.0,NaN,NaN
21301,572736,393486,mobile,ended,180.0,NaN,NaN
21303,573305,392752,mobile,ended,72.0,NaN,NaN
21307,573791,364890,mobile,ended,144.0,NaN,NaN
21309,575056,351549,connect,ended,35.0,NaN,NaN

In [130]:
#Mask sur les Canceled Vs Delay
df_delay_canceled = df_delay['state'] == 'canceled'
df_canceled_data = df_delay[df_delay_canceled]

In [131]:
# Vérification : quand les gens annulent, pas de temps de délai entre 2 voitures.
df_canceled_data

Empty DataFrame
Columns: [rental_id, car_id, checkin_type, state, delay_at_checkout_in_minutes, previous_ended_rental_id, time_delta_with_previous_rental_in_minutes]
Index: []

In [132]:
# Groupe "canceled" et Filtre NA sur time_delta_with_previous_rental_in_minutes
canceled_vs_delta = df[mask_canceled]
mask_delta = canceled_vs_delta['time_delta_with_previous_rental_in_minutes'].isna()==False
canceled_vs_delta_1 = canceled_vs_delta[mask_delta]
canceled_vs_delta_1

,rental_id,car_id,checkin_type,state,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes
204,543768,374169,connect,canceled,NaN,543010.0,210.0
242,546160,352528,connect,canceled,NaN,546578.0,630.0
504,564627,341431,mobile,canceled,NaN,552005.0,150.0
637,568657,317378,connect,canceled,NaN,566412.0,210.0
669,516550,377700,mobile,canceled,NaN,545076.0,720.0
...,...,...,...,...,...,...,...
21172,566228,390871,connect,canceled,NaN,568465.0,60.0
21197,567305,405564,mobile,canceled,NaN,552222.0,0.0
21230,569706,245154,connect,canceled,NaN,558088.0,660.0
21269,568049,381499,connect,canceled,NaN,562174.0,720.0
21272,568241,396409,mobile,canceled,NaN,566136.0,570.0

In [133]:
# Filtre time_delta > 0
delta_nb_mask = df['time_delta_with_previous_rental_in_minutes'] > 0

In [134]:
# DataFrame time_delta > 0
delta_nb_dataf = df[delta_nb_mask]
delta_nb_dataf

,rental_id,car_id,checkin_type,state,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes
6,511639,370585,connect,ended,-15.0,563782.0,570.0
19,519491,312389,mobile,ended,58.0,545639.0,420.0
34,525044,349751,mobile,ended,NaN,510607.0,60.0
40,528808,181625,connect,ended,-76.0,557404.0,330.0
64,533670,320824,connect,ended,-6.0,556563.0,630.0
...,...,...,...,...,...,...,...
21269,568049,381499,connect,canceled,NaN,562174.0,720.0
21272,568241,396409,mobile,canceled,NaN,566136.0,570.0
21275,568523,297973,mobile,ended,12.0,567121.0,240.0
21286,569717,377312,mobile,ended,230.0,545045.0,90.0
21305,573446,380069,mobile,ended,NaN,573429.0,300.0

In [135]:
# est-ce qu'il y a des NA ? Non.
delta_nb_dataf['time_delta_with_previous_rental_in_minutes'].isna().count()

1562

In [136]:
delta_nb_dataf = df[delta_nb_mask]

delta_nb = delta_nb_dataf.shape[0]

In [137]:
delta_nb

1562

In [138]:
from summarytools import dfSummary
dfSummary(delta_nb_dataf)

In [139]:
mask_canceled

0         True
1        False
2        False
3         True
4        False
         ...
21305    False
21306    False
21307    False
21308    False
21309    False
Name: state, Length: 21310, dtype: bool

In [140]:
#Nombre de Canceled total
canceled_total = df[mask_canceled]['state'].value_counts()
print(f"Nombre total de cancel : {canceled_total}")
#% de Canceled total 
print(round((canceled_total/df.shape[0])*100, 2))

Nombre total de cancel : state
canceled    3265
Name: count, dtype: int64
state
canceled    15.32
Name: count, dtype: float64

In [141]:
# Mask time_delta > 0 et state = canceled

delta_mask_canceled = delta_nb_dataf['state']=='canceled'

#Nombre de cancel avec time_delta > 0
delta_mask_nb = delta_nb_dataf[delta_mask_canceled]
print(f'Nombre de Canceled à la 2e location : {delta_mask_nb.shape[0]}')

delta_mask_ended= delta_nb_dataf['state']=='ended'

#nombre de Ended avec time_delta > 0
delta_mask_ended_nb = delta_nb_dataf[delta_mask_ended]
print(f'Nombre de Ended à la 2e location : {delta_mask_ended_nb.shape[0]}')

Nombre de Canceled à la 2e location : 194
Nombre de Ended à la 2e location : 1368

In [ ]:
#% de canceled à la 2e location sur le total /!\ temps Delta sup à 0, car annulation dès 0.
print(f"Pourcentage de Canceled à la 2e location sur le total : {round((delta_mask_nb.shape[0]/df.shape[0])*100, 2)}")
print(f"Pourcentage de Canceled à la 2e location sur le total : {round((delta_mask_nb.shape[0]/canceled_total)*100, 2)}")

Pourcentage de Canceled à la 2e location sur le total : 0.91
Pourcentage de Canceled à la 2e location sur le total : state
canceled    5.94
Name: count, dtype: float64

# Threshold : Calculateur de Seuil

In [143]:
#delta_mask_nb = nombre de cancel avec time_delta > 0

print(f"Pourcentage de perte ou de cancel avec un Time Delta > 0 : {round(delta_mask_nb.shape[0] / (delta_mask_nb.shape[0] + delta_mask_ended_nb.shape[0]) * 100, 2)}%")

Pourcentage de perte ou de cancel avec un Time Delta > 0 : 12.42%

In [144]:
# canceled_vs_delta_1 = Filtre sur Cancel
# Calcul nombre de cancel (nombre de lignes) (time_delta en fonction des minutes de temps_cancel donné)

temps_cancel = [1, 5, 10, 15, 20, 30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 400, 500, 600, 700, 750]


def cancel(tps_cancel):
    cancel_10min = (canceled_vs_delta_1[(canceled_vs_delta_1["time_delta_with_previous_rental_in_minutes"] <= tps_cancel)])
    print(f"Pourcentage d'annulation après {tps_cancel}min d'attente pour 2e location : {round((cancel_10min.shape[0]/delta_nb)*100,2)}% 😤")


cancel(15)

Pourcentage d'annulation après 15min d'attente pour 2e location : 2.24% 😤

In [145]:
for i in temps_cancel:
    cancel_10min = (canceled_vs_delta_1[(canceled_vs_delta_1["time_delta_with_previous_rental_in_minutes"] <= i)])
    print(f"Pourcentage d'annulation après {i}min d'attente pour 2e location : {round((cancel_10min.shape[0]/delta_nb)*100,2)}% 😤")

Pourcentage d'annulation après 1min d'attente pour 2e location : 2.24% 😤
Pourcentage d'annulation après 5min d'attente pour 2e location : 2.24% 😤
Pourcentage d'annulation après 10min d'attente pour 2e location : 2.24% 😤
Pourcentage d'annulation après 15min d'attente pour 2e location : 2.24% 😤
Pourcentage d'annulation après 20min d'attente pour 2e location : 2.24% 😤
Pourcentage d'annulation après 30min d'attente pour 2e location : 2.75% 😤
Pourcentage d'annulation après 60min d'attente pour 2e location : 4.23% 😤
Pourcentage d'annulation après 90min d'attente pour 2e location : 4.74% 😤
Pourcentage d'annulation après 120min d'attente pour 2e location : 5.57% 😤
Pourcentage d'annulation après 150min d'attente pour 2e location : 6.21% 😤
Pourcentage d'annulation après 180min d'attente pour 2e location : 6.79% 😤
Pourcentage d'annulation après 210min d'attente pour 2e location : 7.49% 😤
Pourcentage d'annulation après 240min d'attente pour 2e location : 8.07% 😤
Pourcentage d'annulation après 270min d'attente pour 2e location : 8.32% 😤
Pourcentage d'annulation après 300min d'attente pour 2e location : 8.45% 😤
Pourcentage d'annulation après 400min d'attente pour 2e location : 9.28% 😤
Pourcentage d'annulation après 500min d'attente pour 2e location : 10.37% 😤
Pourcentage d'annulation après 600min d'attente pour 2e location : 12.29% 😤
Pourcentage d'annulation après 700min d'attente pour 2e location : 13.96% 😤
Pourcentage d'annulation après 750min d'attente pour 2e location : 14.66% 😤

In [146]:
delta_mask_nb

,rental_id,car_id,checkin_type,state,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes
204,543768,374169,connect,canceled,NaN,543010.0,210.0
242,546160,352528,connect,canceled,NaN,546578.0,630.0
504,564627,341431,mobile,canceled,NaN,552005.0,150.0
637,568657,317378,connect,canceled,NaN,566412.0,210.0
669,516550,377700,mobile,canceled,NaN,545076.0,720.0
...,...,...,...,...,...,...,...
21022,560787,413181,mobile,canceled,NaN,560542.0,150.0
21172,566228,390871,connect,canceled,NaN,568465.0,60.0
21230,569706,245154,connect,canceled,NaN,558088.0,660.0
21269,568049,381499,connect,canceled,NaN,562174.0,720.0
21272,568241,396409,mobile,canceled,NaN,566136.0,570.0

In [147]:
# Pourcentage de d'annulation en Desktop (connect) selon le temps d'attente

delta_mask_connect = delta_mask_nb['checkin_type']== 'connect'
delta_connect_nb = delta_mask_nb[delta_mask_connect]
delta_connect_nb

,rental_id,car_id,checkin_type,state,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes
204,543768,374169,connect,canceled,NaN,543010.0,210.0
242,546160,352528,connect,canceled,NaN,546578.0,630.0
637,568657,317378,connect,canceled,NaN,566412.0,210.0
1002,528088,383110,connect,canceled,NaN,546057.0,150.0
1106,538906,334190,connect,canceled,NaN,556215.0,630.0
...,...,...,...,...,...,...,...
20309,569736,376491,connect,canceled,NaN,571965.0,510.0
20658,552433,349678,connect,canceled,NaN,555522.0,420.0
21172,566228,390871,connect,canceled,NaN,568465.0,60.0
21230,569706,245154,connect,canceled,NaN,558088.0,660.0
21269,568049,381499,connect,canceled,NaN,562174.0,720.0

In [148]:
temps_cancel = [1, 5, 10, 20, 30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 400, 500, 600, 700, 750]

for i in temps_cancel:
    cancel_10min = (delta_connect_nb [(delta_connect_nb["time_delta_with_previous_rental_in_minutes"] < i)])
    print(f"Pourcentage d'annulation - Desktop 🖥 -  après {i}min d'attente pour 2e location : {round((cancel_10min.shape[0]/delta_nb)*100,2)}%")

Pourcentage d'annulation - Desktop 🖥 -  après 1min d'attente pour 2e location : 0.0%
Pourcentage d'annulation - Desktop 🖥 -  après 5min d'attente pour 2e location : 0.0%
Pourcentage d'annulation - Desktop 🖥 -  après 10min d'attente pour 2e location : 0.0%
Pourcentage d'annulation - Desktop 🖥 -  après 20min d'attente pour 2e location : 0.0%
Pourcentage d'annulation - Desktop 🖥 -  après 30min d'attente pour 2e location : 0.0%
Pourcentage d'annulation - Desktop 🖥 -  après 60min d'attente pour 2e location : 0.19%
Pourcentage d'annulation - Desktop 🖥 -  après 90min d'attente pour 2e location : 1.09%
Pourcentage d'annulation - Desktop 🖥 -  après 120min d'attente pour 2e location : 1.34%
Pourcentage d'annulation - Desktop 🖥 -  après 150min d'attente pour 2e location : 1.73%
Pourcentage d'annulation - Desktop 🖥 -  après 180min d'attente pour 2e location : 2.11%
Pourcentage d'annulation - Desktop 🖥 -  après 210min d'attente pour 2e location : 2.37%
Pourcentage d'annulation - Desktop 🖥 -  après 240min d'attente pour 2e location : 2.69%
Pourcentage d'annulation - Desktop 🖥 -  après 270min d'attente pour 2e location : 3.14%
Pourcentage d'annulation - Desktop 🖥 -  après 300min d'attente pour 2e location : 3.33%
Pourcentage d'annulation - Desktop 🖥 -  après 400min d'attente pour 2e location : 3.71%
Pourcentage d'annulation - Desktop 🖥 -  après 500min d'attente pour 2e location : 4.35%
Pourcentage d'annulation - Desktop 🖥 -  après 600min d'attente pour 2e location : 4.93%
Pourcentage d'annulation - Desktop 🖥 -  après 700min d'attente pour 2e location : 6.66%
Pourcentage d'annulation - Desktop 🖥 -  après 750min d'attente pour 2e location : 6.98%

In [149]:
# Pourcentage de d'annulation en Mobile selon le temps d'attente

delta_mask_mobile = delta_mask_nb['checkin_type']== 'mobile'
delta_mobile_nb = delta_mask_nb[delta_mask_mobile]
delta_mobile_nb

,rental_id,car_id,checkin_type,state,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes
504,564627,341431,mobile,canceled,NaN,552005.0,150.0
669,516550,377700,mobile,canceled,NaN,545076.0,720.0
1157,542320,377924,mobile,canceled,NaN,541053.0,120.0
1326,539915,314455,mobile,canceled,NaN,533006.0,180.0
1491,533570,271621,mobile,canceled,NaN,561375.0,120.0
...,...,...,...,...,...,...,...
19899,575049,382444,mobile,canceled,NaN,568419.0,330.0
20978,557237,366025,mobile,canceled,NaN,555447.0,360.0
21003,559133,335341,mobile,canceled,NaN,558460.0,300.0
21022,560787,413181,mobile,canceled,NaN,560542.0,150.0
21272,568241,396409,mobile,canceled,NaN,566136.0,570.0

In [150]:
temps_cancel = [1, 5, 10, 20, 30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 400, 500, 600, 700, 750]

for i in temps_cancel:
    cancel_10min = (delta_mobile_nb[(delta_mobile_nb["time_delta_with_previous_rental_in_minutes"] <= i)])
    print(f"Pourcentage d'annulation mobile - 📵 - après {i}min d'attente pour 2e location : {round((cancel_10min.shape[0]/delta_nb)*100,2)} %")

Pourcentage d'annulation mobile - 📵 - après 1min d'attente pour 2e location : 0.0 %
Pourcentage d'annulation mobile - 📵 - après 5min d'attente pour 2e location : 0.0 %
Pourcentage d'annulation mobile - 📵 - après 10min d'attente pour 2e location : 0.0 %
Pourcentage d'annulation mobile - 📵 - après 20min d'attente pour 2e location : 0.0 %
Pourcentage d'annulation mobile - 📵 - après 30min d'attente pour 2e location : 0.32 %
Pourcentage d'annulation mobile - 📵 - après 60min d'attente pour 2e location : 0.9 %
Pourcentage d'annulation mobile - 📵 - après 90min d'attente pour 2e location : 1.15 %
Pourcentage d'annulation mobile - 📵 - après 120min d'attente pour 2e location : 1.6 %
Pourcentage d'annulation mobile - 📵 - après 150min d'attente pour 2e location : 1.86 %
Pourcentage d'annulation mobile - 📵 - après 180min d'attente pour 2e location : 2.18 %
Pourcentage d'annulation mobile - 📵 - après 210min d'attente pour 2e location : 2.56 %
Pourcentage d'annulation mobile - 📵 - après 240min d'attente pour 2e location : 2.69 %
Pourcentage d'annulation mobile - 📵 - après 270min d'attente pour 2e location : 2.75 %
Pourcentage d'annulation mobile - 📵 - après 300min d'attente pour 2e location : 2.82 %
Pourcentage d'annulation mobile - 📵 - après 400min d'attente pour 2e location : 3.33 %
Pourcentage d'annulation mobile - 📵 - après 500min d'attente pour 2e location : 3.78 %
Pourcentage d'annulation mobile - 📵 - après 600min d'attente pour 2e location : 4.48 %
Pourcentage d'annulation mobile - 📵 - après 700min d'attente pour 2e location : 5.06 %
Pourcentage d'annulation mobile - 📵 - après 750min d'attente pour 2e location : 5.44 %

In [151]:
df

,rental_id,car_id,checkin_type,state,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes
0,505000,363965,mobile,canceled,NaN,NaN,NaN
1,507750,269550,mobile,ended,-81.0,NaN,NaN
2,508131,359049,connect,ended,70.0,NaN,NaN
3,508865,299063,connect,canceled,NaN,NaN,NaN
4,511440,313932,mobile,ended,NaN,NaN,NaN
...,...,...,...,...,...,...,...
21305,573446,380069,mobile,ended,NaN,573429.0,300.0
21306,573790,341965,mobile,ended,-337.0,NaN,NaN
21307,573791,364890,mobile,ended,144.0,NaN,NaN
21308,574852,362531,connect,ended,-76.0,NaN,NaN
21309,575056,351549,connect,ended,35.0,NaN,NaN

In [152]:
delay_mask = df['delay_at_checkout_in_minutes'] > 0
delay_dataf = df[delay_mask]
#delay_dataf_mask_cancel = delay_dataf['state']=='canceled'

delay_dataf

,rental_id,car_id,checkin_type,state,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes
2,508131,359049,connect,ended,70.0,NaN,NaN
9,513434,256528,connect,ended,23.0,NaN,NaN
12,514257,402596,mobile,ended,214.0,NaN,NaN
13,515147,257466,mobile,ended,15.0,NaN,NaN
17,518895,398816,mobile,ended,66.0,NaN,NaN
...,...,...,...,...,...,...,...
21299,571738,406927,mobile,ended,68.0,NaN,NaN
21301,572736,393486,mobile,ended,180.0,NaN,NaN
21303,573305,392752,mobile,ended,72.0,NaN,NaN
21307,573791,364890,mobile,ended,144.0,NaN,NaN
21309,575056,351549,connect,ended,35.0,NaN,NaN

In [153]:
delay_dataf.describe()

,rental_id,car_id,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes
count,9404.000000,9404.00000,9404.000000,802.000000,802.000000
mean,550128.381433,349430.39345,201.791472,549388.846633,259.376559
std,13483.656692,58737.84446,1243.645804,13654.521614,248.481753
min,504970.000000,159250.00000,1.000000,506069.000000,0.000000
25%,541204.000000,317525.75000,19.000000,540077.000000,60.000000
50%,550658.500000,368687.50000,53.000000,549836.500000,150.000000
75%,560454.750000,394781.00000,131.000000,560640.000000,480.000000
max,576401.000000,416992.00000,71084.000000,574596.000000,720.000000

In [154]:
# Distribution du Delay de Checkout

fig = px.scatter(delay_dataf, x = "delay_at_checkout_in_minutes")
fig.show()

In [155]:
#Split des delays

df

,rental_id,car_id,checkin_type,state,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes
0,505000,363965,mobile,canceled,NaN,NaN,NaN
1,507750,269550,mobile,ended,-81.0,NaN,NaN
2,508131,359049,connect,ended,70.0,NaN,NaN
3,508865,299063,connect,canceled,NaN,NaN,NaN
4,511440,313932,mobile,ended,NaN,NaN,NaN
...,...,...,...,...,...,...,...
21305,573446,380069,mobile,ended,NaN,573429.0,300.0
21306,573790,341965,mobile,ended,-337.0,NaN,NaN
21307,573791,364890,mobile,ended,144.0,NaN,NaN
21308,574852,362531,connect,ended,-76.0,NaN,NaN
21309,575056,351549,connect,ended,35.0,NaN,NaN

In [156]:
#transforme Early en Ontime
def status_time(x):
    if x <0:
        return 'ONTIME'
    elif x > 0:
        return "DELAY"
    else:
        return "NOFINFO"


df['time'] = df['delay_at_checkout_in_minutes'].apply(status_time)

In [157]:
df

,rental_id,car_id,checkin_type,state,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes,time
0,505000,363965,mobile,canceled,NaN,NaN,NaN,NOFINFO
1,507750,269550,mobile,ended,-81.0,NaN,NaN,ONTIME
2,508131,359049,connect,ended,70.0,NaN,NaN,DELAY
3,508865,299063,connect,canceled,NaN,NaN,NaN,NOFINFO
4,511440,313932,mobile,ended,NaN,NaN,NaN,NOFINFO
...,...,...,...,...,...,...,...,...
21305,573446,380069,mobile,ended,NaN,573429.0,300.0,NOFINFO
21306,573790,341965,mobile,ended,-337.0,NaN,NaN,ONTIME
21307,573791,364890,mobile,ended,144.0,NaN,NaN,DELAY
21308,574852,362531,connect,ended,-76.0,NaN,NaN,ONTIME
21309,575056,351549,connect,ended,35.0,NaN,NaN,DELAY

In [158]:
df_state_time = df['time'].value_counts()
df_state_time = pd.DataFrame(df_state_time).reset_index()

In [159]:
df_state_time

      time  count
0    DELAY   9404
1   ONTIME   6820
2  NOFINFO   5086

In [160]:
px.pie(df_state_time, values='count', names = 'time', width=WIDTH, title="State of the Car")

In [161]:
#Report du State sur les ligne NOINFO

df['time'] = df.apply(lambda row: row['state'].upper() if row['time'] == 'NOFINFO' else row['time'], axis=1)
df

,rental_id,car_id,checkin_type,state,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes,time
0,505000,363965,mobile,canceled,NaN,NaN,NaN,CANCELED
1,507750,269550,mobile,ended,-81.0,NaN,NaN,ONTIME
2,508131,359049,connect,ended,70.0,NaN,NaN,DELAY
3,508865,299063,connect,canceled,NaN,NaN,NaN,CANCELED
4,511440,313932,mobile,ended,NaN,NaN,NaN,ENDED
...,...,...,...,...,...,...,...,...
21305,573446,380069,mobile,ended,NaN,573429.0,300.0,ENDED
21306,573790,341965,mobile,ended,-337.0,NaN,NaN,ONTIME
21307,573791,364890,mobile,ended,144.0,NaN,NaN,DELAY
21308,574852,362531,connect,ended,-76.0,NaN,NaN,ONTIME
21309,575056,351549,connect,ended,35.0,NaN,NaN,DELAY

In [162]:
df_state = df['time'].value_counts()
df_state

time
DELAY       9404
ONTIME      6820
CANCELED    3264
ENDED       1822
Name: count, dtype: int64

In [163]:
df_state_detail = pd.DataFrame(df_state).reset_index()
px.pie(df_state_detail, values='count', names = 'time', width=WIDTH, title="State of the Car")

In [171]:
mask_positif = df['time_state_convert'] >=  0
delta_positif = df[mask_positif]

mask_positif_canceled = delta_positif['state'] == "canceled"
delta_positif[mask_positif_canceled]

,rental_id,car_id,checkin_type,state,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes,time,time_state_convert,palier
0,505000,363965,mobile,canceled,NaN,NaN,NaN,CANCELED,0.0,0MIN
3,508865,299063,connect,canceled,NaN,NaN,NaN,CANCELED,0.0,0MIN
8,512475,322502,mobile,canceled,NaN,NaN,NaN,CANCELED,0.0,0MIN
10,513743,330658,mobile,canceled,NaN,NaN,NaN,CANCELED,0.0,0MIN
11,514161,366037,connect,canceled,NaN,NaN,NaN,CANCELED,0.0,0MIN
...,...,...,...,...,...,...,...,...,...,...
21283,569325,345079,mobile,canceled,NaN,NaN,NaN,CANCELED,0.0,0MIN
21287,569764,405347,mobile,canceled,NaN,NaN,NaN,CANCELED,0.0,0MIN
21288,570001,386413,connect,canceled,NaN,NaN,NaN,CANCELED,0.0,0MIN
21297,571481,311841,mobile,canceled,NaN,NaN,NaN,CANCELED,0.0,0MIN
21300,572293,355023,connect,canceled,NaN,NaN,NaN,CANCELED,0.0,0MIN

In [172]:
# Mask time_delta > 0

mask_delta = df['time_delta_with_previous_rental_in_minutes'] >=  0
delta = df[mask_delta]

delta.to_csv("delta.csv")

In [173]:
#Mask des Cancel et time_delta > 0
delta_canceled = delta[delta['state'] == 'canceled']
delta_canceled

,rental_id,car_id,checkin_type,state,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes,time,time_state_convert,palier
204,543768,374169,connect,canceled,NaN,543010.0,210.0,CANCELED,0.0,0MIN
242,546160,352528,connect,canceled,NaN,546578.0,630.0,CANCELED,0.0,0MIN
504,564627,341431,mobile,canceled,NaN,552005.0,150.0,CANCELED,0.0,0MIN
637,568657,317378,connect,canceled,NaN,566412.0,210.0,CANCELED,0.0,0MIN
669,516550,377700,mobile,canceled,NaN,545076.0,720.0,CANCELED,0.0,0MIN
...,...,...,...,...,...,...,...,...,...,...
21172,566228,390871,connect,canceled,NaN,568465.0,60.0,CANCELED,0.0,0MIN
21197,567305,405564,mobile,canceled,NaN,552222.0,0.0,CANCELED,0.0,0MIN
21230,569706,245154,connect,canceled,NaN,558088.0,660.0,CANCELED,0.0,0MIN
21269,568049,381499,connect,canceled,NaN,562174.0,720.0,CANCELED,0.0,0MIN
21272,568241,396409,mobile,canceled,NaN,566136.0,570.0,CANCELED,0.0,0MIN

In [174]:
# Voiture Sauvées Calcul du nombre de clients perdu par rapport au temps d'attente

temps_cancel = [15, 30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 400, 500, 600, 700, 750]

for i in temps_cancel:
    cancel_now = (delta_canceled[(delta_canceled["time_delta_with_previous_rental_in_minutes"] <= i)])
    print(f"% d'annulation après {i} min d'attente pour 2e loc. : {round((cancel_now.shape[0]/delta.shape[0])*100,3)} % | {cancel_now.shape[0]} clients perdus au total : {round((cancel_now.shape[0]/df.shape[0])*100,2)} %")
    print(f"{i}min représente : {round(((delta_canceled.shape[0] - cancel_now.shape[0])/delta_canceled.shape[0])*100,2)} % | sauvés 👌 ")

% d'annulation après 15 min d'attente pour 2e loc. : 1.901 % | 35 clients perdus au total : 0.16 %
15min représente : 84.72 % | sauvés 👌
% d'annulation après 30 min d'attente pour 2e loc. : 2.336 % | 43 clients perdus au total : 0.2 %
30min représente : 81.22 % | sauvés 👌
% d'annulation après 60 min d'attente pour 2e loc. : 3.585 % | 66 clients perdus au total : 0.31 %
60min représente : 71.18 % | sauvés 👌
% d'annulation après 90 min d'attente pour 2e loc. : 4.02 % | 74 clients perdus au total : 0.35 %
90min représente : 67.69 % | sauvés 👌
% d'annulation après 120 min d'attente pour 2e loc. : 4.726 % | 87 clients perdus au total : 0.41 %
120min représente : 62.01 % | sauvés 👌
% d'annulation après 150 min d'attente pour 2e loc. : 5.269 % | 97 clients perdus au total : 0.46 %
150min représente : 57.64 % | sauvés 👌
% d'annulation après 180 min d'attente pour 2e loc. : 5.758 % | 106 clients perdus au total : 0.5 %
180min représente : 53.71 % | sauvés 👌
% d'annulation après 210 min d'attente pour 2e loc. : 6.355 % | 117 clients perdus au total : 0.55 %
210min représente : 48.91 % | sauvés 👌
% d'annulation après 240 min d'attente pour 2e loc. : 6.844 % | 126 clients perdus au total : 0.59 %
240min représente : 44.98 % | sauvés 👌
% d'annulation après 270 min d'attente pour 2e loc. : 7.061 % | 130 clients perdus au total : 0.61 %
270min représente : 43.23 % | sauvés 👌
% d'annulation après 300 min d'attente pour 2e loc. : 7.17 % | 132 clients perdus au total : 0.62 %
300min représente : 42.36 % | sauvés 👌
% d'annulation après 400 min d'attente pour 2e loc. : 7.876 % | 145 clients perdus au total : 0.68 %
400min représente : 36.68 % | sauvés 👌
% d'annulation après 500 min d'attente pour 2e loc. : 8.8 % | 162 clients perdus au total : 0.76 %
500min représente : 29.26 % | sauvés 👌
% d'annulation après 600 min d'attente pour 2e loc. : 10.429 % | 192 clients perdus au total : 0.9 %
600min représente : 16.16 % | sauvés 👌
% d'annulation après 700 min d'attente pour 2e loc. : 11.841 % | 218 clients perdus au total : 1.02 %
700min représente : 4.8 % | sauvés 👌
% d'annulation après 750 min d'attente pour 2e loc. : 12.439 % | 229 clients perdus au total : 1.07 %
750min représente : 0.0 % | sauvés 👌

In [175]:
delta_canceled.shape[0]

229

In [ ]:
# Nombre de Canceled pour cause de Delay au total

delta_canceled.shape[0]
df.shape[0]

# Pourcentage de Canceled suite au Delay

canceled_due_delay = (delta_canceled.shape[0]/df.shape[0])*100

print(f"% Canceled due au Retard en 2e locations :{round(canceled_due_delay, 2)}% 🚘")

% Canceled due au Retard en deux locations :1.07% 🚘

In [177]:
mask_canceled = df['state'] == 'canceled'
df_canceled = df[mask_canceled].shape[0]


canceled_total = (df_canceled/df.shape[0])*100

print(f"% Canceled sur la totalité des locations :{round(canceled_total, 2)}% 🚘")

% Canceled sur la totalité des locations :15.32% 🚘

In [178]:
# Script à modifier en fonction de "Voitures Sauvées"

print(f"au bout de 15 min : {round(35/df_canceled, 2)}% sur le total")
print(f"On part du principe que 84,72 % continue de louer. On peut se dire qu'on gagne : {(0.85*delta_canceled.shape[0])} de voitures 🚘 de plus")
print(f"Soit le % total d'affaire en plus : {round((194.65/df_canceled)*100, 2)} % ")

au bout de 15 min : 0.01% sur le total
On part du principe que 84,72 % continue de louer. On peut se dire qu'on gagne : 194.65 de voitures 🚘 de plus
Soit le % total d'affaire en plus : 5.96 %

In [ ]:
mask_canceled = df['state'] == 'canceled'
df_canceled = df[mask_canceled].shape[0]

# Préparation des données (comme avant)
time_bins = [0, 15, 30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 400, 500, 600, 700, 750]
labels = [f"{time_bins[i]}-{time_bins[i+1]} min" for i in range(len(time_bins)-1)]
delta_canceled['time_interval'] = pd.cut(
    delta_canceled['time_delta_with_previous_rental_in_minutes'],
    bins=time_bins,
    labels=labels,
    right=True,
    include_lowest=True
)
cancellation_counts = delta_canceled['time_interval'].value_counts().sort_index()

# Création du DataFrame pour Plotly
df_plot = cancellation_counts.reset_index()
df_plot.columns = ['Intervalle', 'Nombre']

# Création du graphique avec dégradé de couleur
fig = px.bar(
    df_plot,
    x='Intervalle',
    y='Nombre',
    color='Nombre',  # Dégradé basé sur la valeur
    color_continuous_scale='Plasma_r',  # Palette de couleurs
    title="Distribution des Annulations - Canceled - par Intervalle de Temps",
    labels={"Intervalle": "Intervalle de temps (minutes)", "Nombre": "Nombre d'annulations"}
)

# Personnalisation
fig.update_layout(
    xaxis_tickangle=-45,
    coloraxis_showscale=False,  # Masquer la légende de couleur si souhaité
    template="seaborn"
)

# Ajouter les valeurs sur les barres
fig.update_traces(
    text=df_plot['Nombre'],
    textposition='outside',
    textfont_size=10
)

fig.show()

/var/folders/mk/k32g1gsn4c1_yd1vbqdbpvw00000gn/T/ipykernel_1705/3341601834.py:8: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [349]:
import pandas as pd


# Masque pour les locations annulées
mask_canceled = df['state'] == 'canceled'

# Masque pour les locations avec un temps de battement inférieur à 30 minutes
# .notna() est important pour s'assurer qu'on ne compare pas des valeurs NaN
mask_early_delta = (df['time_delta_with_previous_rental_in_minutes'] >= 0) & \
                   (df['time_delta_with_previous_rental_in_minutes'] < 30)

# --- Étape 2 : Appliquer les deux masques pour obtenir le sous-ensemble ---

early_cancellations_df = df[mask_canceled & mask_early_delta]

# --- Étape 3 : Afficher les résultats pour l'enquête ---

print(f"Nombre total d'annulations avec un temps de battement < 30 min : {early_cancellations_df.shape[0]}")
print("\n--- Répartition par type de check-in pour ces annulations ---")
print(early_cancellations_df['checkin_type'].value_counts())

print("\n--- Répartition des temps de battement exacts (pour voir les cas à 0 min) ---")
print(early_cancellations_df['time_delta_with_previous_rental_in_minutes'].value_counts().sort_index())

print("\n--- Affichage des premières lignes de ces cas curieux ---")
# On affiche toutes les colonnes pour ne rien manquer
pd.set_option('display.max_columns', None) 
early_cancellations_df.head()

Nombre total d'annulations avec un temps de battement < 30 min : 35

--- Répartition par type de check-in pour ces annulations ---
checkin_type
connect    22
mobile     13
Name: count, dtype: int64

--- Répartition des temps de battement exacts (pour voir les cas à 0 min) ---
time_delta_with_previous_rental_in_minutes
0.0    35
Name: count, dtype: int64

--- Affichage des premières lignes de ces cas curieux ---

,rental_id,car_id,checkin_type,state,delay_at_checkout_in_minutes,previous_ended_rental_id,time_delta_with_previous_rental_in_minutes
1778,549128,367632,connect,canceled,NaN,545710.0,0.0
2181,559037,349171,connect,canceled,NaN,552392.0,0.0
2725,551958,403265,connect,canceled,NaN,551363.0,0.0
3401,569366,364783,mobile,canceled,NaN,563995.0,0.0
4158,557183,410939,connect,canceled,NaN,565171.0,0.0